import { Model } from './types';

export const asianGroupModels: Model[] = [
    { "id": "daewoo-kalos", "brandId": "daewoo", "name": "Kalos", "slug": "kalos", "series": "Kalos" },
    { "id": "daewoo-lanos", "brandId": "daewoo", "name": "Lanos", "slug": "lanos", "series": "Lanos" },
    { "id": "daewoo-matiz", "brandId": "daewoo", "name": "Matiz", "slug": "matiz", "series": "Matiz" },
    { "id": "daewoo-nexia", "brandId": "daewoo", "name": "Nexia", "slug": "nexia", "series": "Nexia" },
    { "id": "daewoo-nubira", "brandId": "daewoo", "name": "Nubira", "slug": "nubira", "series": "Nubira" },
    { "id": "daewoo-musso", "brandId": "daewoo", "name": "Musso", "slug": "musso", "series": "Musso" },
    { "id": "daewoo-korando", "brandId": "daewoo", "name": "Korando", "slug": "korando", "series": "Korando" },
    { "id": "daewoo-evanda", "brandId": "daewoo", "name": "Evanda", "slug": "evanda", "series": "Evanda" },
    { "id": "daewoo-espero", "brandId": "daewoo", "name": "Espero", "slug": "espero", "series": "Espero" },
    { "id": "daewoo-leganza", "brandId": "daewoo", "name": "Leganza", "slug": "leganza", "series": "Leganza" },
    { "id": "daewoo-tacuma", "brandId": "daewoo", "name": "Tacuma", "slug": "tacuma", "series": "Tacuma" },
    { "id": "daewoo-tico", "brandId": "daewoo", "name": "Tico", "slug": "tico", "series": "Tico" },
    { "id": "honda-accord-6", "brandId": "honda", "name": "Accord VI", "slug": "accord-6", "series": "Accord", "keywords": ["VTEC", "2.0 TD", "Type-R"] },
    { "id": "honda-accord-7", "brandId": "honda", "name": "Accord VII", "slug": "accord-7", "series": "Accord", "keywords": ["2.0 i-VTEC", "2.4 i-VTEC", "2.2 i-CTDI", "Type-S"] },
    { "id": "honda-accord-8", "brandId": "honda", "name": "Accord VIII", "slug": "accord-8", "series": "Accord", "keywords": ["2.0 i-VTEC", "2.4 i-VTEC", "2.2 i-DTEC", "Type-S"] },
    { "id": "honda-city", "brandId": "honda", "name": "City", "slug": "city", "series": "City" },
    { "id": "honda-civic-6", "brandId": "honda", "name": "Civic VI", "slug": "civic-6", "series": "Civic", "keywords": ["VTI", "Type-R", "1.4", "1.5", "1.6"] },
    { "id": "honda-civic-7", "brandId": "honda", "name": "Civic VII", "slug": "civic-7", "series": "Civic", "keywords": ["Type-R", "1.7 CTDI", "1.4", "1.6"] },
    { "id": "honda-civic-8", "brandId": "honda", "name": "Civic VIII", "slug": "civic-8", "series": "Civic", "keywords": ["Type-R", "UFO", "ufo civic", "1.8 i-VTEC", "2.2 CTDI", "R18A", "N22A", "K20A"] },
    { "id": "honda-civic-9", "brandId": "honda", "name": "Civic IX", "slug": "civic-9", "series": "Civic", "keywords": ["Type-R", "1.6 i-DTEC", "1.8 i-VTEC", "N16A", "R18Z"] },
    { "id": "honda-civic-10", "brandId": "honda", "name": "Civic X", "slug": "civic-10", "series": "Civic" },
    { "id": "honda-civic-11", "brandId": "honda", "name": "Civic XI", "slug": "civic-11", "series": "Civic" },
    { "id": "honda-integra", "brandId": "honda", "name": "Integra", "slug": "integra", "series": "Integra" },
    { "id": "honda-legend", "brandId": "honda", "name": "Legend", "slug": "legend", "series": "Legend" },
    { "id": "honda-prelude", "brandId": "honda", "name": "Prelude", "slug": "prelude", "series": "Prelude" },
    { "id": "honda-stream", "brandId": "honda", "name": "Stream", "slug": "stream", "series": "Stream" },
    { "id": "honda-insight", "brandId": "honda", "name": "Insight", "slug": "insight", "series": "Insight" },
    { "id": "honda-nsx", "brandId": "honda", "name": "NSX", "slug": "nsx", "series": "NSX" },
    { "id": "honda-crv-1", "brandId": "honda", "name": "CR-V I", "slug": "crv-1", "series": "CR-V" },
    { "id": "honda-crv-2", "brandId": "honda", "name": "CR-V II", "slug": "crv-2", "series": "CR-V" },
    { "id": "honda-crv-3", "brandId": "honda", "name": "CR-V III", "slug": "crv-3", "series": "CR-V" },
    { "id": "honda-crv-4", "brandId": "honda", "name": "CR-V IV", "slug": "crv-4", "series": "CR-V" },
    { "id": "honda-crv-5", "brandId": "honda", "name": "CR-V V", "slug": "crv-5", "series": "CR-V" },
    { "id": "honda-crz", "brandId": "honda", "name": "CR-Z", "slug": "crz", "series": "CR-Z" },
    { "id": "honda-e", "brandId": "honda", "name": "e", "slug": "e", "series": "e" },
    { "id": "honda-frv", "brandId": "honda", "name": "FR-V", "slug": "frv", "series": "FR-V" },
    { "id": "honda-hrv-1", "brandId": "honda", "name": "HR-V I", "slug": "hrv-1", "series": "HR-V" },
    { "id": "honda-hrv-2", "brandId": "honda", "name": "HR-V II", "slug": "hrv-2", "series": "HR-V" },
    { "id": "honda-hrv-3", "brandId": "honda", "name": "HR-V III", "slug": "hrv-3", "series": "HR-V" },
    { "id": "honda-jazz-1", "brandId": "honda", "name": "Jazz I", "slug": "jazz-1", "series": "Jazz" },
    { "id": "honda-jazz-2", "brandId": "honda", "name": "Jazz II", "slug": "jazz-2", "series": "Jazz" },
    { "id": "honda-jazz-3", "brandId": "honda", "name": "Jazz III", "slug": "jazz-3", "series": "Jazz" },
    { "id": "honda-jazz-4", "brandId": "honda", "name": "Jazz IV", "slug": "jazz-4", "series": "Jazz" },
    { "id": "honda-s2000", "brandId": "honda", "name": "S2000", "slug": "s2000", "series": "S2000" },
    { "id": "hyundai-bayon", "brandId": "hyundai", "name": "Bayon", "slug": "bayon", "series": "Bayon" },
    { "id": "hyundai-elantra", "brandId": "hyundai", "name": "Elantra", "slug": "elantra", "series": "Elantra" },
    { "id": "hyundai-accent", "brandId": "hyundai", "name": "Accent", "slug": "accent", "series": "Accent" },
    { "id": "hyundai-atos", "brandId": "hyundai", "name": "Atos", "slug": "atos", "series": "Atos" },
    { "id": "hyundai-coupe", "brandId": "hyundai", "name": "Coupe", "slug": "coupe", "series": "Coupe" },
    { "id": "hyundai-genesis", "brandId": "hyundai", "name": "Genesis", "slug": "genesis", "series": "Genesis" },
    { "id": "hyundai-getz", "brandId": "hyundai", "name": "Getz", "slug": "getz", "series": "Getz" },
    { "id": "hyundai-h1", "brandId": "hyundai", "name": "H-1 / Starex", "slug": "h1", "series": "H-1" },
    { "id": "hyundai-matrix", "brandId": "hyundai", "name": "Matrix", "slug": "matrix", "series": "Matrix" },
    { "id": "hyundai-sonata", "brandId": "hyundai", "name": "Sonata", "slug": "sonata", "series": "Sonata" },
    { "id": "hyundai-terracan", "brandId": "hyundai", "name": "Terracan", "slug": "terracan", "series": "Terracan" },
    { "id": "hyundai-trajet", "brandId": "hyundai", "name": "Trajet", "slug": "trajet", "series": "Trajet" },
    { "id": "hyundai-veloster", "brandId": "hyundai", "name": "Veloster", "slug": "veloster", "series": "Veloster" },
    { "id": "hyundai-i10-1", "brandId": "hyundai", "name": "i10", "slug": "i10-1", "series": "i10", "keywords": ["1.1", "1.2"] },
    { "id": "hyundai-i20-1", "brandId": "hyundai", "name": "i20 I", "slug": "i20-1", "series": "i20", "keywords": ["1.2", "1.4 CRDI"] },
    { "id": "hyundai-i20-2", "brandId": "hyundai", "name": "i20 II", "slug": "i20-2", "series": "i20" },
    { "id": "hyundai-i20-3", "brandId": "hyundai", "name": "i20 III", "slug": "i20-3", "series": "i20" },
    { "id": "hyundai-i30-1", "brandId": "hyundai", "name": "i30 I", "slug": "i30-1", "series": "i30", "keywords": ["CW", "1.4", "1.6 CRDI", "G4FA", "D4FB"] },
    { "id": "hyundai-i30-2", "brandId": "hyundai", "name": "i30 II", "slug": "i30-2", "series": "i30", "keywords": ["CW", "Coupe", "1.6 CRDI", "D4FB"] },
    { "id": "hyundai-i30-3", "brandId": "hyundai", "name": "i30 III", "slug": "i30-3", "series": "i30", "keywords": ["N", "Fastback", "CW", "1.4 T-GDI", "1.6 CRDI", "G4LD", "D4FE"] },
    { "id": "hyundai-i40", "brandId": "hyundai", "name": "i40", "slug": "i40", "series": "i40" },
    { "id": "hyundai-ioniq", "brandId": "hyundai", "name": "Ioniq", "slug": "ioniq", "series": "Ioniq" },
    { "id": "hyundai-ioniq5", "brandId": "hyundai", "name": "Ioniq 5", "slug": "ioniq5", "series": "Ioniq 5" },
    { "id": "hyundai-ioniq6", "brandId": "hyundai", "name": "Ioniq 6", "slug": "ioniq6", "series": "Ioniq 6" },
    { "id": "hyundai-ix20", "brandId": "hyundai", "name": "ix20", "slug": "ix20", "series": "ix20" },
    { "id": "hyundai-ix35", "brandId": "hyundai", "name": "ix35", "slug": "ix35", "series": "ix35", "keywords": ["1.7 CRDI", "2.0 CRDI"] },
    { "id": "hyundai-kona", "brandId": "hyundai", "name": "Kona", "slug": "kona", "series": "Kona" },
    { "id": "hyundai-santa-fe-1", "brandId": "hyundai", "name": "Santa Fe I", "slug": "santa-fe-1", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-2", "brandId": "hyundai", "name": "Santa Fe II", "slug": "santa-fe-2", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-3", "brandId": "hyundai", "name": "Santa Fe III", "slug": "santa-fe-3", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-4", "brandId": "hyundai", "name": "Santa Fe IV", "slug": "santa-fe-4", "series": "Santa Fe" },
    { "id": "hyundai-tucson-1", "brandId": "hyundai", "name": "Tucson I", "slug": "tucson-1", "series": "Tucson", "keywords": ["2.0 CRDI"] },
    { "id": "hyundai-tucson-3", "brandId": "hyundai", "name": "Tucson III", "slug": "tucson-3", "series": "Tucson", "keywords": ["1.6 CRDI", "1.7 CRDI", "1.6 T-GDI"] },
    { "id": "hyundai-tucson-4", "brandId": "hyundai", "name": "Tucson IV", "slug": "tucson-4", "series": "Tucson" },
    { "id": "infiniti-fx", "brandId": "infiniti", "name": "FX / QX70", "slug": "fx", "series": "FX" },
    { "id": "infiniti-ex", "brandId": "infiniti", "name": "EX / QX50", "slug": "ex", "series": "EX" },
    { "id": "infiniti-g", "brandId": "infiniti", "name": "G / Q40", "slug": "g", "series": "G" },
    { "id": "infiniti-m", "brandId": "infiniti", "name": "M / Q70", "slug": "m", "series": "M" },
    { "id": "infiniti-q30", "brandId": "infiniti", "name": "Q30", "slug": "q30", "series": "Q30" },
    { "id": "infiniti-q60", "brandId": "infiniti", "name": "Q60", "slug": "q60", "series": "Q60" },
    { "id": "infiniti-qx30", "brandId": "infiniti", "name": "QX30", "slug": "qx30", "series": "QX30" },
    { "id": "infiniti-q50", "brandId": "infiniti", "name": "Q50", "slug": "q50", "series": "Q50" },
    { "id": "isuzu-dmax", "brandId": "isuzu", "name": "D-Max", "slug": "d-max", "series": "D-Max" },
    { "id": "isuzu-trooper", "brandId": "isuzu", "name": "Trooper", "slug": "trooper", "series": "Trooper" },
    { "id": "kia-carens-3", "brandId": "kia", "name": "Carens III", "slug": "carens-3", "series": "Carens" },
    { "id": "kia-carens-4", "brandId": "kia", "name": "Carens IV", "slug": "carens-4", "series": "Carens" },
    { "id": "kia-carnival", "brandId": "kia", "name": "Carnival", "slug": "carnival", "series": "Carnival" },
    { "id": "kia-cerato", "brandId": "kia", "name": "Cerato", "slug": "cerato", "series": "Cerato" },
    { "id": "kia-magentis", "brandId": "kia", "name": "Magentis", "slug": "magentis", "series": "Magentis" },
    { "id": "kia-pride", "brandId": "kia", "name": "Pride", "slug": "pride", "series": "Pride" },
    { "id": "kia-proceed", "brandId": "kia", "name": "ProCeed", "slug": "proceed", "series": "Ceed" },
    { "id": "kia-sephia", "brandId": "kia", "name": "Sephia", "slug": "sephia", "series": "Sephia" },
    { "id": "kia-shuma", "brandId": "kia", "name": "Shuma", "slug": "shuma", "series": "Shuma" },
    { "id": "kia-venga", "brandId": "kia", "name": "Venga", "slug": "venga", "series": "Venga" },
    { "id": "kia-ceed-1", "brandId": "kia", "name": "Cee'd I", "slug": "ceed-1", "series": "Cee'd", "keywords": ["SW", "pro_ceed", "1.4", "1.6 CRDI"] },
    { "id": "kia-ceed-2", "brandId": "kia", "name": "Cee'd II", "slug": "ceed-2", "series": "Cee'd", "keywords": ["SW", "pro_ceed", "GT", "1.6 CRDI", "1.4 GDI"] },
    { "id": "kia-ceed-3", "brandId": "kia", "name": "Ceed III", "slug": "ceed-3", "series": "Ceed", "keywords": ["SW", "GT", "Proceed", "Xceed"] },
    { "id": "kia-ev6", "brandId": "kia", "name": "EV6", "slug": "ev6", "series": "EV" },
    { "id": "kia-ev9", "brandId": "kia", "name": "EV9", "slug": "ev9", "series": "EV" },
    { "id": "kia-ev3", "brandId": "kia", "name": "EV3", "slug": "ev3", "series": "EV" },
    { "id": "kia-niro-1", "brandId": "kia", "name": "Niro I", "slug": "niro-1", "series": "Niro" },
    { "id": "kia-niro-2", "brandId": "kia", "name": "Niro II", "slug": "niro-2", "series": "Niro" },
    { "id": "kia-optima-3", "brandId": "kia", "name": "Optima III", "slug": "optima-3", "series": "Optima" },
    { "id": "kia-optima-4", "brandId": "kia", "name": "Optima IV", "slug": "optima-4", "series": "Optima" },
    { "id": "kia-picanto-1", "brandId": "kia", "name": "Picanto I", "slug": "picanto-1", "series": "Picanto" },
    { "id": "kia-picanto-2", "brandId": "kia", "name": "Picanto II", "slug": "picanto-2", "series": "Picanto" },
    { "id": "kia-picanto-3", "brandId": "kia", "name": "Picanto III", "slug": "picanto-3", "series": "Picanto" },
    { "id": "kia-rio-2", "brandId": "kia", "name": "Rio II", "slug": "rio-2", "series": "Rio", "keywords": ["1.4", "1.5 CRDI"] },
    { "id": "kia-rio-3", "brandId": "kia", "name": "Rio III", "slug": "rio-3", "series": "Rio", "keywords": ["1.1 CRDI", "1.2", "1.4 CRDI"] },
    { "id": "kia-rio-4", "brandId": "kia", "name": "Rio IV", "slug": "rio-4", "series": "Rio", "keywords": ["1.0 T-GDI", "1.2", "1.4"] },
    { "id": "kia-sorento-1", "brandId": "kia", "name": "Sorento I", "slug": "sorento-1", "series": "Sorento" },
    { "id": "kia-sorento-2", "brandId": "kia", "name": "Sorento II", "slug": "sorento-2", "series": "Sorento" },
    { "id": "kia-sorento-3", "brandId": "kia", "name": "Sorento III", "slug": "sorento-3", "series": "Sorento" },
    { "id": "kia-sorento-4", "brandId": "kia", "name": "Sorento IV", "slug": "sorento-4", "series": "Sorento" },
    { "id": "kia-soul", "brandId": "kia", "name": "Soul", "slug": "soul", "series": "Soul" },
    { "id": "kia-sportage-2", "brandId": "kia", "name": "Sportage II", "slug": "sportage-2", "series": "Sportage", "keywords": ["2.0 CRDI", "2.7 V6"] },
    { "id": "kia-sportage-3", "brandId": "kia", "name": "Sportage III", "slug": "sportage-3", "series": "Sportage", "keywords": ["1.6 GDI", "1.7 CRDI", "2.0 CRDI"] },
    { "id": "kia-sportage-4", "brandId": "kia", "name": "Sportage IV", "slug": "sportage-4", "series": "Sportage", "keywords": ["1.6 GDI", "1.6 T-GDI", "1.7 CRDI", "2.0 CRDI"] },
    { "id": "kia-sportage-5", "brandId": "kia", "name": "Sportage V", "slug": "sportage-5", "series": "Sportage", "keywords": ["1.6 T-GDI", "1.6 CRDI", "Hybrid", "PHEV"] },
    { "id": "kia-stinger", "brandId": "kia", "name": "Stinger", "slug": "stinger", "series": "Stinger" },
    { "id": "kia-stonic", "brandId": "kia", "name": "Stonic", "slug": "stonic", "series": "Stonic" },
    { "id": "kia-xceed", "brandId": "kia", "name": "XCeed", "slug": "xceed", "series": "XCeed" },
    { "id": "lexus-ct", "brandId": "lexus", "name": "CT 200h", "slug": "ct", "series": "CT" },
    { "id": "lexus-es", "brandId": "lexus", "name": "ES", "slug": "es", "series": "ES" },
    { "id": "lexus-gs", "brandId": "lexus", "name": "GS", "slug": "gs", "series": "GS" },
    { "id": "lexus-ls", "brandId": "lexus", "name": "LS", "slug": "ls", "series": "LS" },
    { "id": "lexus-rc", "brandId": "lexus", "name": "RC", "slug": "rc", "series": "RC" },
    { "id": "lexus-sc", "brandId": "lexus", "name": "SC", "slug": "sc", "series": "SC" },
    { "id": "lexus-ux", "brandId": "lexus", "name": "UX", "slug": "ux", "series": "UX" },
    { "id": "lexus-lbx", "brandId": "lexus", "name": "LBX", "slug": "lbx", "series": "LBX" },
    { "id": "lexus-rz", "brandId": "lexus", "name": "RZ", "slug": "rz", "series": "RZ" },
    { "id": "lexus-is-1", "brandId": "lexus", "name": "IS I", "slug": "is-1", "series": "IS" },
    { "id": "lexus-is-2", "brandId": "lexus", "name": "IS II", "slug": "is-2", "series": "IS" },
    { "id": "lexus-is-3", "brandId": "lexus", "name": "IS III", "slug": "is-3", "series": "IS" },
    { "id": "lexus-nx", "brandId": "lexus", "name": "NX", "slug": "nx", "series": "NX" },
    { "id": "lexus-rx-2", "brandId": "lexus", "name": "RX II", "slug": "rx-2", "series": "RX" },
    { "id": "lexus-rx-3", "brandId": "lexus", "name": "RX III", "slug": "rx-3", "series": "RX" },
    { "id": "lexus-rx-4", "brandId": "lexus", "name": "RX IV", "slug": "rx-4", "series": "RX" },
    { "id": "mazda-2-dy", "brandId": "mazda", "name": "Mazda 2", "slug": "mazda-2-dy", "series": "2", "keywords": ["1.25", "1.4", "1.6", "1.4 CD"] },
    { "id": "mazda-2-de", "brandId": "mazda", "name": "Mazda 2", "slug": "mazda-2-de", "series": "2", "keywords": ["1.3", "1.5", "1.6 MZ-CD"] },
    { "id": "mazda-2-dj", "brandId": "mazda", "name": "Mazda 2", "slug": "mazda-2-dj", "series": "2", "keywords": ["SkyActiv-G", "SkyActiv-D"] },
    { "id": "mazda-3-bk", "brandId": "mazda", "name": "Mazda 3", "slug": "mazda-3-bk", "series": "3", "keywords": ["MPS", "1.6", "2.0"] },
    { "id": "mazda-3-bl", "brandId": "mazda", "name": "Mazda 3", "slug": "mazda-3-bl", "series": "3", "keywords": ["MPS", "1.6 MZ-CD"] },
    { "id": "mazda-3-bm", "brandId": "mazda", "name": "Mazda 3", "slug": "mazda-3-bm", "series": "3", "keywords": ["SkyActiv"] },
    { "id": "mazda-3-bp", "brandId": "mazda", "name": "Mazda 3", "slug": "mazda-3-bp", "series": "3", "keywords": ["SkyActiv-X"] },
    { "id": "mazda-5-cr", "brandId": "mazda", "name": "Mazda 5", "slug": "mazda-5-cr", "series": "5" },
    { "id": "mazda-5-cw", "brandId": "mazda", "name": "Mazda 5", "slug": "mazda-5-cw", "series": "5" },
    { "id": "mazda-6-gg", "brandId": "mazda", "name": "Mazda 6", "slug": "mazda-6-gg", "series": "6", "keywords": ["MPS", "2.0 CD"] },
    { "id": "mazda-6-gh", "brandId": "mazda", "name": "Mazda 6", "slug": "mazda-6-gh", "series": "6", "keywords": ["2.2 CD", "2.0 CD"] },
    { "id": "mazda-6-gj", "brandId": "mazda", "name": "Mazda 6", "slug": "mazda-6-gj", "series": "6", "keywords": ["SkyActiv"] },
    { "id": "mazda-cx3", "brandId": "mazda", "name": "CX-3", "slug": "cx-3", "series": "CX-3" },
    { "id": "mazda-cx30", "brandId": "mazda", "name": "CX-30", "slug": "cx-30", "series": "CX-30" },
    { "id": "mazda-cx9", "brandId": "mazda", "name": "CX-9", "slug": "cx-9", "series": "CX-9" },
    { "id": "mazda-cx60", "brandId": "mazda", "name": "CX-60", "slug": "cx-60", "series": "CX-60" },
    { "id": "mazda-cx80", "brandId": "mazda", "name": "CX-80", "slug": "cx-80", "series": "CX-80" },
    { "id": "mazda-demio", "brandId": "mazda", "name": "Demio", "slug": "demio", "series": "Demio" },
    { "id": "mazda-mpv", "brandId": "mazda", "name": "MPV", "slug": "mpv", "series": "MPV" },
    { "id": "mazda-mx3", "brandId": "mazda", "name": "MX-3", "slug": "mx3", "series": "MX-3" },
    { "id": "mazda-premacy", "brandId": "mazda", "name": "Premacy", "slug": "premacy", "series": "Premacy" },
    { "id": "mazda-rx7", "brandId": "mazda", "name": "RX-7", "slug": "rx7", "series": "RX-7" },
    { "id": "mazda-rx8", "brandId": "mazda", "name": "RX-8", "slug": "rx8", "series": "RX-8" },
    { "id": "mazda-tribute", "brandId": "mazda", "name": "Tribute", "slug": "tribute", "series": "Tribute" },
    { "id": "mazda-xedos", "brandId": "mazda", "name": "Xedos 6/9", "slug": "xedos", "series": "Xedos" },
    { "id": "mazda-bseries", "brandId": "mazda", "name": "B-Series", "slug": "b-series", "series": "Pickup" },
    { "id": "mazda-bt50", "brandId": "mazda", "name": "BT-50", "slug": "bt-50", "series": "Pickup" },
    { "id": "mazda-cx5-ke", "brandId": "mazda", "name": "CX-5", "slug": "cx-5-ke", "series": "CX-5" },
    { "id": "mazda-cx5-kf", "brandId": "mazda", "name": "CX-5", "slug": "cx-5-kf", "series": "CX-5" },
    { "id": "mazda-cx7", "brandId": "mazda", "name": "CX-7", "slug": "cx-7", "series": "CX-7" },
    { "id": "mazda-mx5-nb", "brandId": "mazda", "name": "MX-5", "slug": "mx5-nb", "series": "MX-5" },
    { "id": "mazda-mx5-nc", "brandId": "mazda", "name": "MX-5", "slug": "mx5-nc", "series": "MX-5" },
    { "id": "mazda-mx5-nd", "brandId": "mazda", "name": "MX-5", "slug": "mx5-nd", "series": "MX-5" },
    { "id": "mitsubishi-asx", "brandId": "mitsubishi", "name": "ASX", "slug": "asx", "series": "ASX" },
    { "id": "mitsubishi-colt", "brandId": "mitsubishi", "name": "Colt", "slug": "colt", "series": "Colt" },
    { "id": "mitsubishi-eclipse-cross", "brandId": "mitsubishi", "name": "Eclipse Cross", "slug": "eclipse-cross", "series": "Eclipse" },
    { "id": "mitsubishi-eclipse", "brandId": "mitsubishi", "name": "Eclipse", "slug": "eclipse", "series": "Eclipse" },
    { "id": "mitsubishi-carisma", "brandId": "mitsubishi", "name": "Carisma", "slug": "carisma", "series": "Carisma" },
    { "id": "mitsubishi-galant", "brandId": "mitsubishi", "name": "Galant", "slug": "galant", "series": "Galant" },
    { "id": "mitsubishi-grandis", "brandId": "mitsubishi", "name": "Grandis", "slug": "grandis", "series": "Grandis" },
    { "id": "mitsubishi-mirage", "brandId": "mitsubishi", "name": "Mirage", "slug": "mirage", "series": "Mirage" },
    { "id": "mitsubishi-pajero-pinin", "brandId": "mitsubishi", "name": "Pajero Pinin", "slug": "pajero-pinin", "series": "Pajero" },
    { "id": "mitsubishi-pajero-sport", "brandId": "mitsubishi", "name": "Pajero Sport", "slug": "pajero-sport", "series": "Pajero" },
    { "id": "mitsubishi-space-wagon", "brandId": "mitsubishi", "name": "Space Wagon", "slug": "space-wagon", "series": "Space Wagon" },
    { "id": "mitsubishi-imiev", "brandId": "mitsubishi", "name": "i-MiEV", "slug": "imiev", "series": "i-MiEV" },
    { "id": "mitsubishi-l200-4", "brandId": "mitsubishi", "name": "L200 IV", "slug": "l200-4", "series": "L200" },
    { "id": "mitsubishi-l200-5", "brandId": "mitsubishi", "name": "L200 V", "slug": "l200-5", "series": "L200" },
    { "id": "mitsubishi-lancer", "brandId": "mitsubishi", "name": "Lancer", "slug": "lancer", "series": "Lancer", "keywords": ["EVO", "Evolution", "1.5", "1.8", "2.0 DI-D"] },
    { "id": "mitsubishi-outlander-1", "brandId": "mitsubishi", "name": "Outlander I", "slug": "outlander-1", "series": "Outlander", "keywords": ["2.0 Turbo", "4WD"] },
    { "id": "mitsubishi-outlander-2", "brandId": "mitsubishi", "name": "Outlander II", "slug": "outlander-2", "series": "Outlander", "keywords": ["2.0 DI-D", "2.2 DI-D", "4WD"] },
    { "id": "mitsubishi-outlander-3", "brandId": "mitsubishi", "name": "Outlander III", "slug": "outlander-3", "series": "Outlander", "keywords": ["PHEV", "Hybrid", "2.2 DI-D"] },
    { "id": "mitsubishi-pajero-3", "brandId": "mitsubishi", "name": "Pajero III", "slug": "pajero-3", "series": "Pajero", "keywords": ["3.2 DI-D", "Wagon"] },
    { "id": "mitsubishi-pajero-4", "brandId": "mitsubishi", "name": "Pajero IV", "slug": "pajero-4", "series": "Pajero", "keywords": ["3.2 DI-D", "Wagon"] },
    { "id": "mitsubishi-space-star", "brandId": "mitsubishi", "name": "Space Star", "slug": "space-star", "series": "Space Star", "keywords": ["1.0", "1.2", "1.3", "1.6", "1.9 DI-D"] },
    { "id": "nissan-almera-n16", "brandId": "nissan", "name": "Almera", "slug": "almera-n16", "series": "Almera" },
    { "id": "nissan-almera-tino", "brandId": "nissan", "name": "Almera Tino", "slug": "almera-tino", "series": "Almera" },
    { "id": "nissan-350z", "brandId": "nissan", "name": "350Z", "slug": "350z", "series": "Z" },
    { "id": "nissan-370z", "brandId": "nissan", "name": "370Z", "slug": "370z", "series": "Z" },
    { "id": "nissan-maxima", "brandId": "nissan", "name": "Maxima", "slug": "maxima", "series": "Maxima" },
    { "id": "nissan-murano", "brandId": "nissan", "name": "Murano", "slug": "murano", "series": "Murano" },
    { "id": "nissan-patrol", "brandId": "nissan", "name": "Patrol", "slug": "patrol", "series": "Patrol" },
    { "id": "nissan-pickup", "brandId": "nissan", "name": "Pick Up", "slug": "pickup", "series": "Pickup" },
    { "id": "nissan-sunny", "brandId": "nissan", "name": "Sunny", "slug": "sunny", "series": "Sunny" },
    { "id": "nissan-terrano", "brandId": "nissan", "name": "Terrano", "slug": "terrano", "series": "Terrano" },
    { "id": "nissan-tiida", "brandId": "nissan", "name": "Tiida", "slug": "tiida", "series": "Tiida" },
    { "id": "nissan-ariya", "brandId": "nissan", "name": "Ariya", "slug": "ariya", "series": "Ariya" },
    { "id": "nissan-interstar", "brandId": "nissan", "name": "Interstar", "slug": "interstar", "series": "Van" },
    { "id": "nissan-kubistar", "brandId": "nissan", "name": "Kubistar", "slug": "kubistar", "series": "Van" },
    { "id": "nissan-nv200", "brandId": "nissan", "name": "NV200", "slug": "nv200", "series": "Van" },
    { "id": "nissan-nv300", "brandId": "nissan", "name": "NV300", "slug": "nv300", "series": "Van" },
    { "id": "nissan-nv400", "brandId": "nissan", "name": "NV400", "slug": "nv400", "series": "Van" },
    { "id": "nissan-primastar", "brandId": "nissan", "name": "Primastar", "slug": "primastar", "series": "Van" },
    { "id": "nissan-townstar", "brandId": "nissan", "name": "Townstar", "slug": "townstar", "series": "Van" },
    { "id": "nissan-juke-1", "brandId": "nissan", "name": "Juke I", "slug": "juke-1", "series": "Juke", "keywords": ["1.6", "1.5 DCI"] },
    { "id": "nissan-juke-2", "brandId": "nissan", "name": "Juke II", "slug": "juke-2", "series": "Juke" },
    { "id": "nissan-leaf-1", "brandId": "nissan", "name": "Leaf I", "slug": "leaf-1", "series": "Leaf" },
    { "id": "nissan-leaf-2", "brandId": "nissan", "name": "Leaf II", "slug": "leaf-2", "series": "Leaf" },
    { "id": "nissan-micra-k11", "brandId": "nissan", "name": "Micra", "slug": "micra-k11", "series": "Micra", "keywords": ["K11", "Bakancs", "Bakancs Micra", "1.0", "1.3"] },
    { "id": "nissan-micra-k12", "brandId": "nissan", "name": "Micra", "slug": "micra-k12", "series": "Micra" },
    { "id": "nissan-micra-k13", "brandId": "nissan", "name": "Micra", "slug": "micra-k13", "series": "Micra" },
    { "id": "nissan-micra-k14", "brandId": "nissan", "name": "Micra", "slug": "micra-k14", "series": "Micra" },
    { "id": "nissan-navara-d40", "brandId": "nissan", "name": "Navara", "slug": "navara-d40", "series": "Navara" },
    { "id": "nissan-navara-d23", "brandId": "nissan", "name": "Navara", "slug": "navara-d23", "series": "Navara" },
    { "id": "nissan-note-e11", "brandId": "nissan", "name": "Note I", "slug": "note-e11", "series": "Note" },
    { "id": "nissan-note-e12", "brandId": "nissan", "name": "Note II", "slug": "note-e12", "series": "Note" },
    { "id": "nissan-pathfinder-r51", "brandId": "nissan", "name": "Pathfinder", "slug": "pathfinder-r51", "series": "Pathfinder" },
    { "id": "nissan-primera-p12", "brandId": "nissan", "name": "Primera", "slug": "primera-p12", "series": "Primera" },
    { "id": "nissan-qashqai-j10", "brandId": "nissan", "name": "Qashqai", "slug": "qashqai-j10", "series": "Qashqai", "keywords": ["+2", "1.5 DCI", "1.6 DCI", "2.0 DCI"] },
    { "id": "nissan-qashqai-j11", "brandId": "nissan", "name": "Qashqai", "slug": "qashqai-j11", "series": "Qashqai", "keywords": ["1.2 DIG-T", "1.5 DCI", "1.6 DCI"] },
    { "id": "nissan-qashqai-j12", "brandId": "nissan", "name": "Qashqai", "slug": "qashqai-j12", "series": "Qashqai" },
    { "id": "nissan-xtrail-t30", "brandId": "nissan", "name": "X-Trail", "slug": "xtrail-t30", "series": "X-Trail" },
    { "id": "nissan-xtrail-t31", "brandId": "nissan", "name": "X-Trail", "slug": "xtrail-t31", "series": "X-Trail" },
    { "id": "nissan-xtrail-t32", "brandId": "nissan", "name": "X-Trail", "slug": "xtrail-t32", "series": "X-Trail" },
    { "id": "nissan-xtrail-t33", "brandId": "nissan", "name": "X-Trail", "slug": "xtrail-t33", "series": "X-Trail" },
    { "id": "subaru-forester-2", "brandId": "subaru", "name": "Forester II", "slug": "forester-2", "series": "Forester", "keywords": ["2.0 Turbo", "XT"] },
    { "id": "subaru-forester-3", "brandId": "subaru", "name": "Forester III", "slug": "forester-3", "series": "Forester", "keywords": ["2.0 D", "Boxer Diesel"] },
    { "id": "subaru-forester-4", "brandId": "subaru", "name": "Forester IV", "slug": "forester-4", "series": "Forester", "keywords": ["2.0 D", "Boxer Diesel"] },
    { "id": "subaru-impreza-2", "brandId": "subaru", "name": "Impreza II", "slug": "impreza-2", "series": "Impreza" },
    { "id": "subaru-impreza-3", "brandId": "subaru", "name": "Impreza III", "slug": "impreza-3", "series": "Impreza" },
    { "id": "subaru-legacy-4", "brandId": "subaru", "name": "Legacy IV", "slug": "legacy-4", "series": "Legacy" },
    { "id": "subaru-outback-3", "brandId": "subaru", "name": "Outback III", "slug": "outback-3", "series": "Outback" },
    { "id": "subaru-outback-4", "brandId": "subaru", "name": "Outback IV", "slug": "outback-4", "series": "Outback" },
    { "id": "subaru-xv", "brandId": "subaru", "name": "XV/Crosstrek", "slug": "xv", "series": "XV" },
    { "id": "subaru-brz", "brandId": "subaru", "name": "BRZ", "slug": "brz", "series": "BRZ" },
    { "id": "subaru-justy", "brandId": "subaru", "name": "Justy", "slug": "justy", "series": "Justy" },
    { "id": "subaru-levorg", "brandId": "subaru", "name": "Levorg", "slug": "levorg", "series": "Levorg" },
    { "id": "subaru-tribeca", "brandId": "subaru", "name": "Tribeca", "slug": "tribeca", "series": "Tribeca" },
    { "id": "subaru-solterra", "brandId": "subaru", "name": "Solterra", "slug": "solterra", "series": "Solterra" },
    { "id": "subaru-svx", "brandId": "subaru", "name": "SVX", "slug": "svx", "series": "SVX" },
    { "id": "suzuki-alto", "brandId": "suzuki", "name": "Alto", "slug": "alto", "series": "Alto" },
    { "id": "suzuki-baleno", "brandId": "suzuki", "name": "Baleno", "slug": "baleno", "series": "Baleno" },
    { "id": "suzuki-celerio", "brandId": "suzuki", "name": "Celerio", "slug": "celerio", "series": "Celerio" },
    { "id": "suzuki-grand-vitara", "brandId": "suzuki", "name": "Grand Vitara", "slug": "grand-vitara", "series": "Vitara" },
    { "id": "suzuki-ignis-1", "brandId": "suzuki", "name": "Ignis I-II", "slug": "ignis-1", "series": "Ignis" },
    { "id": "suzuki-ignis-3", "brandId": "suzuki", "name": "Ignis III", "slug": "ignis-3", "series": "Ignis" },
    { "id": "suzuki-jimny", "brandId": "suzuki", "name": "Jimny", "slug": "jimny", "series": "Jimny" },
    { "id": "suzuki-liana", "brandId": "suzuki", "name": "Liana", "slug": "liana", "series": "Liana" },
    { "id": "suzuki-splash", "brandId": "suzuki", "name": "Splash", "slug": "splash", "series": "Splash" },
    { "id": "suzuki-swift-2", "brandId": "suzuki", "name": "Swift II", "slug": "swift-2", "series": "Swift", "keywords": ["1.0", "1.3", "Sedan", "GTI"] },
    { "id": "suzuki-swift-3", "brandId": "suzuki", "name": "Swift III", "slug": "swift-3", "series": "Swift", "keywords": ["1.3", "1.5", "1.3 DDIS", "Sport", "vRS"] },
    { "id": "suzuki-swift-4", "brandId": "suzuki", "name": "Swift IV", "slug": "swift-4", "series": "Swift", "keywords": ["1.2 VVT", "1.3 DDIS", "Sport"] },
    { "id": "suzuki-swift-5", "brandId": "suzuki", "name": "Swift V", "slug": "swift-5", "series": "Swift" },
    { "id": "suzuki-sx4", "brandId": "suzuki", "name": "SX4", "slug": "sx4", "series": "SX4" },
    { "id": "suzuki-sx4-scross", "brandId": "suzuki", "name": "SX4 S-Cross", "slug": "sx4-scross", "series": "S-Cross" },
    { "id": "suzuki-vitara-ly", "brandId": "suzuki", "name": "Vitara", "slug": "vitara", "series": "Vitara", "keywords": ["1.6", "1.4 Turbo", "Hybrid"] },
    { "id": "suzuki-kizashi", "brandId": "suzuki", "name": "Kizashi", "slug": "kizashi", "series": "Kizashi" },
    { "id": "suzuki-samurai", "brandId": "suzuki", "name": "Samurai", "slug": "samurai", "series": "Samurai" },
    { "id": "suzuki-wagon-r", "brandId": "suzuki", "name": "Wagon R+", "slug": "wagon-r", "series": "Wagon R" },
    { "id": "suzuki-across", "brandId": "suzuki", "name": "Across", "slug": "across", "series": "Across" },
    { "id": "suzuki-swace", "brandId": "suzuki", "name": "Swace", "slug": "swace", "series": "Swace" },
    { "id": "toyota-auris-1", "brandId": "toyota", "name": "Auris I", "slug": "auris-1", "series": "Auris" },
    { "id": "toyota-auris-2", "brandId": "toyota", "name": "Auris II", "slug": "auris-2", "series": "Auris" },
    { "id": "toyota-avensis-1", "brandId": "toyota", "name": "Avensis I", "slug": "avensis-1", "series": "Avensis", "keywords": ["1.6", "1.8", "2.0 TD"] },
    { "id": "toyota-avensis-2", "brandId": "toyota", "name": "Avensis II", "slug": "avensis-2", "series": "Avensis", "keywords": ["D4-D", "2.2 D-CAT", "1.8", "2.0", "1ZZ-FE", "1AZ-FSE", "1CD-FTV", "2AD-FHV"] },
    { "id": "toyota-avensis-3", "brandId": "toyota", "name": "Avensis III", "slug": "avensis-3", "series": "Avensis", "keywords": ["D4-D", "VALVEMATIC", "1AD-FTV", "2AD-FTV"] },
    { "id": "toyota-aygo-1", "brandId": "toyota", "name": "Aygo I", "slug": "aygo-1", "series": "Aygo" },
    { "id": "toyota-aygo-2", "brandId": "toyota", "name": "Aygo II", "slug": "aygo-2", "series": "Aygo" },
    { "id": "toyota-aygo-x", "brandId": "toyota", "name": "Aygo X", "slug": "aygo-x", "series": "Aygo" },
    { "id": "toyota-chr", "brandId": "toyota", "name": "C-HR", "slug": "chr", "series": "C-HR" },
    { "id": "toyota-corolla-9", "brandId": "toyota", "name": "Corolla IX", "slug": "corolla-9", "series": "Corolla", "keywords": ["1.4 VVTi", "1.6 VVTi", "2.0 D4-D", "TS", "T-Sport"] },
    { "id": "toyota-corolla-10", "brandId": "toyota", "name": "Corolla X", "slug": "corolla-10", "series": "Corolla", "keywords": ["1.33 Dual VVTi", "1.6 Valvematic", "1.4 D-4D", "2.0 D-4D"] },
    { "id": "toyota-corolla-11", "brandId": "toyota", "name": "Corolla XI", "slug": "corolla-11", "series": "Corolla", "keywords": ["1.6 Valvematic", "1.4 D-4D"] },
    { "id": "toyota-corolla-12", "brandId": "toyota", "name": "Corolla XII", "slug": "corolla-12", "series": "Corolla", "keywords": ["Hybrid", "1.8 Hybrid", "2.0 Hybrid", "GR Sport"] },
    { "id": "toyota-corolla-cross", "brandId": "toyota", "name": "Corolla Cross", "slug": "corolla-cross", "series": "Corolla" },
    { "id": "toyota-hilux-7", "brandId": "toyota", "name": "Hilux VII", "slug": "hilux-7", "series": "Hilux" },
    { "id": "toyota-hilux-8", "brandId": "toyota", "name": "Hilux VIII", "slug": "hilux-8", "series": "Hilux" },
    { "id": "toyota-land-cruiser-j120", "brandId": "toyota", "name": "Land Cruiser", "slug": "land-cruiser-j120", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j150", "brandId": "toyota", "name": "Land Cruiser", "slug": "land-cruiser-j150", "series": "Land Cruiser" },
    { "id": "toyota-prius-2", "brandId": "toyota", "name": "Prius II", "slug": "prius-2", "series": "Prius", "keywords": ["Hybrid", "1.5 HSD"] },
    { "id": "toyota-prius-3", "brandId": "toyota", "name": "Prius III", "slug": "prius-3", "series": "Prius", "keywords": ["Hybrid", "Plug-in", "1.8 HSD"] },
    { "id": "toyota-prius-4", "brandId": "toyota", "name": "Prius IV", "slug": "prius-4", "series": "Prius" },
    { "id": "toyota-rav4-2", "brandId": "toyota", "name": "RAV4 II", "slug": "rav4-2", "series": "RAV4" },
    { "id": "toyota-rav4-3", "brandId": "toyota", "name": "RAV4 III", "slug": "rav4-3", "series": "RAV4" },
    { "id": "toyota-rav4-4", "brandId": "toyota", "name": "RAV4 IV", "slug": "rav4-4", "series": "RAV4" },
    { "id": "toyota-rav4-5", "brandId": "toyota", "name": "RAV4 V", "slug": "rav4-5", "series": "RAV4" },
    { "id": "toyota-yaris-1", "brandId": "toyota", "name": "Yaris I", "slug": "yaris-1", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.3 VVT-i", "1.4 D-4D", "TS"] },
    { "id": "toyota-yaris-2", "brandId": "toyota", "name": "Yaris II", "slug": "yaris-2", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.33 Dual VVT-i", "1.4 D-4D"] },
    { "id": "toyota-yaris-3", "brandId": "toyota", "name": "Yaris III", "slug": "yaris-3", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.33 VVT-i", "1.5 HSD", "Hybrid", "1.4 D-4D"] },
    { "id": "toyota-yaris-4", "brandId": "toyota", "name": "Yaris IV", "slug": "yaris-4", "series": "Yaris", "keywords": ["1.5 Hybrid", "GR Yaris"] },
    { "id": "toyota-yaris-cross", "brandId": "toyota", "name": "Yaris Cross", "slug": "yaris-cross", "series": "Yaris", "keywords": ["Hybrid", "e-Four"] },
    { "id": "toyota-4runner", "brandId": "toyota", "name": "4-Runner", "slug": "4runner", "series": "4-Runner" },
    { "id": "toyota-avensis-verso", "brandId": "toyota", "name": "Avensis Verso", "slug": "avensis-verso", "series": "Avensis" },
    { "id": "toyota-carina", "brandId": "toyota", "name": "Carina", "slug": "carina", "series": "Carina" },
    { "id": "toyota-celica", "brandId": "toyota", "name": "Celica", "slug": "celica", "series": "Celica" },
    { "id": "toyota-gt86", "brandId": "toyota", "name": "GT86", "slug": "gt86", "series": "GT86" },
    { "id": "toyota-gr86", "brandId": "toyota", "name": "GR86", "slug": "gr86", "series": "GR86" },
    { "id": "toyota-hiace", "brandId": "toyota", "name": "Hiace", "slug": "hiace", "series": "Van" },
    { "id": "toyota-iq", "brandId": "toyota", "name": "iQ", "slug": "iq", "series": "iQ" },
    { "id": "toyota-mr2", "brandId": "toyota", "name": "MR2", "slug": "mr2", "series": "MR2" },
    { "id": "toyota-paseo", "brandId": "toyota", "name": "Paseo", "slug": "paseo", "series": "Paseo" },
    { "id": "toyota-picnic", "brandId": "toyota", "name": "Picnic", "slug": "picnic", "series": "Picnic" },
    { "id": "toyota-previa", "brandId": "toyota", "name": "Previa", "slug": "previa", "series": "Previa" },
    { "id": "toyota-prius-plus", "brandId": "toyota", "name": "Prius Plus", "slug": "prius-plus", "series": "Prius" },
    { "id": "toyota-proace", "brandId": "toyota", "name": "Proace", "slug": "proace", "series": "Van" },
    { "id": "toyota-starlet", "brandId": "toyota", "name": "Starlet", "slug": "starlet", "series": "Starlet" },
    { "id": "toyota-supra", "brandId": "toyota", "name": "Supra", "slug": "supra", "series": "Supra" },
    { "id": "toyota-urban-cruiser", "brandId": "toyota", "name": "Urban Cruiser", "slug": "urban-cruiser", "series": "Urban Cruiser" },
    { "id": "toyota-verso", "brandId": "toyota", "name": "Verso / Verso-S", "slug": "verso", "series": "Verso" },
    { "id": "toyota-bz4x", "brandId": "toyota", "name": "bZ4X", "slug": "bz4x", "series": "bZ4X" },
    { "id": "toyota-mirai", "brandId": "toyota", "name": "Mirai", "slug": "mirai", "series": "Mirai" },
];
