import { Model } from './types';

export const asianGroupModels: Model[] = [
    { "id": "daewoo-kalos", "brandId": "daewoo", "name": "Kalos", "slug": "kalos", "series": "Kalos" },
    { "id": "daewoo-lanos", "brandId": "daewoo", "name": "Lanos", "slug": "lanos", "series": "Lanos" },
    { "id": "daewoo-matiz", "brandId": "daewoo", "name": "Matiz", "slug": "matiz", "series": "Matiz" },
    { "id": "daewoo-nexia", "brandId": "daewoo", "name": "Nexia", "slug": "nexia", "series": "Nexia" },
    { "id": "daewoo-nubira", "brandId": "daewoo", "name": "Nubira", "slug": "nubira", "series": "Nubira" },
    { "id": "daewoo-musso", "brandId": "daewoo", "name": "Musso", "slug": "musso", "series": "Musso" },
    { "id": "daewoo-korando", "brandId": "daewoo", "name": "Korando", "slug": "korando", "series": "Korando" },
    { "id": "daewoo-evanda", "brandId": "daewoo", "name": "Evanda", "slug": "evanda", "series": "Evanda" },
    { "id": "daewoo-espero", "brandId": "daewoo", "name": "Espero", "slug": "espero", "series": "Espero" },
    { "id": "daewoo-leganza", "brandId": "daewoo", "name": "Leganza", "slug": "leganza", "series": "Leganza" },
    { "id": "daewoo-tacuma", "brandId": "daewoo", "name": "Tacuma", "slug": "tacuma", "series": "Tacuma" },
    { "id": "daewoo-tico", "brandId": "daewoo", "name": "Tico", "slug": "tico", "series": "Tico" },
    { "id": "honda-accord-1", "brandId": "honda", "name": "Accord I (Mk1)", "slug": "accord-1", "series": "Accord" },
    { "id": "honda-accord-2", "brandId": "honda", "name": "Accord II (Mk2)", "slug": "accord-2", "series": "Accord" },
    { "id": "honda-accord-3", "brandId": "honda", "name": "Accord III (Mk3)", "slug": "accord-3", "series": "Accord" },
    { "id": "honda-accord-4", "brandId": "honda", "name": "Accord IV (Mk4)", "slug": "accord-4", "series": "Accord" },
    { "id": "honda-accord-5", "brandId": "honda", "name": "Accord V (Mk5)", "slug": "accord-5", "series": "Accord" },
    { "id": "honda-accord-6", "brandId": "honda", "name": "Accord VI (Mk6)", "slug": "accord-6", "series": "Accord", "keywords": ["VTEC", "2.0 TD", "Type-R"] },
    { "id": "honda-accord-7", "brandId": "honda", "name": "Accord VII (Mk7)", "slug": "accord-7", "series": "Accord", "keywords": ["2.0 i-VTEC", "2.4 i-VTEC", "2.2 i-CTDI", "Type-S"] },
    { "id": "honda-accord-8", "brandId": "honda", "name": "Accord VIII (Mk8)", "slug": "accord-8", "series": "Accord", "keywords": ["2.0 i-VTEC", "2.4 i-VTEC", "2.2 i-DTEC", "Type-S"] },
    { "id": "honda-accord-9", "brandId": "honda", "name": "Accord IX (Mk9)", "slug": "accord-9", "series": "Accord" },
    { "id": "honda-accord-10", "brandId": "honda", "name": "Accord X (Mk10)", "slug": "accord-10", "series": "Accord" },
    { "id": "honda-city", "brandId": "honda", "name": "City", "slug": "city", "series": "City" },
    { "id": "honda-civic-1", "brandId": "honda", "name": "Civic I (Mk1)", "slug": "civic-1", "series": "Civic" },
    { "id": "honda-civic-2", "brandId": "honda", "name": "Civic II (Mk2)", "slug": "civic-2", "series": "Civic" },
    { "id": "honda-civic-3", "brandId": "honda", "name": "Civic III (Mk3)", "slug": "civic-3", "series": "Civic" },
    { "id": "honda-civic-4", "brandId": "honda", "name": "Civic IV (Mk4)", "slug": "civic-4", "series": "Civic" },
    { "id": "honda-civic-5", "brandId": "honda", "name": "Civic V (Mk5)", "slug": "civic-5", "series": "Civic" },
    { "id": "honda-civic-6", "brandId": "honda", "name": "Civic VI (Mk6)", "slug": "civic-6", "series": "Civic", "keywords": ["VTI", "Type-R", "1.4", "1.5", "1.6"] },
    { "id": "honda-civic-7", "brandId": "honda", "name": "Civic VII (Mk7)", "slug": "civic-7", "series": "Civic", "keywords": ["Type-R", "1.7 CTDI", "1.4", "1.6"] },
    { "id": "honda-civic-8", "brandId": "honda", "name": "Civic VIII (Mk8 / UFO)", "slug": "civic-8", "series": "Civic", "keywords": ["Type-R", "UFO", "ufo civic", "1.8 i-VTEC", "2.2 CTDI", "R18A", "N22A", "K20A"] },
    { "id": "honda-civic-9", "brandId": "honda", "name": "Civic IX (Mk9)", "slug": "civic-9", "series": "Civic", "keywords": ["Type-R", "1.6 i-DTEC", "1.8 i-VTEC", "N16A", "R18Z"] },
    { "id": "honda-civic-10", "brandId": "honda", "name": "Civic X (Mk10)", "slug": "civic-10", "series": "Civic" },
    { "id": "honda-civic-11", "brandId": "honda", "name": "Civic XI (Mk11)", "slug": "civic-11", "series": "Civic" },
    { "id": "honda-concerto", "brandId": "honda", "name": "Concerto", "slug": "concerto", "series": "Concerto" },
    { "id": "honda-crv-1", "brandId": "honda", "name": "CR-V I (Mk1)", "slug": "crv-1", "series": "CR-V" },
    { "id": "honda-crv-2", "brandId": "honda", "name": "CR-V II (Mk2)", "slug": "crv-2", "series": "CR-V" },
    { "id": "honda-crv-3", "brandId": "honda", "name": "CR-V III (Mk3)", "slug": "crv-3", "series": "CR-V" },
    { "id": "honda-crv-4", "brandId": "honda", "name": "CR-V IV (Mk4)", "slug": "crv-4", "series": "CR-V" },
    { "id": "honda-crv-5", "brandId": "honda", "name": "CR-V V (Mk5)", "slug": "crv-5", "series": "CR-V" },
    { "id": "honda-crx", "brandId": "honda", "name": "CRX", "slug": "crx", "series": "CRX" },
    { "id": "honda-crz", "brandId": "honda", "name": "CR-Z", "slug": "crz", "series": "CR-Z" },
    { "id": "honda-e", "brandId": "honda", "name": "e", "slug": "e", "series": "e" },
    { "id": "honda-element", "brandId": "honda", "name": "Element", "slug": "element", "series": "Element" },
    { "id": "honda-frv", "brandId": "honda", "name": "FR-V", "slug": "frv", "series": "FR-V" },
    { "id": "honda-hrv-1", "brandId": "honda", "name": "HR-V I (Mk1)", "slug": "hrv-1", "series": "HR-V" },
    { "id": "honda-hrv-2", "brandId": "honda", "name": "HR-V II (Mk2)", "slug": "hrv-2", "series": "HR-V" },
    { "id": "honda-hrv-3", "brandId": "honda", "name": "HR-V III (Mk3)", "slug": "hrv-3", "series": "HR-V" },
    { "id": "honda-insight", "brandId": "honda", "name": "Insight", "slug": "insight", "series": "Insight" },
    { "id": "honda-integra", "brandId": "honda", "name": "Integra", "slug": "integra", "series": "Integra" },
    { "id": "honda-jazz-1", "brandId": "honda", "name": "Jazz I (Mk1)", "slug": "jazz-1", "series": "Jazz" },
    { "id": "honda-jazz-2", "brandId": "honda", "name": "Jazz II (Mk2)", "slug": "jazz-2", "series": "Jazz" },
    { "id": "honda-jazz-3", "brandId": "honda", "name": "Jazz III (Mk3)", "slug": "jazz-3", "series": "Jazz" },
    { "id": "honda-jazz-4", "brandId": "honda", "name": "Jazz IV (Mk4)", "slug": "jazz-4", "series": "Jazz" },
    { "id": "honda-legend", "brandId": "honda", "name": "Legend", "slug": "legend", "series": "Legend" },
    { "id": "honda-logo", "brandId": "honda", "name": "Logo", "slug": "logo", "series": "Logo" },
    { "id": "honda-nsx", "brandId": "honda", "name": "NSX", "slug": "nsx", "series": "NSX" },
    { "id": "honda-odyssey", "brandId": "honda", "name": "Odyssey", "slug": "odyssey", "series": "Odyssey" },
    { "id": "honda-prelude", "brandId": "honda", "name": "Prelude", "slug": "prelude", "series": "Prelude" },
    { "id": "honda-s2000", "brandId": "honda", "name": "S2000", "slug": "s2000", "series": "S2000" },
    { "id": "honda-shuttle", "brandId": "honda", "name": "Shuttle", "slug": "shuttle", "series": "Shuttle" },
    { "id": "honda-stream", "brandId": "honda", "name": "Stream", "slug": "stream", "series": "Stream" },
    { "id": "honda-zrv", "brandId": "honda", "name": "ZR-V", "slug": "zr-v", "series": "ZR-V" },
    { "id": "hyundai-accent", "brandId": "hyundai", "name": "Accent", "slug": "accent", "series": "Accent" },
    { "id": "hyundai-atos", "brandId": "hyundai", "name": "Atos", "slug": "atos", "series": "Atos" },
    { "id": "hyundai-bayon", "brandId": "hyundai", "name": "Bayon", "slug": "bayon", "series": "Bayon" },
    { "id": "hyundai-coupe", "brandId": "hyundai", "name": "Coupe", "slug": "coupe", "series": "Coupe" },
    { "id": "hyundai-elantra", "brandId": "hyundai", "name": "Elantra", "slug": "elantra", "series": "Elantra" },
    { "id": "hyundai-galloper", "brandId": "hyundai", "name": "Galloper", "slug": "galloper", "series": "Galloper" },
    { "id": "hyundai-genesis", "brandId": "hyundai", "name": "Genesis", "slug": "genesis", "series": "Genesis" },
    { "id": "hyundai-getz", "brandId": "hyundai", "name": "Getz", "slug": "getz", "series": "Getz" },
    { "id": "hyundai-grandeur", "brandId": "hyundai", "name": "Grandeur", "slug": "grandeur", "series": "Grandeur" },
    { "id": "hyundai-h1", "brandId": "hyundai", "name": "H-1 / Starex", "slug": "h1", "series": "H-1" },
    { "id": "hyundai-h100", "brandId": "hyundai", "name": "H-100", "slug": "h100", "series": "Van" },
    { "id": "hyundai-h200", "brandId": "hyundai", "name": "H-200", "slug": "h200", "series": "Van" },
    { "id": "hyundai-h350", "brandId": "hyundai", "name": "H-350", "slug": "h350", "series": "Van" },
    { "id": "hyundai-hd", "brandId": "hyundai", "name": "HD", "slug": "hd", "series": "Truck" },
    { "id": "hyundai-i10-1", "brandId": "hyundai", "name": "i10 I (Mk1)", "slug": "i10-1", "series": "i10", "keywords": ["1.1", "1.2"] },
    { "id": "hyundai-i10-2", "brandId": "hyundai", "name": "i10 II (Mk2)", "slug": "i10-2", "series": "i10" },
    { "id": "hyundai-i10-3", "brandId": "hyundai", "name": "i10 III (Mk3)", "slug": "i10-3", "series": "i10" },
    { "id": "hyundai-i20-1", "brandId": "hyundai", "name": "i20 I (Mk1)", "slug": "i20-1", "series": "i20", "keywords": ["1.2", "1.4 CRDI"] },
    { "id": "hyundai-i20-2", "brandId": "hyundai", "name": "i20 II (Mk2)", "slug": "i20-2", "series": "i20" },
    { "id": "hyundai-i20-3", "brandId": "hyundai", "name": "i20 III (Mk3)", "slug": "i20-3", "series": "i20" },
    { "id": "hyundai-i30-1", "brandId": "hyundai", "name": "i30 I (Mk1)", "slug": "i30-1", "series": "i30", "keywords": ["CW", "1.4", "1.6 CRDI", "G4FA", "D4FB"] },
    { "id": "hyundai-i30-2", "brandId": "hyundai", "name": "i30 II (Mk2)", "slug": "i30-2", "series": "i30", "keywords": ["CW", "Coupe", "1.6 CRDI", "D4FB"] },
    { "id": "hyundai-i30-3", "brandId": "hyundai", "name": "i30 III (Mk3)", "slug": "i30-3", "series": "i30", "keywords": ["N", "Fastback", "CW", "1.4 T-GDI", "1.6 CRDI", "G4LD", "D4FE"] },
    { "id": "hyundai-i40", "brandId": "hyundai", "name": "i40", "slug": "i40", "series": "i40" },
    { "id": "hyundai-inster", "brandId": "hyundai", "name": "Inster", "slug": "inster", "series": "Inster" },
    { "id": "hyundai-ioniq", "brandId": "hyundai", "name": "Ioniq", "slug": "ioniq", "series": "Ioniq" },
    { "id": "hyundai-ioniq5", "brandId": "hyundai", "name": "Ioniq 5", "slug": "ioniq5", "series": "Ioniq 5" },
    { "id": "hyundai-ioniq6", "brandId": "hyundai", "name": "Ioniq 6", "slug": "ioniq6", "series": "Ioniq 6" },
    { "id": "hyundai-ix20", "brandId": "hyundai", "name": "ix20", "slug": "ix20", "series": "ix20" },
    { "id": "hyundai-ix35", "brandId": "hyundai", "name": "ix35", "slug": "ix35", "series": "ix35", "keywords": ["1.7 CRDI", "2.0 CRDI"] },
    { "id": "hyundai-ix55", "brandId": "hyundai", "name": "ix55", "slug": "ix55", "series": "ix55" },
    { "id": "hyundai-kona-1", "brandId": "hyundai", "name": "Kona I (Mk1)", "slug": "kona-1", "series": "Kona" },
    { "id": "hyundai-kona-2", "brandId": "hyundai", "name": "Kona II (Mk2)", "slug": "kona-2", "series": "Kona", "keywords": ["SX2"] },
    { "id": "hyundai-lantra", "brandId": "hyundai", "name": "Lantra", "slug": "lantra", "series": "Lantra" },
    { "id": "hyundai-matrix", "brandId": "hyundai", "name": "Matrix", "slug": "matrix", "series": "Matrix" },
    { "id": "hyundai-pony", "brandId": "hyundai", "name": "Pony", "slug": "pony", "series": "Pony" },
    { "id": "hyundai-porter", "brandId": "hyundai", "name": "Porter", "slug": "porter", "series": "Van" },
    { "id": "hyundai-scoupe", "brandId": "hyundai", "name": "S Coupe", "slug": "scoupe", "series": "Coupe" },
    { "id": "hyundai-santa-fe-1", "brandId": "hyundai", "name": "Santa Fe I (Mk1)", "slug": "santa-fe-1", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-2", "brandId": "hyundai", "name": "Santa Fe II (Mk2)", "slug": "santa-fe-2", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-3", "brandId": "hyundai", "name": "Santa Fe III (Mk3)", "slug": "santa-fe-3", "series": "Santa Fe" },
    { "id": "hyundai-santa-fe-4", "brandId": "hyundai", "name": "Santa Fe IV (Mk4)", "slug": "santa-fe-4", "series": "Santa Fe" },
    { "id": "hyundai-santamo", "brandId": "hyundai", "name": "Santamo", "slug": "santamo", "series": "Santamo" },
    { "id": "hyundai-sonata", "brandId": "hyundai", "name": "Sonata", "slug": "sonata", "series": "Sonata" },
    { "id": "hyundai-starex", "brandId": "hyundai", "name": "Starex", "slug": "starex", "series": "Starex" },
    { "id": "hyundai-staria", "brandId": "hyundai", "name": "Staria", "slug": "staria", "series": "Staria" },
    { "id": "hyundai-terracan", "brandId": "hyundai", "name": "Terracan", "slug": "terracan", "series": "Terracan" },
    { "id": "hyundai-trajet", "brandId": "hyundai", "name": "Trajet", "slug": "trajet", "series": "Trajet" },
    { "id": "hyundai-tucson-1", "brandId": "hyundai", "name": "Tucson I (Mk1)", "slug": "tucson-1", "series": "Tucson", "keywords": ["2.0 CRDI"] },
    { "id": "hyundai-tucson-2", "brandId": "hyundai", "name": "Tucson II (Mk2)", "slug": "tucson-2", "series": "Tucson" },
    { "id": "hyundai-tucson-3", "brandId": "hyundai", "name": "Tucson III (Mk3)", "slug": "tucson-3", "series": "Tucson", "keywords": ["1.6 CRDI", "1.7 CRDI", "1.6 T-GDI"] },
    { "id": "hyundai-tucson-4", "brandId": "hyundai", "name": "Tucson IV (Mk4)", "slug": "tucson-4", "series": "Tucson" },
    { "id": "hyundai-veloster", "brandId": "hyundai", "name": "Veloster", "slug": "veloster", "series": "Veloster" },
    { "id": "hyundai-xg", "brandId": "hyundai", "name": "XG", "slug": "xg", "series": "XG" },
    { "id": "infiniti-fx", "brandId": "infiniti", "name": "FX / QX70", "slug": "fx", "series": "FX" },
    { "id": "infiniti-ex", "brandId": "infiniti", "name": "EX / QX50", "slug": "ex", "series": "EX" },
    { "id": "infiniti-g", "brandId": "infiniti", "name": "G / Q40", "slug": "g", "series": "G" },
    { "id": "infiniti-m", "brandId": "infiniti", "name": "M / Q70", "slug": "m", "series": "M" },
    { "id": "infiniti-q30", "brandId": "infiniti", "name": "Q30", "slug": "q30", "series": "Q30" },
    { "id": "infiniti-q60", "brandId": "infiniti", "name": "Q60", "slug": "q60", "series": "Q60" },
    { "id": "infiniti-qx30", "brandId": "infiniti", "name": "QX30", "slug": "qx30", "series": "QX30" },
    { "id": "infiniti-q50", "brandId": "infiniti", "name": "Q50", "slug": "q50", "series": "Q50" },
    { "id": "isuzu-dmax", "brandId": "isuzu", "name": "D-Max", "slug": "d-max", "series": "D-Max" },
    { "id": "isuzu-trooper", "brandId": "isuzu", "name": "Trooper", "slug": "trooper", "series": "Trooper" },
    { "id": "kia-besta", "brandId": "kia", "name": "Besta", "slug": "besta", "series": "Van" },
    { "id": "kia-carens-1", "brandId": "kia", "name": "Carens I (Mk1)", "slug": "carens-1", "series": "Carens" },
    { "id": "kia-carens-2", "brandId": "kia", "name": "Carens II (Mk2)", "slug": "carens-2", "series": "Carens" },
    { "id": "kia-carens-3", "brandId": "kia", "name": "Carens III (Mk3)", "slug": "carens-3", "series": "Carens" },
    { "id": "kia-carens-4", "brandId": "kia", "name": "Carens IV (Mk4)", "slug": "carens-4", "series": "Carens" },
    { "id": "kia-carnival", "brandId": "kia", "name": "Carnival", "slug": "carnival", "series": "Carnival" },
    { "id": "kia-ceed-1", "brandId": "kia", "name": "Cee'd I (Mk1)", "slug": "ceed-1", "series": "Cee'd", "keywords": ["SW", "pro_ceed", "1.4", "1.6 CRDI"] },
    { "id": "kia-ceed-2", "brandId": "kia", "name": "Cee'd II (Mk2)", "slug": "ceed-2", "series": "Cee'd", "keywords": ["SW", "pro_ceed", "GT", "1.6 CRDI", "1.4 GDI"] },
    { "id": "kia-ceed-3", "brandId": "kia", "name": "Ceed III (Mk3)", "slug": "ceed-3", "series": "Ceed", "keywords": ["SW", "GT", "Proceed", "Xceed"] },
    { "id": "kia-pro", "brandId": "kia", "name": "Pro", "slug": "pro", "series": "Ceed" },
    { "id": "kia-proceed", "brandId": "kia", "name": "ProCeed", "slug": "proceed", "series": "Ceed" },
    { "id": "kia-cerato", "brandId": "kia", "name": "Cerato", "slug": "cerato", "series": "Cerato" },
    { "id": "kia-clarus", "brandId": "kia", "name": "Clarus", "slug": "clarus", "series": "Clarus" },
    { "id": "kia-ev3", "brandId": "kia", "name": "EV3", "slug": "ev3", "series": "EV" },
    { "id": "kia-ev6", "brandId": "kia", "name": "EV6", "slug": "ev6", "series": "EV" },
    { "id": "kia-ev9", "brandId": "kia", "name": "EV9", "slug": "ev9", "series": "EV" },
    { "id": "kia-joice", "brandId": "kia", "name": "Joice", "slug": "joice", "series": "Joice" },
    { "id": "kia-k2500", "brandId": "kia", "name": "K2500", "slug": "k2500", "series": "Van" },
    { "id": "kia-k2700", "brandId": "kia", "name": "K2700", "slug": "k2700", "series": "Van" },
    { "id": "kia-magentis", "brandId": "kia", "name": "Magentis", "slug": "magentis", "series": "Magentis" },
    { "id": "kia-niro-1", "brandId": "kia", "name": "Niro I (Mk1)", "slug": "niro-1", "series": "Niro" },
    { "id": "kia-niro-2", "brandId": "kia", "name": "Niro II (Mk2)", "slug": "niro-2", "series": "Niro" },
    { "id": "kia-optima-1", "brandId": "kia", "name": "Optima I (Mk1)", "slug": "optima-1", "series": "Optima" },
    { "id": "kia-optima-2", "brandId": "kia", "name": "Optima II (Mk2)", "slug": "optima-2", "series": "Optima" },
    { "id": "kia-optima-3", "brandId": "kia", "name": "Optima III (Mk3)", "slug": "optima-3", "series": "Optima" },
    { "id": "kia-optima-4", "brandId": "kia", "name": "Optima IV (Mk4)", "slug": "optima-4", "series": "Optima" },
    { "id": "kia-picanto-1", "brandId": "kia", "name": "Picanto I (Mk1)", "slug": "picanto-1", "series": "Picanto" },
    { "id": "kia-picanto-2", "brandId": "kia", "name": "Picanto II (Mk2)", "slug": "picanto-2", "series": "Picanto" },
    { "id": "kia-picanto-3", "brandId": "kia", "name": "Picanto III (Mk3)", "slug": "picanto-3", "series": "Picanto" },
    { "id": "kia-pregio", "brandId": "kia", "name": "Pregio", "slug": "pregio", "series": "Van" },
    { "id": "kia-pride", "brandId": "kia", "name": "Pride", "slug": "pride", "series": "Pride" },
    { "id": "kia-rio-1", "brandId": "kia", "name": "Rio I (Mk1)", "slug": "rio-1", "series": "Rio" },
    { "id": "kia-rio-2", "brandId": "kia", "name": "Rio II (Mk2)", "slug": "rio-2", "series": "Rio", "keywords": ["1.4", "1.5 CRDI"] },
    { "id": "kia-rio-3", "brandId": "kia", "name": "Rio III (Mk3)", "slug": "rio-3", "series": "Rio", "keywords": ["1.1 CRDI", "1.2", "1.4 CRDI"] },
    { "id": "kia-rio-4", "brandId": "kia", "name": "Rio IV (Mk4)", "slug": "rio-4", "series": "Rio", "keywords": ["1.0 T-GDI", "1.2", "1.4"] },
    { "id": "kia-sephia", "brandId": "kia", "name": "Sephia", "slug": "sephia", "series": "Sephia" },
    { "id": "kia-shuma", "brandId": "kia", "name": "Shuma", "slug": "shuma", "series": "Shuma" },
    { "id": "kia-sorento-1", "brandId": "kia", "name": "Sorento I (Mk1)", "slug": "sorento-1", "series": "Sorento" },
    { "id": "kia-sorento-2", "brandId": "kia", "name": "Sorento II (Mk2)", "slug": "sorento-2", "series": "Sorento" },
    { "id": "kia-sorento-3", "brandId": "kia", "name": "Sorento III (Mk3)", "slug": "sorento-3", "series": "Sorento" },
    { "id": "kia-sorento-4", "brandId": "kia", "name": "Sorento IV (Mk4)", "slug": "sorento-4", "series": "Sorento" },
    { "id": "kia-soul", "brandId": "kia", "name": "Soul", "slug": "soul", "series": "Soul" },
    { "id": "kia-sportage-1", "brandId": "kia", "name": "Sportage I (Mk1)", "slug": "sportage-1", "series": "Sportage" },
    { "id": "kia-sportage-2", "brandId": "kia", "name": "Sportage II (Mk2)", "slug": "sportage-2", "series": "Sportage", "keywords": ["2.0 CRDI", "2.7 V6"] },
    { "id": "kia-sportage-3", "brandId": "kia", "name": "Sportage III (Mk3)", "slug": "sportage-3", "series": "Sportage", "keywords": ["1.6 GDI", "1.7 CRDI", "2.0 CRDI"] },
    { "id": "kia-sportage-4", "brandId": "kia", "name": "Sportage IV (Mk4)", "slug": "sportage-4", "series": "Sportage", "keywords": ["1.6 GDI", "1.6 T-GDI", "1.7 CRDI", "2.0 CRDI"] },
    { "id": "kia-sportage-5", "brandId": "kia", "name": "Sportage V (Mk5)", "slug": "sportage-5", "series": "Sportage", "keywords": ["1.6 T-GDI", "1.6 CRDI", "Hybrid", "PHEV"] },
    { "id": "kia-stinger", "brandId": "kia", "name": "Stinger", "slug": "stinger", "series": "Stinger" },
    { "id": "kia-stonic", "brandId": "kia", "name": "Stonic", "slug": "stonic", "series": "Stonic" },
    { "id": "kia-venga", "brandId": "kia", "name": "Venga", "slug": "venga", "series": "Venga" },
    { "id": "kia-xceed", "brandId": "kia", "name": "XCeed", "slug": "xceed", "series": "XCeed" },
    { "id": "lexus-ct", "brandId": "lexus", "name": "CT 200h (ZWA10)", "slug": "ct", "series": "CT" },
    { "id": "lexus-es", "brandId": "lexus", "name": "ES", "slug": "es", "series": "ES" },
    { "id": "lexus-gs", "brandId": "lexus", "name": "GS", "slug": "gs", "series": "GS" },
    { "id": "lexus-ls", "brandId": "lexus", "name": "LS", "slug": "ls", "series": "LS" },
    { "id": "lexus-rc", "brandId": "lexus", "name": "RC", "slug": "rc", "series": "RC" },
    { "id": "lexus-sc", "brandId": "lexus", "name": "SC", "slug": "sc", "series": "SC" },
    { "id": "lexus-ux", "brandId": "lexus", "name": "UX", "slug": "ux", "series": "UX" },
    { "id": "lexus-lbx", "brandId": "lexus", "name": "LBX", "slug": "lbx", "series": "LBX" },
    { "id": "lexus-rz", "brandId": "lexus", "name": "RZ", "slug": "rz", "series": "RZ" },
    { "id": "lexus-is-1", "brandId": "lexus", "name": "IS (XE10)", "slug": "is-1", "series": "IS" },
    { "id": "lexus-is-2", "brandId": "lexus", "name": "IS (XE20)", "slug": "is-2", "series": "IS" },
    { "id": "lexus-is-3", "brandId": "lexus", "name": "IS (XE30)", "slug": "is-3", "series": "IS" },
    { "id": "lexus-nx", "brandId": "lexus", "name": "NX", "slug": "nx", "series": "NX" },
    { "id": "lexus-rx-2", "brandId": "lexus", "name": "RX (XU30)", "slug": "rx-2", "series": "RX" },
    { "id": "lexus-rx-3", "brandId": "lexus", "name": "RX (AL10)", "slug": "rx-3", "series": "RX" },
    { "id": "lexus-rx-4", "brandId": "lexus", "name": "RX (AL20)", "slug": "rx-4", "series": "RX" },
    { "id": "mazda-121", "brandId": "mazda", "name": "121", "slug": "121", "series": "121" },
    { "id": "mazda-323", "brandId": "mazda", "name": "323", "slug": "323", "series": "323" },
    { "id": "mazda-626", "brandId": "mazda", "name": "626", "slug": "626", "series": "626" },
    { "id": "mazda-929", "brandId": "mazda", "name": "929", "slug": "929", "series": "929" },
    { "id": "mazda-2-1", "brandId": "mazda", "name": "2 I (Mk1 / DY)", "slug": "mazda-2-dy", "series": "2", "keywords": ["1.25", "1.4", "1.6", "1.4 CD"] },
    { "id": "mazda-2-2", "brandId": "mazda", "name": "2 II (Mk2 / DE)", "slug": "mazda-2-de", "series": "2", "keywords": ["1.3", "1.5", "1.6 MZ-CD"] },
    { "id": "mazda-2-3", "brandId": "mazda", "name": "2 III (Mk3 / DJ)", "slug": "mazda-2-dj", "series": "2", "keywords": ["SkyActiv-G", "SkyActiv-D"] },
    { "id": "mazda-3-1", "brandId": "mazda", "name": "3 I (Mk1 / BK)", "slug": "mazda-3-bk", "series": "3", "keywords": ["MPS", "1.6", "2.0"] },
    { "id": "mazda-3-2", "brandId": "mazda", "name": "3 II (Mk2 / BL)", "slug": "mazda-3-bl", "series": "3", "keywords": ["MPS", "1.6 MZ-CD"] },
    { "id": "mazda-3-3", "brandId": "mazda", "name": "3 III (Mk3 / BM/BN)", "slug": "mazda-3-bm", "series": "3", "keywords": ["SkyActiv"] },
    { "id": "mazda-3-4", "brandId": "mazda", "name": "3 IV (Mk4 / BP)", "slug": "mazda-3-bp", "series": "3", "keywords": ["SkyActiv-X"] },
    { "id": "mazda-5-1", "brandId": "mazda", "name": "5 I (Mk1 / CR)", "slug": "mazda-5-cr", "series": "5" },
    { "id": "mazda-5-2", "brandId": "mazda", "name": "5 II (Mk2 / CW)", "slug": "mazda-5-cw", "series": "5" },
    { "id": "mazda-6-1", "brandId": "mazda", "name": "6 I (Mk1 / GG/GY)", "slug": "mazda-6-gg", "series": "6", "keywords": ["MPS", "2.0 CD"] },
    { "id": "mazda-6-2", "brandId": "mazda", "name": "6 II (Mk2 / GH)", "slug": "mazda-6-gh", "series": "6", "keywords": ["2.2 CD", "2.0 CD"] },
    { "id": "mazda-6-3", "brandId": "mazda", "name": "6 III (Mk3 / GJ/GL)", "slug": "mazda-6-gj", "series": "6", "keywords": ["SkyActiv"] },
    { "id": "mazda-cx3", "brandId": "mazda", "name": "CX-3", "slug": "cx-3", "series": "CX-3" },
    { "id": "mazda-cx30", "brandId": "mazda", "name": "CX-30", "slug": "cx-30", "series": "CX-30" },
    { "id": "mazda-cx5-1", "brandId": "mazda", "name": "CX-5 I (Mk1 / KE)", "slug": "cx-5-ke", "series": "CX-5" },
    { "id": "mazda-cx5-2", "brandId": "mazda", "name": "CX-5 II (Mk2 / KF)", "slug": "cx-5-kf", "series": "CX-5" },
    { "id": "mazda-cx7", "brandId": "mazda", "name": "CX-7", "slug": "cx-7", "series": "CX-7" },
    { "id": "mazda-cx9", "brandId": "mazda", "name": "CX-9", "slug": "cx-9", "series": "CX-9" },
    { "id": "mazda-cx60", "brandId": "mazda", "name": "CX-60", "slug": "cx-60", "series": "CX-60" },
    { "id": "mazda-cx80", "brandId": "mazda", "name": "CX-80", "slug": "cx-80", "series": "CX-80" },
    { "id": "mazda-demio", "brandId": "mazda", "name": "Demio", "slug": "demio", "series": "Demio" },
    { "id": "mazda-eserie", "brandId": "mazda", "name": "E-Serie", "slug": "e-serie", "series": "Van" },
    { "id": "mazda-mpv", "brandId": "mazda", "name": "MPV", "slug": "mpv", "series": "MPV" },
    { "id": "mazda-mx3", "brandId": "mazda", "name": "MX-3", "slug": "mx3", "series": "MX-3" },
    { "id": "mazda-mx30", "brandId": "mazda", "name": "MX-30", "slug": "mx-30", "series": "MX-30" },
    { "id": "mazda-mx5-1", "brandId": "mazda", "name": "MX-5 I (Mk1 / NA)", "slug": "mx5-na", "series": "MX-5" },
    { "id": "mazda-mx5-2", "brandId": "mazda", "name": "MX-5 II (Mk2 / NB)", "slug": "mx5-nb", "series": "MX-5" },
    { "id": "mazda-mx5-3", "brandId": "mazda", "name": "MX-5 III (Mk3 / NC)", "slug": "mx5-nc", "series": "MX-5" },
    { "id": "mazda-mx5-4", "brandId": "mazda", "name": "MX-5 IV (Mk4 / ND)", "slug": "mx5-nd", "series": "MX-5" },
    { "id": "mazda-mx6", "brandId": "mazda", "name": "MX-6", "slug": "mx-6", "series": "MX-6" },
    { "id": "mazda-premacy", "brandId": "mazda", "name": "Premacy", "slug": "premacy", "series": "Premacy" },
    { "id": "mazda-rx7", "brandId": "mazda", "name": "RX-7", "slug": "rx7", "series": "RX-7" },
    { "id": "mazda-rx8", "brandId": "mazda", "name": "RX-8", "slug": "rx8", "series": "RX-8" },
    { "id": "mazda-tribute", "brandId": "mazda", "name": "Tribute", "slug": "tribute", "series": "Tribute" },
    { "id": "mazda-xedos-6", "brandId": "mazda", "name": "Xedos 6", "slug": "xedos-6", "series": "Xedos" },
    { "id": "mazda-xedos-9", "brandId": "mazda", "name": "Xedos 9", "slug": "xedos-9", "series": "Xedos" },
    { "id": "mazda-bseries", "brandId": "mazda", "name": "B-Series", "slug": "b-series", "series": "Pickup" },
    { "id": "mazda-bt50", "brandId": "mazda", "name": "BT-50", "slug": "bt-50", "series": "Pickup" },
    { "id": "mitsubishi-asx", "brandId": "mitsubishi", "name": "ASX", "slug": "asx", "series": "ASX" },
    { "id": "mitsubishi-colt", "brandId": "mitsubishi", "name": "Colt", "slug": "colt", "series": "Colt" },
    { "id": "mitsubishi-eclipse-cross", "brandId": "mitsubishi", "name": "Eclipse Cross", "slug": "eclipse-cross", "series": "Eclipse" },
    { "id": "mitsubishi-eclipse", "brandId": "mitsubishi", "name": "Eclipse", "slug": "eclipse", "series": "Eclipse" },
    { "id": "mitsubishi-carisma", "brandId": "mitsubishi", "name": "Carisma", "slug": "carisma", "series": "Carisma" },
    { "id": "mitsubishi-galant", "brandId": "mitsubishi", "name": "Galant", "slug": "galant", "series": "Galant" },
    { "id": "mitsubishi-grandis", "brandId": "mitsubishi", "name": "Grandis", "slug": "grandis", "series": "Grandis" },
    { "id": "mitsubishi-mirage", "brandId": "mitsubishi", "name": "Mirage", "slug": "mirage", "series": "Mirage" },
    { "id": "mitsubishi-pajero-pinin", "brandId": "mitsubishi", "name": "Pinin", "slug": "pajero-pinin", "series": "Pajero" },
    { "id": "mitsubishi-pajero-sport", "brandId": "mitsubishi", "name": "Sport", "slug": "pajero-sport", "series": "Pajero" },
    { "id": "mitsubishi-space-wagon", "brandId": "mitsubishi", "name": "Space Wagon", "slug": "space-wagon", "series": "Space Wagon" },
    { "id": "mitsubishi-imiev", "brandId": "mitsubishi", "name": "i-MiEV", "slug": "imiev", "series": "i-MiEV" },
    { "id": "mitsubishi-l200-4", "brandId": "mitsubishi", "name": "L200 (Mk4)", "slug": "l200-4", "series": "L200" },
    { "id": "mitsubishi-l200-5", "brandId": "mitsubishi", "name": "L200 (Mk5)", "slug": "l200-5", "series": "L200" },
    { "id": "mitsubishi-lancer", "brandId": "mitsubishi", "name": "Lancer", "slug": "lancer", "series": "Lancer", "keywords": ["EVO", "Evolution", "1.5", "1.8", "2.0 DI-D"] },
    { "id": "mitsubishi-outlander-1", "brandId": "mitsubishi", "name": "Outlander (CU)", "slug": "outlander-1", "series": "Outlander", "keywords": ["2.0 Turbo", "4WD"] },
    { "id": "mitsubishi-outlander-2", "brandId": "mitsubishi", "name": "Outlander (CW)", "slug": "outlander-2", "series": "Outlander", "keywords": ["2.0 DI-D", "2.2 DI-D", "4WD"] },
    { "id": "mitsubishi-outlander-3", "brandId": "mitsubishi", "name": "Outlander (GF)", "slug": "outlander-3", "series": "Outlander", "keywords": ["PHEV", "Hybrid", "2.2 DI-D"] },
    { "id": "mitsubishi-pajero-3", "brandId": "mitsubishi", "name": "Pajero (V60)", "slug": "pajero-3", "series": "Pajero", "keywords": ["3.2 DI-D", "Wagon"] },
    { "id": "mitsubishi-pajero-4", "brandId": "mitsubishi", "name": "Pajero (V80)", "slug": "pajero-4", "series": "Pajero", "keywords": ["3.2 DI-D", "Wagon"] },
    { "id": "mitsubishi-space-star", "brandId": "mitsubishi", "name": "Space Star", "slug": "space-star", "series": "Space Star", "keywords": ["1.0", "1.2", "1.3", "1.6", "1.9 DI-D"] },
    { "id": "nissan-100nx", "brandId": "nissan", "name": "100NX (B13)", "slug": "100nx", "series": "100NX" },
    { "id": "nissan-200sx", "brandId": "nissan", "name": "200SX (S13 / S14)", "slug": "200sx", "series": "200SX" },
    { "id": "nissan-300zx", "brandId": "nissan", "name": "300ZX (Z31 / Z32)", "slug": "300zx", "series": "300ZX" },
    { "id": "nissan-350z", "brandId": "nissan", "name": "350Z (Z33)", "slug": "350z", "series": "Z" },
    { "id": "nissan-370z", "brandId": "nissan", "name": "370Z (Z34)", "slug": "370z", "series": "Z" },
    { "id": "nissan-almera-n15", "brandId": "nissan", "name": "Almera I (Mk1 / N15)", "slug": "almera-n15", "series": "Almera" },
    { "id": "nissan-almera-n16", "brandId": "nissan", "name": "Almera II (Mk2 / N16)", "slug": "almera-n16", "series": "Almera" },
    { "id": "nissan-almera-tino", "brandId": "nissan", "name": "Almera Tino (V10)", "slug": "almera-tino", "series": "Almera" },
    { "id": "nissan-ariya", "brandId": "nissan", "name": "Ariya", "slug": "ariya", "series": "Ariya" },
    { "id": "nissan-atleon", "brandId": "nissan", "name": "Atleon", "slug": "atleon", "series": "Truck" },
    { "id": "nissan-bluebird", "brandId": "nissan", "name": "Bluebird (U11 / T12 / T72)", "slug": "bluebird", "series": "Bluebird" },
    { "id": "nissan-cabstar", "brandId": "nissan", "name": "Cabstar", "slug": "cabstar", "series": "Truck" },
    { "id": "nissan-cherry", "brandId": "nissan", "name": "Cherry (N10 / N12)", "slug": "cherry", "series": "Cherry" },
    { "id": "nissan-cube", "brandId": "nissan", "name": "Cube (Z11 / Z12)", "slug": "cube", "series": "Cube" },
    { "id": "nissan-gtr", "brandId": "nissan", "name": "GT-R (R35)", "slug": "gtr", "series": "GT-R" },
    { "id": "nissan-interstar", "brandId": "nissan", "name": "Interstar", "slug": "interstar", "series": "Van" },
    { "id": "nissan-juke-1", "brandId": "nissan", "name": "Juke I (Mk1 / F15)", "slug": "juke-1", "series": "Juke", "keywords": ["1.6", "1.5 DCI"] },
    { "id": "nissan-juke-2", "brandId": "nissan", "name": "Juke II (Mk2 / F16)", "slug": "juke-2", "series": "Juke" },
    { "id": "nissan-kubistar", "brandId": "nissan", "name": "Kubistar (X76)", "slug": "kubistar", "series": "Van" },
    { "id": "nissan-leaf-1", "brandId": "nissan", "name": "Leaf I (Mk1 / ZE0)", "slug": "leaf-1", "series": "Leaf" },
    { "id": "nissan-leaf-2", "brandId": "nissan", "name": "Leaf II (Mk2 / ZE1)", "slug": "leaf-2", "series": "Leaf" },
    { "id": "nissan-maxima", "brandId": "nissan", "name": "Maxima (J30 / A32 / A33)", "slug": "maxima", "series": "Maxima" },
    { "id": "nissan-micra-k10", "brandId": "nissan", "name": "Micra I (Mk1 / K10)", "slug": "micra-k10", "series": "Micra" },
    { "id": "nissan-micra-k11", "brandId": "nissan", "name": "Micra II (Mk2 / K11)", "slug": "micra-k11", "series": "Micra", "keywords": ["K11", "Bakancs", "Bakancs Micra", "1.0", "1.3"] },
    { "id": "nissan-micra-k12", "brandId": "nissan", "name": "Micra III (Mk3 / K12)", "slug": "micra-k12", "series": "Micra" },
    { "id": "nissan-micra-k13", "brandId": "nissan", "name": "Micra IV (Mk4 / K13)", "slug": "micra-k13", "series": "Micra" },
    { "id": "nissan-micra-k14", "brandId": "nissan", "name": "Micra V (Mk5 / K14)", "slug": "micra-k14", "series": "Micra" },
    { "id": "nissan-murano", "brandId": "nissan", "name": "Murano (Z50 / Z51 / Z52)", "slug": "murano", "series": "Murano" },
    { "id": "nissan-navara-d21", "brandId": "nissan", "name": "Navara (D21)", "slug": "navara-d21", "series": "Navara" },
    { "id": "nissan-navara-d22", "brandId": "nissan", "name": "Navara (D22)", "slug": "navara-d22", "series": "Navara" },
    { "id": "nissan-navara-d40", "brandId": "nissan", "name": "Navara (D40)", "slug": "navara-d40", "series": "Navara" },
    { "id": "nissan-navara-d23", "brandId": "nissan", "name": "Navara (D23/NP300)", "slug": "navara-d23", "series": "Navara" },
    { "id": "nissan-np300", "brandId": "nissan", "name": "NP300", "slug": "np300", "series": "Pickup" },
    { "id": "nissan-note-e11", "brandId": "nissan", "name": "Note I (Mk1 / E11)", "slug": "note-e11", "series": "Note" },
    { "id": "nissan-note-e12", "brandId": "nissan", "name": "Note II (Mk2 / E12)", "slug": "note-e12", "series": "Note" },
    { "id": "nissan-nv200", "brandId": "nissan", "name": "NV200", "slug": "nv200", "series": "Van" },
    { "id": "nissan-nv300", "brandId": "nissan", "name": "NV300", "slug": "nv300", "series": "Van" },
    { "id": "nissan-nv400", "brandId": "nissan", "name": "NV400", "slug": "nv400", "series": "Van" },
    { "id": "nissan-pathfinder-wd21", "brandId": "nissan", "name": "Pathfinder I (WD21)", "slug": "pathfinder-wd21", "series": "Pathfinder" },
    { "id": "nissan-pathfinder-r50", "brandId": "nissan", "name": "Pathfinder II (R50)", "slug": "pathfinder-r50", "series": "Pathfinder" },
    { "id": "nissan-pathfinder-r51", "brandId": "nissan", "name": "Pathfinder III (R51)", "slug": "pathfinder-r51", "series": "Pathfinder" },
    { "id": "nissan-patrol-y60", "brandId": "nissan", "name": "Patrol (Y60)", "slug": "patrol-y60", "series": "Patrol" },
    { "id": "nissan-patrol-y61", "brandId": "nissan", "name": "Patrol (Y61)", "slug": "patrol-y61", "series": "Patrol" },
    { "id": "nissan-pickup", "brandId": "nissan", "name": "Pick Up (D21 / D22)", "slug": "pickup", "series": "Pickup" },
    { "id": "nissan-pixo", "brandId": "nissan", "name": "Pixo (UA0)", "slug": "pixo", "series": "Pixo" },
    { "id": "nissan-prairie", "brandId": "nissan", "name": "Prairie (M10 / M11)", "slug": "prairie", "series": "Prairie" },
    { "id": "nissan-primastar", "brandId": "nissan", "name": "Primastar (X83)", "slug": "primastar", "series": "Van" },
    { "id": "nissan-primera-p10", "brandId": "nissan", "name": "Primera I (Mk1 / P10)", "slug": "primera-p10", "series": "Primera" },
    { "id": "nissan-primera-p11", "brandId": "nissan", "name": "Primera II (Mk2 / P11)", "slug": "primera-p11", "series": "Primera" },
    { "id": "nissan-primera-p12", "brandId": "nissan", "name": "Primera III (Mk3 / P12)", "slug": "primera-p12", "series": "Primera" },
    { "id": "nissan-pulsar", "brandId": "nissan", "name": "Pulsar (N15 / N16 / C13)", "slug": "pulsar", "series": "Pulsar" },
    { "id": "nissan-pulsar-nx", "brandId": "nissan", "name": "Pulsar NX (N12 / N13)", "slug": "pulsar-nx", "series": "Pulsar NX" },
    { "id": "nissan-qashqai-j10", "brandId": "nissan", "name": "Qashqai I (Mk1 / J10)", "slug": "qashqai-j10", "series": "Qashqai", "keywords": ["+2", "1.5 DCI", "1.6 DCI", "2.0 DCI"] },
    { "id": "nissan-qashqai-j11", "brandId": "nissan", "name": "Qashqai II (Mk2 / J11)", "slug": "qashqai-j11", "series": "Qashqai", "keywords": ["1.2 DIG-T", "1.5 DCI", "1.6 DCI"] },
    { "id": "nissan-qashqai-j12", "brandId": "nissan", "name": "Qashqai III (Mk3 / J12)", "slug": "qashqai-j12", "series": "Qashqai" },
    { "id": "nissan-serena", "brandId": "nissan", "name": "Serena (C23 / C24 / C25)", "slug": "serena", "series": "Serena" },
    { "id": "nissan-stanza", "brandId": "nissan", "name": "Stanza (T11)", "slug": "stanza", "series": "Stanza" },
    { "id": "nissan-sunny", "brandId": "nissan", "name": "Sunny (B11 / B12 / N13 / N14)", "slug": "sunny", "series": "Sunny" },
    { "id": "nissan-terrano-1", "brandId": "nissan", "name": "Terrano I (Mk1 / WD21)", "slug": "terrano-1", "series": "Terrano" },
    { "id": "nissan-terrano-2", "brandId": "nissan", "name": "Terrano II (Mk2 / R20)", "slug": "terrano-2", "series": "Terrano" },
    { "id": "nissan-tiida-c11", "brandId": "nissan", "name": "Tiida I (Mk1 / C11)", "slug": "tiida-c11", "series": "Tiida" },
    { "id": "nissan-tiida-c13", "brandId": "nissan", "name": "Tiida II (Mk2 / C13)", "slug": "tiida-c13", "series": "Tiida" },
    { "id": "nissan-townstar", "brandId": "nissan", "name": "Townstar", "slug": "townstar", "series": "Van" },
    { "id": "nissan-trade", "brandId": "nissan", "name": "Trade", "slug": "trade", "series": "Van" },
    { "id": "nissan-urvan", "brandId": "nissan", "name": "Urvan", "slug": "urvan", "series": "Van" },
    { "id": "nissan-vanette", "brandId": "nissan", "name": "Vanette (C120 / C22 / HC23)", "slug": "vanette", "series": "Vanette" },
    { "id": "nissan-xtrail-t30", "brandId": "nissan", "name": "X-Trail I (Mk1 / T30)", "slug": "xtrail-t30", "series": "X-Trail" },
    { "id": "nissan-xtrail-t31", "brandId": "nissan", "name": "X-Trail II (Mk2 / T31)", "slug": "xtrail-t31", "series": "X-Trail" },
    { "id": "nissan-xtrail-t32", "brandId": "nissan", "name": "X-Trail III (Mk3 / T32)", "slug": "xtrail-t32", "series": "X-Trail" },
    { "id": "nissan-xtrail-t33", "brandId": "nissan", "name": "X-Trail IV (Mk4 / T33)", "slug": "xtrail-t33", "series": "X-Trail" },
    { "id": "subaru-forester-1", "brandId": "subaru", "name": "Forester (SF)", "slug": "forester-1", "series": "Forester" },
    { "id": "subaru-forester-2", "brandId": "subaru", "name": "Forester (SG)", "slug": "forester-2", "series": "Forester", "keywords": ["2.0 Turbo", "XT"] },
    { "id": "subaru-forester-3", "brandId": "subaru", "name": "Forester (SH)", "slug": "forester-3", "series": "Forester", "keywords": ["2.0 D", "Boxer Diesel"] },
    { "id": "subaru-forester-4", "brandId": "subaru", "name": "Forester (SJ)", "slug": "forester-4", "series": "Forester", "keywords": ["2.0 D", "Boxer Diesel"] },
    { "id": "subaru-impreza-1", "brandId": "subaru", "name": "Impreza (GC/GF)", "slug": "impreza-1", "series": "Impreza" },
    { "id": "subaru-impreza-2", "brandId": "subaru", "name": "Impreza (GD/GG)", "slug": "impreza-2", "series": "Impreza" },
    { "id": "subaru-impreza-3", "brandId": "subaru", "name": "Impreza (GE/GH/GR)", "slug": "impreza-3", "series": "Impreza" },
    { "id": "subaru-impreza-4", "brandId": "subaru", "name": "Impreza (GP/GJ)", "slug": "impreza-4", "series": "Impreza" },
    { "id": "subaru-legacy-4", "brandId": "subaru", "name": "Legacy IV (BL/BP)", "slug": "legacy-4", "series": "Legacy" },
    { "id": "subaru-outback-3", "brandId": "subaru", "name": "Outback III (BP)", "slug": "outback-3", "series": "Outback" },
    { "id": "subaru-outback-4", "brandId": "subaru", "name": "Outback IV (BR)", "slug": "outback-4", "series": "Outback" },
    { "id": "subaru-xv", "brandId": "subaru", "name": "XV/Crosstrek", "slug": "xv", "series": "XV" },
    { "id": "subaru-brz", "brandId": "subaru", "name": "BRZ", "slug": "brz", "series": "BRZ" },
    { "id": "subaru-justy", "brandId": "subaru", "name": "Justy", "slug": "justy", "series": "Justy" },
    { "id": "subaru-levorg", "brandId": "subaru", "name": "Levorg", "slug": "levorg", "series": "Levorg" },
    { "id": "subaru-tribeca", "brandId": "subaru", "name": "Tribeca", "slug": "tribeca", "series": "Tribeca" },
    { "id": "subaru-solterra", "brandId": "subaru", "name": "Solterra", "slug": "solterra", "series": "Solterra" },
    { "id": "subaru-svx", "brandId": "subaru", "name": "SVX", "slug": "svx", "series": "SVX" },
    { "id": "suzuki-alto-1", "brandId": "suzuki", "name": "Alto I (Mk1)", "slug": "suzuki-alto-1", "series": "Alto" },
    { "id": "suzuki-alto-2", "brandId": "suzuki", "name": "Alto II (Mk2)", "slug": "suzuki-alto-2", "series": "Alto" },
    { "id": "suzuki-alto-3", "brandId": "suzuki", "name": "Alto III (Mk3)", "slug": "suzuki-alto-3", "series": "Alto" },
    { "id": "suzuki-alto-4", "brandId": "suzuki", "name": "Alto IV (Mk4)", "slug": "suzuki-alto-4", "series": "Alto" },
    { "id": "suzuki-alto-5", "brandId": "suzuki", "name": "Alto V (Mk5)", "slug": "alto-5", "series": "Alto" },
    { "id": "suzuki-alto-6", "brandId": "suzuki", "name": "Alto VI (Mk6)", "slug": "alto-6", "series": "Alto" },
    { "id": "suzuki-alto-7", "brandId": "suzuki", "name": "Alto VII (Mk7 / GF)", "slug": "alto-7", "series": "Alto" },
    { "id": "suzuki-baleno-1", "brandId": "suzuki", "name": "Baleno I (Mk1 / EG)", "slug": "suzuki-baleno-1", "series": "Baleno" },
    { "id": "suzuki-baleno-2", "brandId": "suzuki", "name": "Baleno II (Mk2 / WB)", "slug": "baleno", "series": "Baleno" },
    { "id": "suzuki-carry", "brandId": "suzuki", "name": "Carry (Mk7 / SK)", "slug": "suzuki-carry", "series": "Van" },
    { "id": "suzuki-super-carry", "brandId": "suzuki", "name": "Super Carry (Mk1 / SK)", "slug": "suzuki-super-carry", "series": "Van" },
    { "id": "suzuki-celerio", "brandId": "suzuki", "name": "Celerio (Mk1)", "slug": "celerio", "series": "Celerio" },
    { "id": "suzuki-grand-vitara-1", "brandId": "suzuki", "name": "Grand Vitara I (Mk1 / FT/GT)", "slug": "suzuki-grand-vitara-1", "series": "Vitara" },
    { "id": "suzuki-grand-vitara-2", "brandId": "suzuki", "name": "Grand Vitara II (Mk2 / JT)", "slug": "grand-vitara", "series": "Vitara" },
    { "id": "suzuki-ignis-1", "brandId": "suzuki", "name": "Ignis I (Mk1 / FH)", "slug": "ignis-1", "series": "Ignis" },
    { "id": "suzuki-ignis-2", "brandId": "suzuki", "name": "Ignis II (Mk2 / MH)", "slug": "ignis-2", "series": "Ignis" },
    { "id": "suzuki-ignis-3", "brandId": "suzuki", "name": "Ignis III (Mk3 / MF)", "slug": "ignis-3", "series": "Ignis" },
    { "id": "suzuki-jimny-3", "brandId": "suzuki", "name": "Jimny III (Mk3 / FJ)", "slug": "suzuki-jimny-3", "series": "Jimny" },
    { "id": "suzuki-jimny-4", "brandId": "suzuki", "name": "Jimny IV (Mk4 / GJ)", "slug": "jimny", "series": "Jimny" },
    { "id": "suzuki-liana", "brandId": "suzuki", "name": "Liana (Mk1)", "slug": "liana", "series": "Liana" },
    { "id": "suzuki-maruti", "brandId": "suzuki", "name": "Maruti 800", "slug": "suzuki-maruti", "series": "Maruti" },
    { "id": "suzuki-sj", "brandId": "suzuki", "name": "SJ 410 / 413", "slug": "suzuki-sj", "series": "SJ" },
    { "id": "suzuki-splash", "brandId": "suzuki", "name": "Splash (Mk1)", "slug": "splash", "series": "Splash" },
    { "id": "suzuki-swift-1", "brandId": "suzuki", "name": "Swift I (Mk1 / AA)", "slug": "suzuki-swift-1", "series": "Swift" },
    { "id": "suzuki-swift-2", "brandId": "suzuki", "name": "Swift II (Mk2 / EA)", "slug": "swift-2", "series": "Swift", "keywords": ["1.0", "1.3", "Sedan", "GTI"] },
    { "id": "suzuki-swift-3", "brandId": "suzuki", "name": "Swift III (Mk3 / MZ/EZ)", "slug": "swift-3", "series": "Swift", "keywords": ["1.3", "1.5", "1.3 DDIS", "Sport", "vRS"] },
    { "id": "suzuki-swift-4", "brandId": "suzuki", "name": "Swift IV (Mk4 / FZ/NZ)", "slug": "swift-4", "series": "Swift", "keywords": ["1.2 VVT", "1.3 DDIS", "Sport"] },
    { "id": "suzuki-swift-5", "brandId": "suzuki", "name": "Swift V (Mk5 / AZ)", "slug": "swift-5", "series": "Swift" },
    { "id": "suzuki-swift-cabrio", "brandId": "suzuki", "name": "Swift Cabrio", "slug": "suzuki-swift-cabrio", "series": "Swift" },
    { "id": "suzuki-sx4", "brandId": "suzuki", "name": "SX4 (Mk1 / EY/GY)", "slug": "sx4", "series": "SX4" },
    { "id": "suzuki-sx4-scross", "brandId": "suzuki", "name": "SX4 S-Cross (Mk2 / JY)", "slug": "sx4-scross", "series": "S-Cross" },
    { "id": "suzuki-scross", "brandId": "suzuki", "name": "S-Cross (Mk3 / JY)", "slug": "suzuki-scross", "series": "S-Cross" },
    { "id": "suzuki-vitara-et", "brandId": "suzuki", "name": "Vitara I (Mk1 / ET/TA)", "slug": "suzuki-vitara-1", "series": "Vitara" },
    { "id": "suzuki-vitara-ly", "brandId": "suzuki", "name": "Vitara II (Mk2 / LY)", "slug": "vitara", "series": "Vitara", "keywords": ["1.6", "1.4 Turbo", "Hybrid"] },
    { "id": "suzuki-kizashi", "brandId": "suzuki", "name": "Kizashi (Mk1)", "slug": "kizashi", "series": "Kizashi" },
    { "id": "suzuki-samurai", "brandId": "suzuki", "name": "Samurai (Mk1)", "slug": "samurai", "series": "Samurai" },
    { "id": "suzuki-wagon-r-1", "brandId": "suzuki", "name": "Wagon R+ I (Mk1 / MA61)", "slug": "suzuki-wagon-r-1", "series": "Wagon R" },
    { "id": "suzuki-wagon-r-2", "brandId": "suzuki", "name": "Wagon R+ II (Mk2 / EM)", "slug": "wagon-r", "series": "Wagon R" },
    { "id": "suzuki-across", "brandId": "suzuki", "name": "Across (PHEV)", "slug": "across", "series": "Across" },
    { "id": "suzuki-swace", "brandId": "suzuki", "name": "Swace (Hybrid)", "slug": "swace", "series": "Swace" },
    { "id": "toyota-1000", "brandId": "toyota", "name": "1000 (KP30)", "slug": "toyota-1000", "series": "1000" },
    { "id": "toyota-4runner", "brandId": "toyota", "name": "4-Runner (N60/N120/N180/N210/N280)", "slug": "4runner", "series": "4-Runner" },
    { "id": "toyota-auris-1", "brandId": "toyota", "name": "Auris I (Mk1 / E150)", "slug": "auris-1", "series": "Auris" },
    { "id": "toyota-auris-2", "brandId": "toyota", "name": "Auris II (Mk2 / E180)", "slug": "auris-2", "series": "Auris" },
    { "id": "toyota-avensis-1", "brandId": "toyota", "name": "Avensis I (Mk1 / T220)", "slug": "avensis-1", "series": "Avensis", "keywords": ["1.6", "1.8", "2.0 TD"] },
    { "id": "toyota-avensis-2", "brandId": "toyota", "name": "Avensis II (Mk2 / T250)", "slug": "avensis-2", "series": "Avensis", "keywords": ["D4-D", "2.2 D-CAT", "1.8", "2.0", "1ZZ-FE", "1AZ-FSE", "1CD-FTV", "2AD-FHV"] },
    { "id": "toyota-avensis-3", "brandId": "toyota", "name": "Avensis III (Mk3 / T270)", "slug": "avensis-3", "series": "Avensis", "keywords": ["D4-D", "VALVEMATIC", "1AD-FTV", "2AD-FTV"] },
    { "id": "toyota-avensis-verso", "brandId": "toyota", "name": "Avensis Verso (Mk1 / M20)", "slug": "avensis-verso", "series": "Avensis" },
    { "id": "toyota-aygo-1", "brandId": "toyota", "name": "Aygo I (Mk1 / AB10)", "slug": "aygo-1", "series": "Aygo" },
    { "id": "toyota-aygo-2", "brandId": "toyota", "name": "Aygo II (Mk2 / AB40)", "slug": "aygo-2", "series": "Aygo" },
    { "id": "toyota-aygo-x", "brandId": "toyota", "name": "Aygo X (Mk1 / AB70)", "slug": "aygo-x", "series": "Aygo" },
    { "id": "toyota-bz4x", "brandId": "toyota", "name": "bZ4X (Mk1 / EA10)", "slug": "bz4x", "series": "bZ4X" },
    { "id": "toyota-caldina", "brandId": "toyota", "name": "Caldina (T190/T210/T240)", "slug": "toyota-caldina", "series": "Caldina" },
    { "id": "toyota-camry-xv10", "brandId": "toyota", "name": "Camry (XV10)", "slug": "toyota-camry-xv10", "series": "Camry" },
    { "id": "toyota-camry-xv20", "brandId": "toyota", "name": "Camry (XV20)", "slug": "toyota-camry-xv20", "series": "Camry" },
    { "id": "toyota-camry-xv30", "brandId": "toyota", "name": "Camry (XV30)", "slug": "toyota-camry-xv30", "series": "Camry" },
    { "id": "toyota-camry-xv40", "brandId": "toyota", "name": "Camry (XV40)", "slug": "toyota-camry-xv40", "series": "Camry" },
    { "id": "toyota-camry-xv50", "brandId": "toyota", "name": "Camry (XV50)", "slug": "toyota-camry-xv50", "series": "Camry" },
    { "id": "toyota-camry-xv70", "brandId": "toyota", "name": "Camry (XV70)", "slug": "toyota-camry-xv70", "series": "Camry" },
    { "id": "toyota-carina", "brandId": "toyota", "name": "Carina (T150/T170/T190)", "slug": "carina", "series": "Carina" },
    { "id": "toyota-celica", "brandId": "toyota", "name": "Celica (T160/T180/T200/T230)", "slug": "celica", "series": "Celica" },
    { "id": "toyota-chr-1", "brandId": "toyota", "name": "C-HR I (Mk1 / AX10)", "slug": "chr", "series": "C-HR" },
    { "id": "toyota-chr-2", "brandId": "toyota", "name": "C-HR II (Mk2 / AX20)", "slug": "toyota-chr-2", "series": "C-HR" },
    { "id": "toyota-corolla-100", "brandId": "toyota", "name": "Corolla VII (Mk7 / E100)", "slug": "toyota-corolla-e100", "series": "Corolla" },
    { "id": "toyota-corolla-110", "brandId": "toyota", "name": "Corolla VIII (Mk8 / E110)", "slug": "toyota-corolla-e110", "series": "Corolla" },
    { "id": "toyota-corolla-9", "brandId": "toyota", "name": "Corolla IX (Mk9 / E120)", "slug": "corolla-9", "series": "Corolla", "keywords": ["1.4 VVTi", "1.6 VVTi", "2.0 D4-D", "TS", "T-Sport"] },
    { "id": "toyota-corolla-10", "brandId": "toyota", "name": "Corolla X (Mk10 / E150)", "slug": "corolla-10", "series": "Corolla", "keywords": ["1.33 Dual VVTi", "1.6 Valvematic", "1.4 D-4D", "2.0 D-4D"] },
    { "id": "toyota-corolla-11", "brandId": "toyota", "name": "Corolla XI (Mk11 / E170)", "slug": "corolla-11", "series": "Corolla", "keywords": ["1.6 Valvematic", "1.4 D-4D"] },
    { "id": "toyota-corolla-12", "brandId": "toyota", "name": "Corolla XII (Mk12 / E210)", "slug": "corolla-12", "series": "Corolla", "keywords": ["Hybrid", "1.8 Hybrid", "2.0 Hybrid", "GR Sport"] },
    { "id": "toyota-corolla-cross", "brandId": "toyota", "name": "Corolla Cross (Mk1 / XG10)", "slug": "corolla-cross", "series": "Corolla" },
    { "id": "toyota-corolla-verso-1", "brandId": "toyota", "name": "Corolla Verso I (Mk1 / E11)", "slug": "toyota-corolla-verso-1", "series": "Corolla" },
    { "id": "toyota-corolla-verso-2", "brandId": "toyota", "name": "Corolla Verso II (Mk2 / E12)", "slug": "toyota-corolla-verso-2", "series": "Corolla" },
    { "id": "toyota-corolla-verso-3", "brandId": "toyota", "name": "Corolla Verso III (Mk3 / R1)", "slug": "toyota-corolla-verso-3", "series": "Corolla" },
    { "id": "toyota-dyna", "brandId": "toyota", "name": "Dyna (U series)", "slug": "toyota-dyna", "series": "Truck" },
    { "id": "toyota-gt86", "brandId": "toyota", "name": "GT86 (Mk1 / ZN6)", "slug": "gt86", "series": "GT86" },
    { "id": "toyota-gr86", "brandId": "toyota", "name": "GR86 (Mk2 / ZN8)", "slug": "gr86", "series": "GR86" },
    { "id": "toyota-hiace", "brandId": "toyota", "name": "Hiace (H50/H100/H200)", "slug": "hiace", "series": "Van" },
    { "id": "toyota-highlander", "brandId": "toyota", "name": "Highlander (XU20/XU40/XU50/XU70)", "slug": "toyota-highlander", "series": "Highlander" },
    { "id": "toyota-hilux-4", "brandId": "toyota", "name": "Hilux IV (Mk4 / N50/N60/N70)", "slug": "toyota-hilux-4", "series": "Hilux" },
    { "id": "toyota-hilux-5", "brandId": "toyota", "name": "Hilux V (Mk5 / N80/N90/N100/N110)", "slug": "toyota-hilux-5", "series": "Hilux" },
    { "id": "toyota-hilux-6", "brandId": "toyota", "name": "Hilux VI (Mk6 / N140/N150/N160/N170)", "slug": "toyota-hilux-6", "series": "Hilux" },
    { "id": "toyota-hilux-7", "brandId": "toyota", "name": "Hilux VII (Mk7 / AN10/AN20/AN30)", "slug": "hilux-7", "series": "Hilux" },
    { "id": "toyota-hilux-8", "brandId": "toyota", "name": "Hilux VIII (Mk8 / AN120/AN130)", "slug": "hilux-8", "series": "Hilux" },
    { "id": "toyota-iq", "brandId": "toyota", "name": "iQ (Mk1 / AJ10)", "slug": "iq", "series": "iQ" },
    { "id": "toyota-land-cruiser-j70", "brandId": "toyota", "name": "Land Cruiser (J70)", "slug": "toyota-land-cruiser-j70", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j80", "brandId": "toyota", "name": "Land Cruiser (J80)", "slug": "toyota-land-cruiser-j80", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j100", "brandId": "toyota", "name": "Land Cruiser (J100)", "slug": "toyota-land-cruiser-j100", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j120", "brandId": "toyota", "name": "Land Cruiser (J120)", "slug": "land-cruiser-j120", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j150", "brandId": "toyota", "name": "Land Cruiser (J150)", "slug": "land-cruiser-j150", "series": "Land Cruiser" },
    { "id": "toyota-land-cruiser-j200", "brandId": "toyota", "name": "Land Cruiser (J200)", "slug": "toyota-land-cruiser-j200", "series": "Land Cruiser" },
    { "id": "toyota-liteace", "brandId": "toyota", "name": "Liteace (R series)", "slug": "toyota-liteace", "series": "Van" },
    { "id": "toyota-matrix", "brandId": "toyota", "name": "Matrix (E130/E140)", "slug": "toyota-matrix", "series": "Matrix" },
    { "id": "toyota-mirai", "brandId": "toyota", "name": "Mirai (JPD10/JPD20)", "slug": "mirai", "series": "Mirai" },
    { "id": "toyota-model-f", "brandId": "toyota", "name": "Model F (R20)", "slug": "toyota-model-f", "series": "Van" },
    { "id": "toyota-mr2", "brandId": "toyota", "name": "MR2 (W10/W20/W30)", "slug": "mr2", "series": "MR2" },
    { "id": "toyota-picnic", "brandId": "toyota", "name": "Picnic (Mk1 / XM10)", "slug": "picnic", "series": "Picnic" },
    { "id": "toyota-previa", "brandId": "toyota", "name": "Previa (XR10/XR30/XR50)", "slug": "previa", "series": "Previa" },
    { "id": "toyota-prius-2", "brandId": "toyota", "name": "Prius II (Mk2 / XW20)", "slug": "prius-2", "series": "Prius", "keywords": ["Hybrid", "1.5 HSD"] },
    { "id": "toyota-prius-3", "brandId": "toyota", "name": "Prius III (Mk3 / XW30)", "slug": "prius-3", "series": "Prius", "keywords": ["Hybrid", "Plug-in", "1.8 HSD"] },
    { "id": "toyota-prius-4", "brandId": "toyota", "name": "Prius IV (Mk4 / XW50)", "slug": "prius-4", "series": "Prius" },
    { "id": "toyota-prius-plus", "brandId": "toyota", "name": "Prius Plus (ZVW40)", "slug": "prius-plus", "series": "Prius" },
    { "id": "toyota-proace-1", "brandId": "toyota", "name": "Proace I (Mk1 / MDX)", "slug": "proace-1", "series": "Van" },
    { "id": "toyota-proace-2", "brandId": "toyota", "name": "Proace II (Mk2 / KO)", "slug": "proace", "series": "Van" },
    { "id": "toyota-proace-city", "brandId": "toyota", "name": "Proace City (Mk1 / K9)", "slug": "toyota-proace-city", "series": "Van" },
    { "id": "toyota-proace-city-verso", "brandId": "toyota", "name": "Proace City Verso", "slug": "toyota-proace-city-verso", "series": "Van" },
    { "id": "toyota-rav4-2", "brandId": "toyota", "name": "RAV4 II (Mk2 / XA20)", "slug": "rav4-2", "series": "RAV4" },
    { "id": "toyota-rav4-3", "brandId": "toyota", "name": "RAV4 III (Mk3 / XA30)", "slug": "rav4-3", "series": "RAV4" },
    { "id": "toyota-rav4-4", "brandId": "toyota", "name": "RAV4 IV (Mk4 / XA40)", "slug": "rav4-4", "series": "RAV4" },
    { "id": "toyota-rav4-5", "brandId": "toyota", "name": "RAV4 V (Mk5 / XA50)", "slug": "rav4-5", "series": "RAV4" },
    { "id": "toyota-sienna", "brandId": "toyota", "name": "Sienna (XL10/XL20/XL30/XL40)", "slug": "toyota-sienna", "series": "Sienna" },
    { "id": "toyota-starlet", "brandId": "toyota", "name": "Starlet (P7/P8/P9)", "slug": "starlet", "series": "Starlet" },
    { "id": "toyota-supra", "brandId": "toyota", "name": "Supra (A70/A80/A90/DB)", "slug": "supra", "series": "Supra" },
    { "id": "toyota-tercel", "brandId": "toyota", "name": "Tercel (L series)", "slug": "toyota-tercel", "series": "Tercel" },
    { "id": "toyota-tundra", "brandId": "toyota", "name": "Tundra (XK30/XK50/XK70)", "slug": "toyota-tundra", "series": "Tundra" },
    { "id": "toyota-urban-cruiser", "brandId": "toyota", "name": "Urban Cruiser (Mk2 / XP110)", "slug": "urban-cruiser", "series": "Urban Cruiser" },
    { "id": "toyota-verso", "brandId": "toyota", "name": "Verso / Verso-S (R20/P120)", "slug": "verso", "series": "Verso" },
    { "id": "toyota-yaris-1", "brandId": "toyota", "name": "Yaris I (Mk1 / XP10)", "slug": "yaris-1", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.3 VVT-i", "1.4 D-4D", "TS"] },
    { "id": "toyota-yaris-2", "brandId": "toyota", "name": "Yaris II (Mk2 / XP90)", "slug": "yaris-2", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.33 Dual VVT-i", "1.4 D-4D"] },
    { "id": "toyota-yaris-3", "brandId": "toyota", "name": "Yaris III (Mk3 / XP130)", "slug": "yaris-3", "series": "Yaris", "keywords": ["1.0 VVT-i", "1.33 VVT-i", "1.5 HSD", "Hybrid", "1.4 D-4D"] },
    { "id": "toyota-yaris-4", "brandId": "toyota", "name": "Yaris IV (Mk4 / XP210)", "slug": "yaris-4", "series": "Yaris", "keywords": ["1.5 Hybrid", "GR Yaris"] },
    { "id": "toyota-yaris-cross", "brandId": "toyota", "name": "Yaris Cross (Mk1 / XP210)", "slug": "yaris-cross", "series": "Yaris", "keywords": ["Hybrid", "e-Four"] },
    { "id": "toyota-yaris-verso", "brandId": "toyota", "name": "Yaris Verso (XP20)", "slug": "toyota-yaris-verso", "series": "Yaris" },
];
