import { Model } from './types';

export const frenchGroupModels: Model[] = [
    { "id": "citroen-ami", "brandId": "citroen", "name": "Ami", "slug": "ami", "series": "Ami" },
    { "id": "citroen-berlingo-1", "brandId": "citroen", "name": "Berlingo (Mk1)", "slug": "berlingo-1", "series": "Berlingo", "keywords": ["1.9 D", "2.0 HDI"] },
    { "id": "citroen-berlingo-2", "brandId": "citroen", "name": "Berlingo (Mk2)", "slug": "berlingo-2", "series": "Berlingo", "keywords": ["1.6 HDI", "Multispace"] },
    { "id": "citroen-berlingo-3", "brandId": "citroen", "name": "Berlingo (Mk3)", "slug": "berlingo-3", "series": "Berlingo" },
    { "id": "citroen-celysee", "brandId": "citroen", "name": "C-Elysée", "slug": "celysee", "series": "C-Elysée" },
    { "id": "citroen-c1", "brandId": "citroen", "name": "C1", "slug": "c1", "series": "C1" },
    { "id": "citroen-c2", "brandId": "citroen", "name": "C2", "slug": "c2", "series": "C2" },
    { "id": "citroen-c3-1", "brandId": "citroen", "name": "C3 (Mk1)", "slug": "c3-1", "series": "C3", "keywords": ["1.4 HDI", "1.1", "1.4"] },
    { "id": "citroen-c3-2", "brandId": "citroen", "name": "C3 (Mk2)", "slug": "c3-2", "series": "C3", "keywords": ["Picasso", "1.6 HDI", "VTI"] },
    { "id": "citroen-c3-3", "brandId": "citroen", "name": "C3 (Mk3)", "slug": "c3-3", "series": "C3", "keywords": ["Aircross", "PureTech"] },
    { "id": "citroen-c3-aircross", "brandId": "citroen", "name": "C3 Aircross", "slug": "c3-aircross", "series": "C3" },
    { "id": "citroen-c3-picasso", "brandId": "citroen", "name": "C3 Picasso", "slug": "c3-picasso", "series": "C3" },
    { "id": "citroen-c3-pluriel", "brandId": "citroen", "name": "C3 Pluriel", "slug": "c3-pluriel", "series": "C3" },
    { "id": "citroen-c4-1", "brandId": "citroen", "name": "C4 (Mk1)", "slug": "c4-1", "series": "C4", "keywords": ["Picasso", "Grand Picasso", "1.6 HDI", "2.0 HDI"] },
    { "id": "citroen-c4-2", "brandId": "citroen", "name": "C4 (Mk2)", "slug": "c4-2", "series": "C4", "keywords": ["Picasso", "Grand Picasso", "1.6 HDI", "e-HDI"] },
    { "id": "citroen-c4-3", "brandId": "citroen", "name": "C4 (Mk3)", "slug": "c4-3", "series": "C4", "keywords": ["Cactus", "Aircross", "PureTech"] },
    { "id": "citroen-c4-cactus", "brandId": "citroen", "name": "C4 Cactus", "slug": "c4-cactus", "series": "C4" },
    { "id": "citroen-c4-aircross", "brandId": "citroen", "name": "C4 Aircross", "slug": "c4-aircross", "series": "C4" },
    { "id": "citroen-c4-spacetourer", "brandId": "citroen", "name": "C4 Spacetourer / Grand Picasso", "slug": "c4-spacetourer", "series": "C4" },
    { "id": "citroen-c4-picasso-1", "brandId": "citroen", "name": "C4 Picasso (Mk1)", "slug": "c4-picasso-1", "series": "C4" },
    { "id": "citroen-c4-picasso-2", "brandId": "citroen", "name": "C4 Picasso (Mk2)", "slug": "c4-picasso-2", "series": "C4" },
    { "id": "citroen-c5-1", "brandId": "citroen", "name": "C5 (Mk1)", "slug": "c5-1", "series": "C5", "keywords": ["2.0 HDI", "2.2 HDI"] },
    { "id": "citroen-c5-2", "brandId": "citroen", "name": "C5 (Mk2 / X7)", "slug": "c5-2", "series": "C5", "keywords": ["Tourer", "2.0 HDI", "2.2 HDI"] },
    { "id": "citroen-c5-aircross", "brandId": "citroen", "name": "C5 Aircross", "slug": "c5-aircross", "series": "C5" },
    { "id": "citroen-c5-x", "brandId": "citroen", "name": "C5 X", "slug": "c5-x", "series": "C5" },
    { "id": "citroen-ccrosser", "brandId": "citroen", "name": "C-Crosser", "slug": "ccrosser", "series": "C-Crosser" },
    { "id": "citroen-c6", "brandId": "citroen", "name": "C6", "slug": "c6", "series": "C6" },
    { "id": "citroen-c8", "brandId": "citroen", "name": "C8", "slug": "c8", "series": "C8" },
    { "id": "citroen-nemo", "brandId": "citroen", "name": "Nemo", "slug": "nemo", "series": "Nemo" },
    { "id": "citroen-xm", "brandId": "citroen", "name": "XM", "slug": "xm", "series": "XM" },
    { "id": "citroen-xantia", "brandId": "citroen", "name": "Xantia", "slug": "xantia", "series": "Xantia" },
    { "id": "citroen-zx", "brandId": "citroen", "name": "ZX", "slug": "zx", "series": "ZX" },
    { "id": "citroen-ds3", "brandId": "citroen", "name": "DS3", "slug": "ds3", "series": "DS3" },
    { "id": "citroen-ds4", "brandId": "citroen", "name": "DS4", "slug": "ds4", "series": "DS4" },
    { "id": "citroen-ds5", "brandId": "citroen", "name": "DS5", "slug": "ds5", "series": "DS5" },
    { "id": "citroen-evasion", "brandId": "citroen", "name": "Evasion", "slug": "evasion", "series": "Evasion" },
    { "id": "citroen-jumper-1", "brandId": "citroen", "name": "Jumper (Mk1)", "slug": "jumper-1", "series": "Jumper" },
    { "id": "citroen-jumper-2", "brandId": "citroen", "name": "Jumper (Mk2)", "slug": "jumper-2", "series": "Jumper" },
    { "id": "citroen-jumpy-1", "brandId": "citroen", "name": "Jumpy (Mk1)", "slug": "jumpy-1", "series": "Jumpy" },
    { "id": "citroen-jumpy-2", "brandId": "citroen", "name": "Jumpy (Mk2)", "slug": "jumpy-2", "series": "Jumpy" },
    { "id": "citroen-jumpy-3", "brandId": "citroen", "name": "Jumpy (Mk3)", "slug": "jumpy-3", "series": "Jumpy" },
    { "id": "citroen-saxo", "brandId": "citroen", "name": "Saxo", "slug": "saxo", "series": "Saxo" },
    { "id": "citroen-xsara", "brandId": "citroen", "name": "Xsara", "slug": "xsara", "series": "Xsara" },
    { "id": "citroen-xsara-picasso", "brandId": "citroen", "name": "Xsara Picasso", "slug": "xsara-picasso", "series": "Xsara" },
    { "id": "peugeot-1007", "brandId": "peugeot", "name": "1007 (KM)", "slug": "1007", "series": "1007" },
    { "id": "peugeot-104", "brandId": "peugeot", "name": "104", "slug": "104", "series": "104" },
    { "id": "peugeot-106-1", "brandId": "peugeot", "name": "106 I (Mk1 / 1A/C)", "slug": "106-1", "series": "106" },
    { "id": "peugeot-106-2", "brandId": "peugeot", "name": "106 II (Mk2 / 1S)", "slug": "106-2", "series": "106" },
    { "id": "peugeot-107", "brandId": "peugeot", "name": "107 (P)", "slug": "107", "series": "107" },
    { "id": "peugeot-108", "brandId": "peugeot", "name": "108", "slug": "108", "series": "108" },
    { "id": "peugeot-2008-1", "brandId": "peugeot", "name": "2008 I (Mk1 / A94)", "slug": "2008-1", "series": "2008" },
    { "id": "peugeot-2008-2", "brandId": "peugeot", "name": "2008 II (Mk2 / P24)", "slug": "2008-2", "series": "2008" },
    { "id": "peugeot-205", "brandId": "peugeot", "name": "205", "slug": "205", "series": "205" },
    { "id": "peugeot-206", "brandId": "peugeot", "name": "206 (Mk1 / T1)", "slug": "206", "series": "206", "keywords": ["CC", "SW", "GTI", "RC", "1.4 HDI", "1.1", "1.4", "1.6"] },
    { "id": "peugeot-206-plus", "brandId": "peugeot", "name": "206+ (Mk2 / T3E)", "slug": "206-plus", "series": "206" },
    { "id": "peugeot-207", "brandId": "peugeot", "name": "207 (Mk1 / A7)", "slug": "207", "series": "207", "keywords": ["CC", "SW", "RC", "1.6 HDI", "VTI"] },
    { "id": "peugeot-208-1", "brandId": "peugeot", "name": "208 I (Mk1 / A9)", "slug": "208-1", "series": "208", "keywords": ["GTI", "e-208"] },
    { "id": "peugeot-208-2", "brandId": "peugeot", "name": "208 II (Mk2 / P21)", "slug": "208-2", "series": "208" },
    { "id": "peugeot-3008-1", "brandId": "peugeot", "name": "3008 I (Mk1 / T8)", "slug": "3008-1", "series": "3008" },
    { "id": "peugeot-3008-2", "brandId": "peugeot", "name": "3008 II (Mk2 / P84)", "slug": "3008-2", "series": "3008" },
    { "id": "peugeot-3008-3", "brandId": "peugeot", "name": "3008 III (Mk3 / P64)", "slug": "3008-3", "series": "3008" },
    { "id": "peugeot-301", "brandId": "peugeot", "name": "301", "slug": "301", "series": "301" },
    { "id": "peugeot-304", "brandId": "peugeot", "name": "304", "slug": "304", "series": "304" },
    { "id": "peugeot-305", "brandId": "peugeot", "name": "305", "slug": "305", "series": "305" },
    { "id": "peugeot-306", "brandId": "peugeot", "name": "306 (Mk1 / N3/N5)", "slug": "306", "series": "306" },
    { "id": "peugeot-307", "brandId": "peugeot", "name": "307 (Mk1 / T5/T6)", "slug": "307", "series": "307", "keywords": ["CC", "SW", "Break", "1.6 HDI", "2.0 HDI"] },
    { "id": "peugeot-308-1", "brandId": "peugeot", "name": "308 I (Mk1 / T7)", "slug": "308-1", "series": "308", "keywords": ["CC", "SW", "GTI", "THP", "1.6 HDI", "2.0 HDI", "9HX", "9HZ", "RHR"] },
    { "id": "peugeot-308-2", "brandId": "peugeot", "name": "308 II (Mk2 / T9)", "slug": "308-2", "series": "308", "keywords": ["SW", "GTI", "BlueHDI", "1.6 BlueHDI", "2.0 BlueHDI", "PureTech", "BHX", "AHX"] },
    { "id": "peugeot-308-3", "brandId": "peugeot", "name": "308 III (Mk3 / P5)", "slug": "308-3", "series": "308", "keywords": ["Hybrid", "PureTech", "e-308"] },
    { "id": "peugeot-309", "brandId": "peugeot", "name": "309", "slug": "309", "series": "309" },
    { "id": "peugeot-4007", "brandId": "peugeot", "name": "4007 (GP)", "slug": "4007", "series": "4007" },
    { "id": "peugeot-4008", "brandId": "peugeot", "name": "4008", "slug": "4008", "series": "4008" },
    { "id": "peugeot-404", "brandId": "peugeot", "name": "404", "slug": "404", "series": "404" },
    { "id": "peugeot-405", "brandId": "peugeot", "name": "405", "slug": "405", "series": "405" },
    { "id": "peugeot-406", "brandId": "peugeot", "name": "406 (Mk1 / D8/D9)", "slug": "406", "series": "406" },
    { "id": "peugeot-407", "brandId": "peugeot", "name": "407 (Mk1 / D2)", "slug": "407", "series": "407" },
    { "id": "peugeot-408", "brandId": "peugeot", "name": "408 (Mk1 / P54)", "slug": "408", "series": "408" },
    { "id": "peugeot-5008-1", "brandId": "peugeot", "name": "5008 I (Mk1 / T85)", "slug": "5008-1", "series": "5008" },
    { "id": "peugeot-5008-2", "brandId": "peugeot", "name": "5008 II (Mk2 / P87)", "slug": "5008-2", "series": "5008" },
    { "id": "peugeot-504", "brandId": "peugeot", "name": "504", "slug": "504", "series": "504" },
    { "id": "peugeot-505", "brandId": "peugeot", "name": "505", "slug": "505", "series": "505" },
    { "id": "peugeot-508-1", "brandId": "peugeot", "name": "508 I (Mk1 / W2)", "slug": "508-1", "series": "508" },
    { "id": "peugeot-508-2", "brandId": "peugeot", "name": "508 II (Mk2 / R8)", "slug": "508-2", "series": "508" },
    { "id": "peugeot-508-rxh", "brandId": "peugeot", "name": "508 RXH", "slug": "508-rxh", "series": "508" },
    { "id": "peugeot-604", "brandId": "peugeot", "name": "604", "slug": "604", "series": "604" },
    { "id": "peugeot-605", "brandId": "peugeot", "name": "605", "slug": "605", "series": "605" },
    { "id": "peugeot-607", "brandId": "peugeot", "name": "607 (Mk1 / Z8/Z9)", "slug": "607", "series": "607" },
    { "id": "peugeot-806", "brandId": "peugeot", "name": "806 (Mk1 / 221)", "slug": "806", "series": "806" },
    { "id": "peugeot-807", "brandId": "peugeot", "name": "807 (Mk1 / V)", "slug": "807", "series": "807" },
    { "id": "peugeot-bipper", "brandId": "peugeot", "name": "Bipper (AA)", "slug": "bipper", "series": "Bipper" },
    { "id": "peugeot-boxer-1", "brandId": "peugeot", "name": "Boxer I (Mk1 / 230/244)", "slug": "boxer-1", "series": "Boxer" },
    { "id": "peugeot-boxer-2", "brandId": "peugeot", "name": "Boxer II (Mk2 / 250)", "slug": "boxer-2", "series": "Boxer" },
    { "id": "peugeot-expert-1", "brandId": "peugeot", "name": "Expert I (Mk1 / 222)", "slug": "expert-1", "series": "Expert" },
    { "id": "peugeot-expert-2", "brandId": "peugeot", "name": "Expert II (Mk2 / G9)", "slug": "expert-2", "series": "Expert" },
    { "id": "peugeot-expert-3", "brandId": "peugeot", "name": "Expert III (Mk3 / K0)", "slug": "expert-3", "series": "Expert" },
    { "id": "peugeot-ion", "brandId": "peugeot", "name": "iOn", "slug": "ion", "series": "iOn" },
    { "id": "peugeot-j5", "brandId": "peugeot", "name": "J5 (280/290)", "slug": "j5", "series": "J5" },
    { "id": "peugeot-partner-1", "brandId": "peugeot", "name": "Partner I (Mk1 / M49/M59)", "slug": "partner-1", "series": "Partner" },
    { "id": "peugeot-partner-2", "brandId": "peugeot", "name": "Partner II (Mk2 / B9)", "slug": "partner-2", "series": "Partner" },
    { "id": "peugeot-partner-3", "brandId": "peugeot", "name": "Partner III (Mk3 / K9) / Ranch", "slug": "partner-3", "series": "Partner" },
    { "id": "peugeot-rcz", "brandId": "peugeot", "name": "RCZ", "slug": "rcz", "series": "RCZ" },
    { "id": "peugeot-rifter", "brandId": "peugeot", "name": "Rifter (K9)", "slug": "rifter", "series": "Rifter" },
    { "id": "peugeot-traveller", "brandId": "peugeot", "name": "Traveller (K0)", "slug": "traveller", "series": "Traveller" },
    { "id": "renault-4", "brandId": "renault", "name": "4", "slug": "4", "series": "4" },
    { "id": "renault-5", "brandId": "renault", "name": "5", "slug": "5", "series": "5" },
    { "id": "renault-super-5", "brandId": "renault", "name": "Super 5 (Super)", "slug": "super-5", "series": "5" },
    { "id": "renault-7", "brandId": "renault", "name": "7", "slug": "7", "series": "7" },
    { "id": "renault-9", "brandId": "renault", "name": "9", "slug": "9", "series": "9" },
    { "id": "renault-11", "brandId": "renault", "name": "11", "slug": "11", "series": "11" },
    { "id": "renault-14", "brandId": "renault", "name": "14", "slug": "14", "series": "14" },
    { "id": "renault-18", "brandId": "renault", "name": "18", "slug": "18", "series": "18" },
    { "id": "renault-19", "brandId": "renault", "name": "19", "slug": "19", "series": "19" },
    { "id": "renault-20", "brandId": "renault", "name": "20", "slug": "20", "series": "20" },
    { "id": "renault-21", "brandId": "renault", "name": "21", "slug": "21", "series": "21" },
    { "id": "renault-25", "brandId": "renault", "name": "25", "slug": "25", "series": "25" },
    { "id": "renault-30", "brandId": "renault", "name": "30", "slug": "30", "series": "30" },
    { "id": "renault-alaskan", "brandId": "renault", "name": "Alaskan", "slug": "alaskan", "series": "Pickup" },
    { "id": "renault-arkana", "brandId": "renault", "name": "Arkana I (Mk1 / LJ)", "slug": "arkana", "series": "Arkana" },
    { "id": "renault-austral", "brandId": "renault", "name": "Austral (Mk1 / RHN)", "slug": "austral", "series": "Austral" },
    { "id": "renault-b120", "brandId": "renault", "name": "B 120", "slug": "b120", "series": "Truck" },
    { "id": "renault-captur-1", "brandId": "renault", "name": "Captur I (Mk1 / J5/H5)", "slug": "captur-1", "series": "Captur" },
    { "id": "renault-captur-2", "brandId": "renault", "name": "Captur II (Mk2 / JB/JE)", "slug": "captur-2", "series": "Captur" },
    { "id": "renault-clio-1", "brandId": "renault", "name": "Clio I (Mk1 / X57)", "slug": "clio-1", "series": "Clio" },
    { "id": "renault-clio-2", "brandId": "renault", "name": "Clio II (Mk2 / X65)", "slug": "clio-2", "series": "Clio", "keywords": ["RS", "1.2 16V", "1.4 16V", "1.5 dCi"] },
    { "id": "renault-clio-3", "brandId": "renault", "name": "Clio III (Mk3 / X85)", "slug": "clio-3", "series": "Clio", "keywords": ["RS", "GT", "1.2 16V", "1.2 TCE", "1.5 dCi", "K9K"] },
    { "id": "renault-clio-4", "brandId": "renault", "name": "Clio IV (Mk4 / X98)", "slug": "clio-4", "series": "Clio", "keywords": ["RS", "GT", "0.9 TCE", "1.2 TCE", "1.5 dCi", "K9K"] },
    { "id": "renault-clio-5", "brandId": "renault", "name": "Clio V (Mk5 / BJA)", "slug": "clio-5", "series": "Clio", "keywords": ["E-Tech", "Hybrid", "1.0 TCE"] },
    { "id": "renault-espace-1", "brandId": "renault", "name": "Espace I (Mk1 / J11)", "slug": "espace-1", "series": "Espace" },
    { "id": "renault-espace-2", "brandId": "renault", "name": "Espace II (Mk2 / J63)", "slug": "espace-2", "series": "Espace" },
    { "id": "renault-espace-3", "brandId": "renault", "name": "Espace III (Mk3 / JE)", "slug": "espace-3", "series": "Espace" },
    { "id": "renault-espace-4", "brandId": "renault", "name": "Espace IV (Mk4 / JK)", "slug": "espace-4", "series": "Espace" },
    { "id": "renault-espace-5", "brandId": "renault", "name": "Espace V (Mk5 / JR)", "slug": "espace-5", "series": "Espace" },
    { "id": "renault-espace-6", "brandId": "renault", "name": "Espace VI (Mk6 / RHN)", "slug": "espace-6", "series": "Espace" },
    { "id": "renault-express", "brandId": "renault", "name": "Express (Mk1 / Mk2)", "slug": "express", "series": "Van" },
    { "id": "renault-fluence", "brandId": "renault", "name": "Fluence (L3)", "slug": "fluence", "series": "Fluence" },
    { "id": "renault-fuego", "brandId": "renault", "name": "Fuego", "slug": "fuego", "series": "Fuego" },
    { "id": "renault-kadjar", "brandId": "renault", "name": "Kadjar (HLA)", "slug": "kadjar", "series": "Kadjar" },
    { "id": "renault-kangoo-1", "brandId": "renault", "name": "Kangoo I (Mk1 / KC)", "slug": "kangoo-1", "series": "Kangoo" },
    { "id": "renault-kangoo-2", "brandId": "renault", "name": "Kangoo II (Mk2 / FW)", "slug": "kangoo-2", "series": "Kangoo" },
    { "id": "renault-kangoo-3", "brandId": "renault", "name": "Kangoo III (Mk3 / XJK)", "slug": "kangoo-3", "series": "Kangoo" },
    { "id": "renault-koleos-1", "brandId": "renault", "name": "Koleos I (Mk1 / HY)", "slug": "koleos-1", "series": "Koleos" },
    { "id": "renault-koleos-2", "brandId": "renault", "name": "Koleos II (Mk2 / HC)", "slug": "koleos-2", "series": "Koleos" },
    { "id": "renault-laguna-1", "brandId": "renault", "name": "Laguna I (Mk1 / B56)", "slug": "laguna-1", "series": "Laguna" },
    { "id": "renault-laguna-2", "brandId": "renault", "name": "Laguna II (Mk2 / G)", "slug": "laguna-2", "series": "Laguna" },
    { "id": "renault-laguna-3", "brandId": "renault", "name": "Laguna III (Mk3 / T)", "slug": "laguna-3", "series": "Laguna" },
    { "id": "renault-laguna-coupe", "brandId": "renault", "name": "Laguna Coupe (D3)", "slug": "laguna-coupe", "series": "Laguna" },
    { "id": "renault-latitude", "brandId": "renault", "name": "Latitude (L70)", "slug": "latitude", "series": "Latitude" },
    { "id": "renault-logan", "brandId": "renault", "name": "Logan (L90 / LS)", "slug": "logan", "series": "Logan" },
    { "id": "renault-mascott", "brandId": "renault", "name": "Mascott", "slug": "mascott", "series": "Truck" },
    { "id": "renault-master-1", "brandId": "renault", "name": "Master I (Mk1 / T/P)", "slug": "master-1", "series": "Master" },
    { "id": "renault-master-2", "brandId": "renault", "name": "Master II (Mk2 / X70)", "slug": "master-2", "series": "Master" },
    { "id": "renault-master-3", "brandId": "renault", "name": "Master III (Mk3 / X62)", "slug": "master-3", "series": "Master" },
    { "id": "renault-megane-1", "brandId": "renault", "name": "Megane I (Mk1 / X64)", "slug": "megane-1", "series": "Megane", "keywords": ["Classic", "Coach", "Scenic", "1.4 16V", "1.6 16V", "1.9 dTi", "1.9 dCi"] },
    { "id": "renault-megane-2", "brandId": "renault", "name": "Megane II (Mk2 / X84)", "slug": "megane-2", "series": "Megane", "keywords": ["Kombi", "Sedan", "CC", "RS", "1.4 16V", "1.6 16V", "1.5 dCi", "1.9 dCi", "K4M", "K9K", "F9Q"] },
    { "id": "renault-megane-3", "brandId": "renault", "name": "Megane III (Mk3 / X95)", "slug": "megane-3", "series": "Megane", "keywords": ["Coupe", "Grandtour", "RS", "GT", "1.5 dCi", "1.6 dCi", "1.4 TCE", "2.0 dCi", "K9K", "R9M", "M9R"] },
    { "id": "renault-megane-4", "brandId": "renault", "name": "Megane IV (Mk4 / BFB)", "slug": "megane-4", "series": "Megane", "keywords": ["Grandtour", "RS", "GT", "1.3 TCE", "1.5 dCi", "1.6 dCi"] },
    { "id": "renault-megane-cc", "brandId": "renault", "name": "Megane CC", "slug": "megane-cc", "series": "Megane" },
    { "id": "renault-megane-grandtour", "brandId": "renault", "name": "Megane Grandtour", "slug": "megane-grandtour", "series": "Megane" },
    { "id": "renault-megane-etron", "brandId": "renault", "name": "Megane E-Tech (BCB)", "slug": "megane-etron", "series": "Megane", "keywords": ["Electric", "EV60"] },
    { "id": "renault-modus", "brandId": "renault", "name": "Modus (F/JP0)", "slug": "modus", "series": "Modus" },
    { "id": "renault-rapid", "brandId": "renault", "name": "Rapid", "slug": "rapid", "series": "Van" },
    { "id": "renault-rafale", "brandId": "renault", "name": "Rafale", "slug": "rafale", "series": "Rafale" },
    { "id": "renault-rodeo", "brandId": "renault", "name": "Rodeo", "slug": "rodeo", "series": "Rodeo" },
    { "id": "renault-safrane", "brandId": "renault", "name": "Safrane (B54)", "slug": "safrane", "series": "Safrane" },
    { "id": "renault-scenic-1", "brandId": "renault", "name": "Scénic I (Mk1 / JA)", "slug": "scenic-1", "series": "Scénic" },
    { "id": "renault-scenic-2", "brandId": "renault", "name": "Scénic II (Mk2 / JM)", "slug": "scenic-2", "series": "Scénic" },
    { "id": "renault-scenic-3", "brandId": "renault", "name": "Scénic III (Mk3 / JZ)", "slug": "scenic-3", "series": "Scénic" },
    { "id": "renault-scenic-4", "brandId": "renault", "name": "Scénic IV (Mk4 / JFA)", "slug": "scenic-4", "series": "Scénic" },
    { "id": "renault-scenic-5", "brandId": "renault", "name": "Scénic V E-Tech", "slug": "scenic-5", "series": "Scénic" },
    { "id": "renault-grand-scenic", "brandId": "renault", "name": "Grand Scénic", "slug": "grand-scenic", "series": "Scénic" },
    { "id": "renault-talisman", "brandId": "renault", "name": "Talisman (LFD)", "slug": "talisman", "series": "Talisman" },
    { "id": "renault-talisman-grandtour", "brandId": "renault", "name": "Talisman Grandtour", "slug": "talisman-grandtour", "series": "Talisman" },
    { "id": "renault-thalia-1", "brandId": "renault", "name": "Thalia I (Mk1 / LB)", "slug": "thalia-1", "series": "Thalia" },
    { "id": "renault-thalia-2", "brandId": "renault", "name": "Thalia II (Mk2 / LU)", "slug": "thalia-2", "series": "Thalia" },
    { "id": "renault-thalia-3", "brandId": "renault", "name": "Thalia III (Mk3 / L52)", "slug": "thalia-3", "series": "Thalia" },
    { "id": "renault-trafic-1", "brandId": "renault", "name": "Trafic I (Mk1 / T)", "slug": "trafic-1", "series": "Trafic" },
    { "id": "renault-trafic-2", "brandId": "renault", "name": "Trafic II (Mk2 / X83)", "slug": "trafic-2", "series": "Trafic" },
    { "id": "renault-trafic-3", "brandId": "renault", "name": "Trafic III (Mk3 / X82)", "slug": "trafic-3", "series": "Trafic" },
    { "id": "renault-twingo-1", "brandId": "renault", "name": "Twingo I (Mk1 / C06)", "slug": "twingo-1", "series": "Twingo" },
    { "id": "renault-twingo-2", "brandId": "renault", "name": "Twingo II (Mk2 / CN0)", "slug": "twingo-2", "series": "Twingo" },
    { "id": "renault-twingo-3", "brandId": "renault", "name": "Twingo III (Mk3 / BCM)", "slug": "twingo-3", "series": "Twingo" },
    { "id": "renault-twizy", "brandId": "renault", "name": "Twizy", "slug": "twizy", "series": "Twizy" },
    { "id": "renault-velsatis", "brandId": "renault", "name": "Vel Satis", "slug": "velsatis", "series": "Vel Satis" },
    { "id": "renault-wind", "brandId": "renault", "name": "Wind", "slug": "wind", "series": "Wind" },
    { "id": "renault-zoe", "brandId": "renault", "name": "Zoe (BF)", "slug": "zoe", "series": "Zoe" },
    { "id": "dacia-1300", "brandId": "dacia", "name": "1300", "slug": "1300", "series": "1300" },
    { "id": "dacia-1310", "brandId": "dacia", "name": "1310", "slug": "1310", "series": "1310" },
    { "id": "dacia-1410", "brandId": "dacia", "name": "1410", "slug": "1410", "series": "1410" },
    { "id": "dacia-bigster", "brandId": "dacia", "name": "Bigster", "slug": "bigster", "series": "Bigster" },
    { "id": "dacia-dokker", "brandId": "dacia", "name": "Dokker", "slug": "dokker", "series": "Dokker" },
    { "id": "dacia-duster-1", "brandId": "dacia", "name": "Duster I (Mk1)", "slug": "duster-1", "series": "Duster", "keywords": ["1.5 dCi", "1.6 16V", "4x4"] },
    { "id": "dacia-duster-2", "brandId": "dacia", "name": "Duster II (Mk2)", "slug": "duster-2", "series": "Duster", "keywords": ["1.5 dCi", "1.3 TCE", "4x4"] },
    { "id": "dacia-duster-3", "brandId": "dacia", "name": "Duster III (Mk3)", "slug": "duster-3", "series": "Duster" },
    { "id": "dacia-jogger", "brandId": "dacia", "name": "Jogger", "slug": "jogger", "series": "Jogger" },
    { "id": "dacia-lodgy", "brandId": "dacia", "name": "Lodgy", "slug": "lodgy", "series": "Lodgy", "keywords": ["Stepway", "1.5 DCI", "TCe"] },
    { "id": "dacia-logan-1", "brandId": "dacia", "name": "Logan I (Mk1)", "slug": "logan-1", "series": "Logan", "keywords": ["MCV", "1.4 MPI", "1.5 dCi"] },
    { "id": "dacia-logan-2", "brandId": "dacia", "name": "Logan II (Mk2)", "slug": "logan-2", "series": "Logan", "keywords": ["MCV", "0.9 TCE", "1.5 dCi"] },
    { "id": "dacia-logan-3", "brandId": "dacia", "name": "Logan III (Mk3)", "slug": "logan-3", "series": "Logan" },
    { "id": "dacia-nova", "brandId": "dacia", "name": "Nova", "slug": "nova", "series": "Nova" },
    { "id": "dacia-pickup", "brandId": "dacia", "name": "Pick Up", "slug": "pickup", "series": "Pick Up" },
    { "id": "dacia-sandero-1", "brandId": "dacia", "name": "Sandero I (Mk1)", "slug": "sandero-1", "series": "Sandero", "keywords": ["Stepway", "1.4 MPI", "1.5 dCi"] },
    { "id": "dacia-sandero-2", "brandId": "dacia", "name": "Sandero II (Mk2)", "slug": "sandero-2", "series": "Sandero", "keywords": ["Stepway", "0.9 TCE", "1.5 dCi"] },
    { "id": "dacia-sandero-3", "brandId": "dacia", "name": "Sandero III (Mk3)", "slug": "sandero-3", "series": "Sandero" },
    { "id": "dacia-solenza", "brandId": "dacia", "name": "Solenza", "slug": "solenza", "series": "Solenza" },
    { "id": "dacia-spring", "brandId": "dacia", "name": "Spring", "slug": "spring", "series": "Spring" },
    { "id": "dacia-supernova", "brandId": "dacia", "name": "SuperNova", "slug": "supernova", "series": "SuperNova" },
];
