import { Model } from './types';

export const frenchGroupModels: Model[] = [
    { "id": "citroen-ami", "brandId": "citroen", "name": "Ami", "slug": "ami", "series": "Ami" },
    { "id": "citroen-berlingo-1", "brandId": "citroen", "name": "Berlingo I", "slug": "berlingo-1", "series": "Berlingo", "keywords": ["1.9 D", "2.0 HDI"] },
    { "id": "citroen-berlingo-2", "brandId": "citroen", "name": "Berlingo II", "slug": "berlingo-2", "series": "Berlingo", "keywords": ["1.6 HDI", "Multispace"] },
    { "id": "citroen-berlingo-3", "brandId": "citroen", "name": "Berlingo III", "slug": "berlingo-3", "series": "Berlingo" },
    { "id": "citroen-celysee", "brandId": "citroen", "name": "C-Elysée", "slug": "celysee", "series": "C-Elysée" },
    { "id": "citroen-c1", "brandId": "citroen", "name": "C1", "slug": "c1", "series": "C1" },
    { "id": "citroen-c2", "brandId": "citroen", "name": "C2", "slug": "c2", "series": "C2" },
    { "id": "citroen-c3-1", "brandId": "citroen", "name": "C3 I", "slug": "c3-1", "series": "C3", "keywords": ["1.4 HDI", "1.1", "1.4"] },
    { "id": "citroen-c3-2", "brandId": "citroen", "name": "C3 II", "slug": "c3-2", "series": "C3", "keywords": ["Picasso", "1.6 HDI", "VTI"] },
    { "id": "citroen-c3-3", "brandId": "citroen", "name": "C3 III", "slug": "c3-3", "series": "C3", "keywords": ["Aircross", "PureTech"] },
    { "id": "citroen-c3-aircross", "brandId": "citroen", "name": "C3 Aircross", "slug": "c3-aircross", "series": "C3" },
    { "id": "citroen-c3-picasso", "brandId": "citroen", "name": "C3 Picasso", "slug": "c3-picasso", "series": "C3" },
    { "id": "citroen-c3-pluriel", "brandId": "citroen", "name": "C3 Pluriel", "slug": "c3-pluriel", "series": "C3" },
    { "id": "citroen-c4-1", "brandId": "citroen", "name": "C4 I", "slug": "c4-1", "series": "C4", "keywords": ["Picasso", "Grand Picasso", "1.6 HDI", "2.0 HDI"] },
    { "id": "citroen-c4-2", "brandId": "citroen", "name": "C4 II", "slug": "c4-2", "series": "C4", "keywords": ["Picasso", "Grand Picasso", "1.6 HDI", "e-HDI"] },
    { "id": "citroen-c4-3", "brandId": "citroen", "name": "C4 III", "slug": "c4-3", "series": "C4", "keywords": ["Cactus", "Aircross", "PureTech"] },
    { "id": "citroen-c4-cactus", "brandId": "citroen", "name": "C4 Cactus", "slug": "c4-cactus", "series": "C4" },
    { "id": "citroen-c4-aircross", "brandId": "citroen", "name": "C4 Aircross", "slug": "c4-aircross", "series": "C4" },
    { "id": "citroen-c4-spacetourer", "brandId": "citroen", "name": "C4 Spacetourer / Grand Picasso", "slug": "c4-spacetourer", "series": "C4" },
    { "id": "citroen-c4-picasso-1", "brandId": "citroen", "name": "C4 Picasso I", "slug": "c4-picasso-1", "series": "C4" },
    { "id": "citroen-c4-picasso-2", "brandId": "citroen", "name": "C4 Picasso II", "slug": "c4-picasso-2", "series": "C4" },
    { "id": "citroen-c5-1", "brandId": "citroen", "name": "C5 I", "slug": "c5-1", "series": "C5", "keywords": ["2.0 HDI", "2.2 HDI"] },
    { "id": "citroen-c5-2", "brandId": "citroen", "name": "C5 II", "slug": "c5-2", "series": "C5", "keywords": ["Tourer", "2.0 HDI", "2.2 HDI"] },
    { "id": "citroen-c5-aircross", "brandId": "citroen", "name": "C5 Aircross", "slug": "c5-aircross", "series": "C5" },
    { "id": "citroen-c5-x", "brandId": "citroen", "name": "C5 X", "slug": "c5-x", "series": "C5" },
    { "id": "citroen-ccrosser", "brandId": "citroen", "name": "C-Crosser", "slug": "ccrosser", "series": "C-Crosser" },
    { "id": "citroen-c6", "brandId": "citroen", "name": "C6", "slug": "c6", "series": "C6" },
    { "id": "citroen-c8", "brandId": "citroen", "name": "C8", "slug": "c8", "series": "C8" },
    { "id": "citroen-nemo", "brandId": "citroen", "name": "Nemo", "slug": "nemo", "series": "Nemo" },
    { "id": "citroen-xm", "brandId": "citroen", "name": "XM", "slug": "xm", "series": "XM" },
    { "id": "citroen-xantia", "brandId": "citroen", "name": "Xantia", "slug": "xantia", "series": "Xantia" },
    { "id": "citroen-zx", "brandId": "citroen", "name": "ZX", "slug": "zx", "series": "ZX" },
    { "id": "citroen-ds3", "brandId": "citroen", "name": "DS3", "slug": "ds3", "series": "DS3" },
    { "id": "citroen-ds4", "brandId": "citroen", "name": "DS4", "slug": "ds4", "series": "DS4" },
    { "id": "citroen-ds5", "brandId": "citroen", "name": "DS5", "slug": "ds5", "series": "DS5" },
    { "id": "citroen-evasion", "brandId": "citroen", "name": "Evasion", "slug": "evasion", "series": "Evasion" },
    { "id": "citroen-jumper-1", "brandId": "citroen", "name": "Jumper I", "slug": "jumper-1", "series": "Jumper" },
    { "id": "citroen-jumper-2", "brandId": "citroen", "name": "Jumper II", "slug": "jumper-2", "series": "Jumper" },
    { "id": "citroen-jumpy-1", "brandId": "citroen", "name": "Jumpy I", "slug": "jumpy-1", "series": "Jumpy" },
    { "id": "citroen-jumpy-2", "brandId": "citroen", "name": "Jumpy II", "slug": "jumpy-2", "series": "Jumpy" },
    { "id": "citroen-jumpy-3", "brandId": "citroen", "name": "Jumpy III", "slug": "jumpy-3", "series": "Jumpy" },
    { "id": "citroen-saxo", "brandId": "citroen", "name": "Saxo", "slug": "saxo", "series": "Saxo" },
    { "id": "citroen-xsara", "brandId": "citroen", "name": "Xsara", "slug": "xsara", "series": "Xsara" },
    { "id": "citroen-xsara-picasso", "brandId": "citroen", "name": "Xsara Picasso", "slug": "xsara-picasso", "series": "Xsara" },
    { "id": "peugeot-106", "brandId": "peugeot", "name": "106", "slug": "106", "series": "106" },
    { "id": "peugeot-107", "brandId": "peugeot", "name": "107", "slug": "107", "series": "107" },
    { "id": "peugeot-108", "brandId": "peugeot", "name": "108", "slug": "108", "series": "108" },
    { "id": "peugeot-1007", "brandId": "peugeot", "name": "1007", "slug": "1007", "series": "1007" },
    { "id": "peugeot-205", "brandId": "peugeot", "name": "205", "slug": "205", "series": "205" },
    { "id": "peugeot-206", "brandId": "peugeot", "name": "206", "slug": "206", "series": "206", "keywords": ["CC", "SW", "GTI", "RC", "1.4 HDI", "1.1", "1.4", "1.6"] },
    { "id": "peugeot-207", "brandId": "peugeot", "name": "207", "slug": "207", "series": "207", "keywords": ["CC", "SW", "RC", "1.6 HDI", "VTI"] },
    { "id": "peugeot-208-1", "brandId": "peugeot", "name": "208 I", "slug": "208-1", "series": "208", "keywords": ["GTI", "e-208"] },
    { "id": "peugeot-208-2", "brandId": "peugeot", "name": "208 II", "slug": "208-2", "series": "208" },
    { "id": "peugeot-2008-1", "brandId": "peugeot", "name": "2008 I", "slug": "2008-1", "series": "2008" },
    { "id": "peugeot-2008-2", "brandId": "peugeot", "name": "2008 II", "slug": "2008-2", "series": "2008" },
    { "id": "peugeot-306", "brandId": "peugeot", "name": "306", "slug": "306", "series": "306" },
    { "id": "peugeot-307", "brandId": "peugeot", "name": "307", "slug": "307", "series": "307", "keywords": ["CC", "SW", "Break", "1.6 HDI", "2.0 HDI"] },
    { "id": "peugeot-308-1", "brandId": "peugeot", "name": "308 I", "slug": "308-1", "series": "308", "keywords": ["CC", "SW", "GTI", "THP", "1.6 HDI", "2.0 HDI", "9HX", "9HZ", "RHR"] },
    { "id": "peugeot-308-2", "brandId": "peugeot", "name": "308 II", "slug": "308-2", "series": "308", "keywords": ["SW", "GTI", "BlueHDI", "1.6 BlueHDI", "2.0 BlueHDI", "PureTech", "BHX", "AHX"] },
    { "id": "peugeot-308-3", "brandId": "peugeot", "name": "308 III", "slug": "308-3", "series": "308", "keywords": ["Hybrid", "PureTech", "e-308"] },
    { "id": "peugeot-301", "brandId": "peugeot", "name": "301", "slug": "301", "series": "301" },
    { "id": "peugeot-309", "brandId": "peugeot", "name": "309", "slug": "309", "series": "309" },
    { "id": "peugeot-3008-1", "brandId": "peugeot", "name": "3008 I", "slug": "3008-1", "series": "3008" },
    { "id": "peugeot-3008-2", "brandId": "peugeot", "name": "3008 II", "slug": "3008-2", "series": "3008" },
    { "id": "peugeot-406", "brandId": "peugeot", "name": "406", "slug": "406", "series": "406" },
    { "id": "peugeot-407", "brandId": "peugeot", "name": "407", "slug": "407", "series": "407" },
    { "id": "peugeot-408", "brandId": "peugeot", "name": "408", "slug": "408", "series": "408" },
    { "id": "peugeot-4007", "brandId": "peugeot", "name": "4007", "slug": "4007", "series": "4007" },
    { "id": "peugeot-4008", "brandId": "peugeot", "name": "4008", "slug": "4008", "series": "4008" },
    { "id": "peugeot-405", "brandId": "peugeot", "name": "405", "slug": "405", "series": "405" },
    { "id": "peugeot-508-1", "brandId": "peugeot", "name": "508 I", "slug": "508-1", "series": "508" },
    { "id": "peugeot-508-rxh", "brandId": "peugeot", "name": "508 RXH", "slug": "508-rxh", "series": "508" },
    { "id": "peugeot-508-2", "brandId": "peugeot", "name": "508 II", "slug": "508-2", "series": "508" },
    { "id": "peugeot-605", "brandId": "peugeot", "name": "605", "slug": "605", "series": "605" },
    { "id": "peugeot-607", "brandId": "peugeot", "name": "607", "slug": "607", "series": "607" },
    { "id": "peugeot-5008-1", "brandId": "peugeot", "name": "5008 I", "slug": "5008-1", "series": "5008" },
    { "id": "peugeot-5008-2", "brandId": "peugeot", "name": "5008 II", "slug": "5008-2", "series": "5008" },
    { "id": "peugeot-807", "brandId": "peugeot", "name": "807", "slug": "807", "series": "807" },
    { "id": "peugeot-806", "brandId": "peugeot", "name": "806", "slug": "806", "series": "806" },
    { "id": "peugeot-bipper", "brandId": "peugeot", "name": "Bipper", "slug": "bipper", "series": "Bipper" },
    { "id": "peugeot-ion", "brandId": "peugeot", "name": "iOn", "slug": "ion", "series": "iOn" },
    { "id": "peugeot-rcz", "brandId": "peugeot", "name": "RCZ", "slug": "rcz", "series": "RCZ" },
    { "id": "peugeot-boxer-1", "brandId": "peugeot", "name": "Boxer I", "slug": "boxer-1", "series": "Boxer" },
    { "id": "peugeot-boxer-2", "brandId": "peugeot", "name": "Boxer II", "slug": "boxer-2", "series": "Boxer" },
    { "id": "peugeot-expert-1", "brandId": "peugeot", "name": "Expert I", "slug": "expert-1", "series": "Expert" },
    { "id": "peugeot-expert-2", "brandId": "peugeot", "name": "Expert II", "slug": "expert-2", "series": "Expert" },
    { "id": "peugeot-expert-3", "brandId": "peugeot", "name": "Expert III", "slug": "expert-3", "series": "Expert" },
    { "id": "peugeot-partner-1", "brandId": "peugeot", "name": "Partner I", "slug": "partner-1", "series": "Partner" },
    { "id": "peugeot-partner-2", "brandId": "peugeot", "name": "Partner II", "slug": "partner-2", "series": "Partner" },
    { "id": "peugeot-rifter", "brandId": "peugeot", "name": "Rifter", "slug": "rifter", "series": "Rifter" },
    { "id": "peugeot-traveller", "brandId": "peugeot", "name": "Traveller", "slug": "traveller", "series": "Traveller" },
    { "id": "renault-arkana", "brandId": "renault", "name": "Arkana", "slug": "arkana", "series": "Arkana" },
    { "id": "renault-austral", "brandId": "renault", "name": "Austral", "slug": "austral", "series": "Austral" },
    { "id": "renault-captur-1", "brandId": "renault", "name": "Captur I", "slug": "captur-1", "series": "Captur" },
    { "id": "renault-captur-2", "brandId": "renault", "name": "Captur II", "slug": "captur-2", "series": "Captur" },
    { "id": "renault-clio-1", "brandId": "renault", "name": "Clio I", "slug": "clio-1", "series": "Clio" },
    { "id": "renault-clio-2", "brandId": "renault", "name": "Clio II", "slug": "clio-2", "series": "Clio", "keywords": ["RS", "1.2 16V", "1.4 16V", "1.5 dCi"] },
    { "id": "renault-clio-3", "brandId": "renault", "name": "Clio III", "slug": "clio-3", "series": "Clio", "keywords": ["RS", "GT", "1.2 16V", "1.2 TCE", "1.5 dCi", "K9K"] },
    { "id": "renault-clio-4", "brandId": "renault", "name": "Clio IV", "slug": "clio-4", "series": "Clio", "keywords": ["RS", "GT", "0.9 TCE", "1.2 TCE", "1.5 dCi", "K9K"] },
    { "id": "renault-clio-5", "brandId": "renault", "name": "Clio V", "slug": "clio-5", "series": "Clio", "keywords": ["E-Tech", "Hybrid", "1.0 TCE"] },
    { "id": "renault-espace-3", "brandId": "renault", "name": "Espace III", "slug": "espace-3", "series": "Espace" },
    { "id": "renault-espace-4", "brandId": "renault", "name": "Espace IV", "slug": "espace-4", "series": "Espace" },
    { "id": "renault-espace-5", "brandId": "renault", "name": "Espace V", "slug": "espace-5", "series": "Espace" },
    { "id": "renault-espace-6", "brandId": "renault", "name": "Espace VI", "slug": "espace-6", "series": "Espace" },
    { "id": "renault-fluence", "brandId": "renault", "name": "Fluence", "slug": "fluence", "series": "Fluence" },
    { "id": "renault-kadjar", "brandId": "renault", "name": "Kadjar", "slug": "kadjar", "series": "Kadjar" },
    { "id": "renault-latitude", "brandId": "renault", "name": "Latitude", "slug": "latitude", "series": "Latitude" },
    { "id": "renault-rafale", "brandId": "renault", "name": "Rafale", "slug": "rafale", "series": "Rafale" },
    { "id": "renault-safrane", "brandId": "renault", "name": "Safrane", "slug": "safrane", "series": "Safrane" },
    { "id": "renault-velsatis", "brandId": "renault", "name": "Vel Satis", "slug": "velsatis", "series": "Vel Satis" },
    { "id": "renault-wind", "brandId": "renault", "name": "Wind", "slug": "wind", "series": "Wind" },
    { "id": "renault-twizy", "brandId": "renault", "name": "Twizy", "slug": "twizy", "series": "Twizy" },
    { "id": "renault-alaskan", "brandId": "renault", "name": "Alaskan", "slug": "alaskan", "series": "Pickup" },
    { "id": "renault-express", "brandId": "renault", "name": "Express", "slug": "express", "series": "Van" },
    { "id": "renault-kangoo-1", "brandId": "renault", "name": "Kangoo I", "slug": "kangoo-1", "series": "Kangoo" },
    { "id": "renault-kangoo-2", "brandId": "renault", "name": "Kangoo II", "slug": "kangoo-2", "series": "Kangoo" },
    { "id": "renault-kangoo-3", "brandId": "renault", "name": "Kangoo III", "slug": "kangoo-3", "series": "Kangoo" },
    { "id": "renault-koleos", "brandId": "renault", "name": "Koleos", "slug": "koleos", "series": "Koleos" },
    { "id": "renault-laguna-1", "brandId": "renault", "name": "Laguna I", "slug": "laguna-1", "series": "Laguna" },
    { "id": "renault-laguna-2", "brandId": "renault", "name": "Laguna II", "slug": "laguna-2", "series": "Laguna" },
    { "id": "renault-laguna-3", "brandId": "renault", "name": "Laguna III", "slug": "laguna-3", "series": "Laguna" },
    { "id": "renault-master-2", "brandId": "renault", "name": "Master II", "slug": "master-2", "series": "Master" },
    { "id": "renault-master-3", "brandId": "renault", "name": "Master III", "slug": "master-3", "series": "Master" },
    { "id": "renault-megane-1", "brandId": "renault", "name": "Megane I", "slug": "megane-1", "series": "Megane", "keywords": ["Classic", "Coach", "Scenic", "1.4 16V", "1.6 16V", "1.9 dTi", "1.9 dCi"] },
    { "id": "renault-megane-2", "brandId": "renault", "name": "Megane II", "slug": "megane-2", "series": "Megane", "keywords": ["Kombi", "Sedan", "CC", "RS", "1.4 16V", "1.6 16V", "1.5 dCi", "1.9 dCi", "K4M", "K9K", "F9Q"] },
    { "id": "renault-megane-3", "brandId": "renault", "name": "Megane III", "slug": "megane-3", "series": "Megane", "keywords": ["Coupe", "Grandtour", "RS", "GT", "1.5 dCi", "1.6 dCi", "1.4 TCE", "2.0 dCi", "K9K", "R9M", "M9R"] },
    { "id": "renault-megane-4", "brandId": "renault", "name": "Megane IV", "slug": "megane-4", "series": "Megane", "keywords": ["Grandtour", "RS", "GT", "1.3 TCE", "1.5 dCi", "1.6 dCi"] },
    { "id": "renault-megane-etron", "brandId": "renault", "name": "Megane E-Tech", "slug": "megane-etron", "series": "Megane", "keywords": ["Electric", "EV60"] },
    { "id": "renault-modus", "brandId": "renault", "name": "Modus", "slug": "modus", "series": "Modus" },
    { "id": "renault-scenic-1", "brandId": "renault", "name": "Scénic I", "slug": "scenic-1", "series": "Scénic" },
    { "id": "renault-scenic-2", "brandId": "renault", "name": "Scénic II", "slug": "scenic-2", "series": "Scénic" },
    { "id": "renault-scenic-3", "brandId": "renault", "name": "Scénic III", "slug": "scenic-3", "series": "Scénic" },
    { "id": "renault-scenic-4", "brandId": "renault", "name": "Scénic IV", "slug": "scenic-4", "series": "Scénic" },
    { "id": "renault-talisman", "brandId": "renault", "name": "Talisman", "slug": "talisman", "series": "Talisman" },
    { "id": "renault-thalia", "brandId": "renault", "name": "Thalia", "slug": "thalia", "series": "Thalia" },
    { "id": "renault-trafic-2", "brandId": "renault", "name": "Trafic II", "slug": "trafic-2", "series": "Trafic" },
    { "id": "renault-trafic-3", "brandId": "renault", "name": "Trafic III", "slug": "trafic-3", "series": "Trafic" },
    { "id": "renault-twingo-1", "brandId": "renault", "name": "Twingo I", "slug": "twingo-1", "series": "Twingo" },
    { "id": "renault-twingo-2", "brandId": "renault", "name": "Twingo II", "slug": "twingo-2", "series": "Twingo" },
    { "id": "renault-twingo-3", "brandId": "renault", "name": "Twingo III", "slug": "twingo-3", "series": "Twingo" },
    { "id": "renault-zoe", "brandId": "renault", "name": "Zoe", "slug": "zoe", "series": "Zoe" },
    { "id": "dacia-dokker", "brandId": "dacia", "name": "Dokker", "slug": "dokker", "series": "Dokker" },
    { "id": "dacia-duster-1", "brandId": "dacia", "name": "Duster I", "slug": "duster-1", "series": "Duster", "keywords": ["1.5 dCi", "1.6 16V", "4x4"] },
    { "id": "dacia-duster-2", "brandId": "dacia", "name": "Duster II", "slug": "duster-2", "series": "Duster", "keywords": ["1.5 dCi", "1.3 TCE", "4x4"] },
    { "id": "dacia-duster-3", "brandId": "dacia", "name": "Duster III", "slug": "duster-3", "series": "Duster" },
    { "id": "dacia-jogger", "brandId": "dacia", "name": "Jogger", "slug": "jogger", "series": "Jogger" },
    { "id": "dacia-lodgy", "brandId": "dacia", "name": "Lodgy", "slug": "lodgy", "series": "Lodgy", "keywords": ["Stepway", "1.5 DCI", "TCe"] },
    { "id": "dacia-logan-1", "brandId": "dacia", "name": "Logan I", "slug": "logan-1", "series": "Logan", "keywords": ["MCV", "1.4 MPI", "1.5 dCi"] },
    { "id": "dacia-logan-2", "brandId": "dacia", "name": "Logan II", "slug": "logan-2", "series": "Logan", "keywords": ["MCV", "0.9 TCE", "1.5 dCi"] },
    { "id": "dacia-logan-3", "brandId": "dacia", "name": "Logan III", "slug": "logan-3", "series": "Logan" },
    { "id": "dacia-sandero-1", "brandId": "dacia", "name": "Sandero I", "slug": "sandero-1", "series": "Sandero", "keywords": ["Stepway", "1.4 MPI", "1.5 dCi"] },
    { "id": "dacia-sandero-2", "brandId": "dacia", "name": "Sandero II", "slug": "sandero-2", "series": "Sandero", "keywords": ["Stepway", "0.9 TCE", "1.5 dCi"] },
    { "id": "dacia-sandero-3", "brandId": "dacia", "name": "Sandero III", "slug": "sandero-3", "series": "Sandero" },
    { "id": "dacia-spring", "brandId": "dacia", "name": "Spring", "slug": "spring", "series": "Spring" },
    { "id": "dacia-logan-pickup", "brandId": "dacia", "name": "Logan Pick-up", "slug": "logan-pickup", "series": "Logan" },
    { "id": "dacia-solenza", "brandId": "dacia", "name": "Solenza", "slug": "solenza", "series": "Solenza" },
    { "id": "dacia-nova", "brandId": "dacia", "name": "Nova / SupeRNova", "slug": "nova", "series": "Nova" },
    { "id": "ds-3", "brandId": "ds", "name": "DS 3 / DS 3 Crossback", "slug": "ds3", "series": "DS 3" },
    { "id": "ds-4", "brandId": "ds", "name": "DS 4 / DS 4 Crossback", "slug": "ds4", "series": "DS 4" },
    { "id": "ds-7", "brandId": "ds", "name": "DS 7 Crossback", "slug": "ds7", "series": "DS 7" },
    { "id": "ds-9", "brandId": "ds", "name": "DS 9", "slug": "ds9", "series": "DS 9" }
];
