import { Model } from './types';

export const otherBrandsModels: Model[] = [
    { "id": "alfa-romeo-145", "brandId": "alfa-romeo", "name": "145", "slug": "145", "series": "145" },
    { "id": "alfa-romeo-146", "brandId": "alfa-romeo", "name": "146", "slug": "146", "series": "146" },
    { "id": "alfa-romeo-147", "brandId": "alfa-romeo", "name": "147", "slug": "147", "series": "147", "keywords": ["1.6 TS", "1.9 JTD", "GTA"] },
    { "id": "alfa-romeo-156", "brandId": "alfa-romeo", "name": "156", "slug": "156", "series": "156", "keywords": ["1.9 JTD", "2.4 JTD", "TS", "GTA"] },
    { "id": "alfa-romeo-159", "brandId": "alfa-romeo", "name": "159", "slug": "159", "series": "159", "keywords": ["1.9 JTDm", "2.4 JTDm", "TBi"] },
    { "id": "alfa-romeo-166", "brandId": "alfa-romeo", "name": "166", "slug": "166", "series": "166" },
    { "id": "alfa-romeo-brera", "brandId": "alfa-romeo", "name": "Brera", "slug": "brera", "series": "Brera" },
    { "id": "alfa-romeo-giulia", "brandId": "alfa-romeo", "name": "Giulia", "slug": "giulia", "series": "Giulia" },
    { "id": "alfa-romeo-giulietta", "brandId": "alfa-romeo", "name": "Giulietta", "slug": "giulietta", "series": "Giulietta", "keywords": ["Quadrifoglio", "1.4 TB", "1.6 JTDm", "2.0 JTDm"] },
    { "id": "alfa-romeo-mito", "brandId": "alfa-romeo", "name": "MiTo", "slug": "mito", "series": "MiTo", "keywords": ["Quadrifoglio", "1.3 JTDm"] },
    { "id": "alfa-romeo-stelvio", "brandId": "alfa-romeo", "name": "Stelvio", "slug": "stelvio", "series": "Stelvio" },
    { "id": "alfa-romeo-tonale", "brandId": "alfa-romeo", "name": "Tonale", "slug": "tonale", "series": "Tonale" },
    { "id": "alfa-romeo-33", "brandId": "alfa-romeo", "name": "33", "slug": "33", "series": "33" },
    { "id": "alfa-romeo-4c", "brandId": "alfa-romeo", "name": "4C", "slug": "4c", "series": "4C" },
    { "id": "alfa-romeo-75", "brandId": "alfa-romeo", "name": "75", "slug": "75", "series": "75" },
    { "id": "alfa-romeo-8c", "brandId": "alfa-romeo", "name": "8C", "slug": "8c", "series": "8C" },
    { "id": "alfa-romeo-gt", "brandId": "alfa-romeo", "name": "GT", "slug": "gt", "series": "GT" },
    { "id": "alfa-romeo-gtv", "brandId": "alfa-romeo", "name": "GTV / Spider", "slug": "gtv", "series": "GTV" },
    { "id": "alfa-romeo-junior", "brandId": "alfa-romeo", "name": "Junior", "slug": "junior", "series": "Junior" },
    { "id": "alfa-romeo-spider", "brandId": "alfa-romeo", "name": "Spider", "slug": "spider", "series": "Spider" },
    { "id": "bmw-1-e81", "brandId": "bmw", "name": "(E81)", "slug": "1-e81", "series": "1-es sorozat" },
    { "id": "bmw-1-e82", "brandId": "bmw", "name": "(E82)", "slug": "1-e82", "series": "1-es sorozat" },
    { "id": "bmw-1-e87", "brandId": "bmw", "name": "(E87)", "slug": "1-e87", "series": "1-es sorozat" },
    { "id": "bmw-1-e88", "brandId": "bmw", "name": "(E88)", "slug": "1-e88", "series": "1-es sorozat" },
    { "id": "bmw-1-f20", "brandId": "bmw", "name": "(F20)", "slug": "1-f20", "series": "1-es sorozat" },
    { "id": "bmw-1-f21", "brandId": "bmw", "name": "(F21)", "slug": "1-f21", "series": "1-es sorozat" },
    { "id": "bmw-1-f40", "brandId": "bmw", "name": "(F40)", "slug": "1-f40", "series": "1-es sorozat" },
    { "id": "bmw-2-f22", "brandId": "bmw", "name": "(F22)", "slug": "2-f22", "series": "2-es sorozat" },
    { "id": "bmw-2-f23", "brandId": "bmw", "name": "(F23)", "slug": "2-f23", "series": "2-es sorozat" },
    { "id": "bmw-2-f44", "brandId": "bmw", "name": "Gran Coupé (F44)", "slug": "2-f44", "series": "2-es sorozat" },
    { "id": "bmw-2-f45", "brandId": "bmw", "name": "Active Tourer (F45)", "slug": "2-f45", "series": "2-es sorozat", "keywords": ["Active Tourer", "F45", "BMW 2", "218d", "216d"] },
    { "id": "bmw-2-f46", "brandId": "bmw", "name": "Gran Tourer (F46)", "slug": "2-f46", "series": "2-es sorozat", "keywords": ["Gran Tourer", "F46", "BMW 2", "218d", "220d"] },
    { "id": "bmw-3-e36", "brandId": "bmw", "name": "(E36)", "slug": "3-e36", "series": "3-as sorozat", "keywords": ["E36", "316i", "318is", "320i", "325tds", "M3", "M43", "M44", "M50", "M52", "M41", "M51"] },
    { "id": "bmw-3-e46", "brandId": "bmw", "name": "(E46)", "slug": "3-e46", "series": "3-as sorozat", "keywords": ["E46", "316i", "318d", "320d", "330d", "330i", "M3", "M43", "N42", "N46", "M47", "M54", "M57", "M57N"] },
    { "id": "bmw-3-e90", "brandId": "bmw", "name": "(E90)", "slug": "3-e90", "series": "3-as sorozat", "keywords": ["E90", "318d", "320d", "M3"] },
    { "id": "bmw-3-e91", "brandId": "bmw", "name": "(E91)", "slug": "3-e91", "series": "3-as sorozat", "keywords": ["E91", "Touring", "320d"] },
    { "id": "bmw-3-e92", "brandId": "bmw", "name": "(E92)", "slug": "3-e92", "series": "3-as sorozat", "keywords": ["E92", "Coupe", "335i"] },
    { "id": "bmw-3-e93", "brandId": "bmw", "name": "(E93)", "slug": "3-e93", "series": "3-as sorozat", "keywords": ["E93", "Cabrio"] },
    { "id": "bmw-3-f30", "brandId": "bmw", "name": "(F30)", "slug": "3-f30", "series": "3-as sorozat", "keywords": ["F30", "318d", "320d"] },
    { "id": "bmw-3-f31", "brandId": "bmw", "name": "(F31)", "slug": "3-f31", "series": "3-as sorozat", "keywords": ["F31", "Touring"] },
    { "id": "bmw-3-f34", "brandId": "bmw", "name": "GT (F34)", "slug": "3-f34", "series": "3-as sorozat", "keywords": ["F34", "Gran Turismo"] },
    { "id": "bmw-3-g20", "brandId": "bmw", "name": "(G20)", "slug": "3-g20", "series": "3-as sorozat", "keywords": ["G20"] },
    { "id": "bmw-3-g21", "brandId": "bmw", "name": "(G21)", "slug": "3-g21", "series": "3-as sorozat", "keywords": ["G21"] },
    { "id": "bmw-4-f32", "brandId": "bmw", "name": "(F32)", "slug": "4-f32", "series": "4-as sorozat" },
    { "id": "bmw-4-f33", "brandId": "bmw", "name": "(F33)", "slug": "4-f33", "series": "4-as sorozat" },
    { "id": "bmw-4-f36", "brandId": "bmw", "name": "Gran Coupe (F36)", "slug": "4-f36", "series": "4-as sorozat" },
    { "id": "bmw-4-g22", "brandId": "bmw", "name": "(G22)", "slug": "4-g22", "series": "4-es sorozat" },
    { "id": "bmw-4-g23", "brandId": "bmw", "name": "(G23)", "slug": "4-g23", "series": "4-es sorozat" },
    { "id": "bmw-4-g26", "brandId": "bmw", "name": "(G26)", "slug": "4-g26", "series": "4-es sorozat" },
    { "id": "bmw-5-g30", "brandId": "bmw", "name": "(G30)", "slug": "5-g30", "series": "5-ös sorozat" },
    { "id": "bmw-5-g31", "brandId": "bmw", "name": "(G31)", "slug": "5-g31", "series": "5-ös sorozat" },
    { "id": "bmw-5-g60", "brandId": "bmw", "name": "(G60)", "slug": "5-g60", "series": "5-ös sorozat" },
    { "id": "bmw-5-g61", "brandId": "bmw", "name": "(G61)", "slug": "5-g61", "series": "5-ös sorozat" },
    { "id": "bmw-6-e63", "brandId": "bmw", "name": "(E63)", "slug": "6-e63", "series": "6-os sorozat", "keywords": ["E63", "630i", "645i"] },
    { "id": "bmw-6-e64", "brandId": "bmw", "name": "(E64)", "slug": "6-e64", "series": "6-os sorozat", "keywords": ["E64", "Cabrio"] },
    { "id": "bmw-6-f12", "brandId": "bmw", "name": "(F12)", "slug": "6-f12", "series": "6-os sorozat", "keywords": ["F12", "Cabrio"] },
    { "id": "bmw-6-f13", "brandId": "bmw", "name": "(F13)", "slug": "6-f13", "series": "6-os sorozat", "keywords": ["F13", "Coupe"] },
    { "id": "bmw-6-f06", "brandId": "bmw", "name": "Gran Coupe (F06)", "slug": "6-f06", "series": "6-os sorozat", "keywords": ["F06", "Gran Coupe"] },
    { "id": "bmw-6-g32", "brandId": "bmw", "name": "GT (G32)", "slug": "6-g32", "series": "6-os sorozat" },
    { "id": "bmw-7-e38", "brandId": "bmw", "name": "(E38)", "slug": "7-e38", "series": "7-es sorozat", "keywords": ["E38", "725tds", "730d", "740d", "740i", "750i"] },
    { "id": "bmw-7-e65", "brandId": "bmw", "name": "(E65)", "slug": "7-e65", "series": "7-es sorozat", "keywords": ["E65", "730d", "740d"] },
    { "id": "bmw-7-e66", "brandId": "bmw", "name": "(E66)", "slug": "7-e66", "series": "7-es sorozat", "keywords": ["E66", "Long"] },
    { "id": "bmw-7-f01", "brandId": "bmw", "name": "(F01)", "slug": "7-f01", "series": "7-es sorozat", "keywords": ["F01", "730d", "740d"] },
    { "id": "bmw-7-f02", "brandId": "bmw", "name": "(F02)", "slug": "7-f02", "series": "7-es sorozat", "keywords": ["F02", "Long"] },
    { "id": "bmw-7-g11", "brandId": "bmw", "name": "(G11)", "slug": "7-g11", "series": "7-es sorozat", "keywords": ["G11", "730d", "740d"] },
    { "id": "bmw-7-g12", "brandId": "bmw", "name": "(G12)", "slug": "7-g12", "series": "7-es sorozat", "keywords": ["G12", "Long"] },
    { "id": "bmw-7-g70", "brandId": "bmw", "name": "(G70)", "slug": "7-g70", "series": "7-es sorozat" },
    { "id": "bmw-8-e31", "brandId": "bmw", "name": "(E31)", "slug": "8-e31", "series": "8-as sorozat" },
    { "id": "bmw-8-g14", "brandId": "bmw", "name": "(G14)", "slug": "8-g14", "series": "8-as sorozat" },
    { "id": "bmw-8-g15", "brandId": "bmw", "name": "(G15)", "slug": "8-g15", "series": "8-as sorozat" },
    { "id": "bmw-8-g16", "brandId": "bmw", "name": "(G16)", "slug": "8-g16", "series": "8-as sorozat" },
    { "id": "bmw-x1-e84", "brandId": "bmw", "name": "X1 (E84)", "slug": "x1-e84", "series": "X széria", "keywords": ["E84", "18d", "20d"] },
    { "id": "bmw-x1-f48", "brandId": "bmw", "name": "X1 (F48)", "slug": "x1-f48", "series": "X széria", "keywords": ["F48", "18d", "20d"] },
    { "id": "bmw-x1-u11", "brandId": "bmw", "name": "X1 (U11)", "slug": "x1-u11", "series": "X széria" },
    { "id": "bmw-x2-f39", "brandId": "bmw", "name": "X2 (F39)", "slug": "x2-f39", "series": "X széria" },
    { "id": "bmw-x3-e83", "brandId": "bmw", "name": "X3 (E83)", "slug": "x3-e83", "series": "X széria", "keywords": ["E83", "2.0d", "3.0d"] },
    { "id": "bmw-x3-f25", "brandId": "bmw", "name": "X3 (F25)", "slug": "x3-f25", "series": "X széria", "keywords": ["F25", "20d", "30d"] },
    { "id": "bmw-x3-g01", "brandId": "bmw", "name": "X3 (G01)", "slug": "x3-g01", "series": "X széria", "keywords": ["G01", "20d", "30d"] },
    { "id": "bmw-x4-f26", "brandId": "bmw", "name": "X4 (F26)", "slug": "x4-f26", "series": "X széria" },
    { "id": "bmw-x4-g02", "brandId": "bmw", "name": "X4 (G02)", "slug": "x4-g02", "series": "X széria" },
    { "id": "bmw-x6-f16", "brandId": "bmw", "name": "X6 (F16)", "slug": "x6-f16", "series": "X széria" },
    { "id": "bmw-x6-g06", "brandId": "bmw", "name": "X6 (G06)", "slug": "x6-g06", "series": "X széria" },
    { "id": "bmw-x7-g07", "brandId": "bmw", "name": "X7 (G07)", "slug": "x7-g07", "series": "X széria" },
    { "id": "bmw-z3-coupe", "brandId": "bmw", "name": "Z3 Coupe (E36/8)", "slug": "z3-coupe", "series": "Z széria" },
    { "id": "bmw-z3-roadster", "brandId": "bmw", "name": "Z3 Roadster (E36/7)", "slug": "z3-roadster", "series": "Z széria" },
    { "id": "bmw-z4-e85", "brandId": "bmw", "name": "Z4 (E85)", "slug": "z4-e85", "series": "Z széria" },
    { "id": "bmw-z4-e86", "brandId": "bmw", "name": "Z4 Coupe (E86)", "slug": "z4-e86", "series": "Z széria" },
    { "id": "bmw-z4-e89", "brandId": "bmw", "name": "Z4 (E89)", "slug": "z4-e89", "series": "Z széria" },
    { "id": "bmw-z4-g29", "brandId": "bmw", "name": "Z4 (G29)", "slug": "z4-g29", "series": "Z széria" },
    { "id": "bmw-z1", "brandId": "bmw", "name": "Z1", "slug": "z1", "series": "Z széria" },
    { "id": "bmw-i3", "brandId": "bmw", "name": "i3 (I01)", "slug": "i3", "series": "i széria" },
    { "id": "bmw-i4", "brandId": "bmw", "name": "i4 (G26)", "slug": "i4", "series": "i széria" },
    { "id": "bmw-ix", "brandId": "bmw", "name": "iX (I20)", "slug": "ix", "series": "i széria" },
    { "id": "bmw-ix1", "brandId": "bmw", "name": "iX1 (U11)", "slug": "ix1", "series": "i széria" },
    { "id": "bmw-ix2", "brandId": "bmw", "name": "iX2 (U10)", "slug": "ix2", "series": "i széria" },
    { "id": "bmw-ix3", "brandId": "bmw", "name": "iX3 (G08)", "slug": "ix3", "series": "i széria" },
    { "id": "bmw-i8", "brandId": "bmw", "name": "i8 (I12/I15)", "slug": "i8", "series": "i széria" },
    { "id": "bmw-xm", "brandId": "bmw", "name": "XM (G09)", "slug": "xm", "series": "M széria" },

    { "id": "chevrolet-aveo", "brandId": "chevrolet", "name": "Aveo", "slug": "aveo", "series": "Aveo" },
    { "id": "chevrolet-captiva", "brandId": "chevrolet", "name": "Captiva", "slug": "captiva", "series": "Captiva" },
    { "id": "chevrolet-cruze", "brandId": "chevrolet", "name": "Cruze", "slug": "cruze", "series": "Cruze" },
    { "id": "chevrolet-epica", "brandId": "chevrolet", "name": "Epica", "slug": "epica", "series": "Epica" },
    { "id": "chevrolet-kalos", "brandId": "chevrolet", "name": "Kalos", "slug": "kalos", "series": "Kalos" },
    { "id": "chevrolet-lacetti", "brandId": "chevrolet", "name": "Lacetti", "slug": "lacetti", "series": "Lacetti" },
    { "id": "chevrolet-matiz", "brandId": "chevrolet", "name": "Matiz", "slug": "matiz", "series": "Matiz" },
    { "id": "chevrolet-orlando", "brandId": "chevrolet", "name": "Orlando", "slug": "orlando", "series": "Orlando" },
    { "id": "chevrolet-spark", "brandId": "chevrolet", "name": "Spark", "slug": "spark", "series": "Spark" },
    { "id": "chevrolet-trax", "brandId": "chevrolet", "name": "Trax", "slug": "trax", "series": "Trax" },
    { "id": "chevrolet-camaro", "brandId": "chevrolet", "name": "Camaro", "slug": "camaro", "series": "Camaro" },
    { "id": "chevrolet-corvette", "brandId": "chevrolet", "name": "Corvette", "slug": "corvette", "series": "Corvette" },
    { "id": "chevrolet-hhr", "brandId": "chevrolet", "name": "HHR", "slug": "hhr", "series": "HHR" },
    { "id": "chevrolet-silverado", "brandId": "chevrolet", "name": "Silverado", "slug": "silverado", "series": "Silverado" },
    { "id": "chevrolet-tahoe", "brandId": "chevrolet", "name": "Tahoe", "slug": "tahoe", "series": "Tahoe" },
    { "id": "chevrolet-suburban", "brandId": "chevrolet", "name": "Suburban", "slug": "suburban", "series": "Suburban" },
    { "id": "dodge-caliber", "brandId": "dodge", "name": "Caliber", "slug": "caliber", "series": "Caliber" },
    { "id": "dodge-journey", "brandId": "dodge", "name": "Journey", "slug": "journey", "series": "Journey" },
    { "id": "dodge-ram", "brandId": "dodge", "name": "RAM", "slug": "ram", "series": "RAM" },
    { "id": "dodge-avenger", "brandId": "dodge", "name": "Avenger", "slug": "avenger", "series": "Avenger" },
    { "id": "dodge-challenger", "brandId": "dodge", "name": "Challenger", "slug": "challenger", "series": "Challenger" },
    { "id": "dodge-charger", "brandId": "dodge", "name": "Charger", "slug": "charger", "series": "Charger" },
    { "id": "dodge-dakota", "brandId": "dodge", "name": "Dakota", "slug": "dakota", "series": "Dakota" },
    { "id": "dodge-durango", "brandId": "dodge", "name": "Durango", "slug": "durango", "series": "Durango" },
    { "id": "dodge-grand-caravan", "brandId": "dodge", "name": "Grand Caravan", "slug": "grand-caravan", "series": "Caravan" },
    { "id": "dodge-magnum", "brandId": "dodge", "name": "Magnum", "slug": "magnum", "series": "Magnum" },
    { "id": "dodge-neon", "brandId": "dodge", "name": "Neon", "slug": "neon", "series": "Neon" },
    { "id": "dodge-nitro", "brandId": "dodge", "name": "Nitro", "slug": "nitro", "series": "Nitro" },
    { "id": "dodge-stealth", "brandId": "dodge", "name": "Stealth", "slug": "stealth", "series": "Stealth" },
    { "id": "dodge-viper", "brandId": "dodge", "name": "Viper", "slug": "viper", "series": "Viper" },
    { "id": "fiat-500", "brandId": "fiat", "name": "500", "slug": "500", "series": "500", "keywords": ["C", "L", "X", "Abarth", "Multijet", "1.2", "0.9 TwinAir"] },
    { "id": "fiat-500x", "brandId": "fiat", "name": "500X", "slug": "500x", "series": "500" },
    { "id": "fiat-500l", "brandId": "fiat", "name": "500L", "slug": "500l", "series": "500" },
    { "id": "fiat-bravo-2", "brandId": "fiat", "name": "Bravo II", "slug": "bravo-2", "series": "Bravo", "keywords": ["Multijet", "1.4 T-Jet"] },
    { "id": "fiat-doblo-1", "brandId": "fiat", "name": "Doblo I", "slug": "doblo-1", "series": "Doblo", "keywords": ["1.3 Multijet", "1.9 JTD"] },
    { "id": "fiat-doblo-2", "brandId": "fiat", "name": "Doblo II", "slug": "doblo-2", "series": "Doblo", "keywords": ["Multijet"] },
    { "id": "fiat-doblo-3", "brandId": "fiat", "name": "Doblo III", "slug": "doblo-3", "series": "Doblo" },
    { "id": "fiat-ducato-2", "brandId": "fiat", "name": "Ducato II", "slug": "ducato-2", "series": "Ducato", "keywords": ["2.3 JTD", "2.8 JTD"] },
    { "id": "fiat-ducato-3", "brandId": "fiat", "name": "Ducato III", "slug": "ducato-3", "series": "Ducato", "keywords": ["Multijet"] },
    { "id": "fiat-fiorino", "brandId": "fiat", "name": "Fiorino", "slug": "fiorino", "series": "Fiorino" },
    { "id": "fiat-freemont", "brandId": "fiat", "name": "Freemont", "slug": "freemont", "series": "Freemont" },
    { "id": "fiat-grande-punto", "brandId": "fiat", "name": "Grande Punto / Punto Evo", "slug": "grande-punto", "series": "Punto" },
    { "id": "fiat-idea", "brandId": "fiat", "name": "Idea", "slug": "idea", "series": "Idea" },
    { "id": "fiat-multipla", "brandId": "fiat", "name": "Multipla", "slug": "multipla", "series": "Multipla" },
    { "id": "fiat-panda-2", "brandId": "fiat", "name": "Panda II (169)", "slug": "panda-2", "series": "Panda" },
    { "id": "fiat-panda-3", "brandId": "fiat", "name": "Panda III (319)", "slug": "panda-3", "series": "Panda" },
    { "id": "fiat-punto-2", "brandId": "fiat", "name": "Punto II (188)", "slug": "punto-2", "series": "Punto" },
    { "id": "fiat-qubo", "brandId": "fiat", "name": "Qubo", "slug": "qubo", "series": "Qubo" },
    { "id": "fiat-scudo-1", "brandId": "fiat", "name": "Scudo I", "slug": "scudo-1", "series": "Scudo" },
    { "id": "fiat-scudo-2", "brandId": "fiat", "name": "Scudo II", "slug": "scudo-2", "series": "Scudo" },
    { "id": "fiat-stilo", "brandId": "fiat", "name": "Stilo", "slug": "stilo", "series": "Stilo" },
    { "id": "fiat-talento", "brandId": "fiat", "name": "Talento", "slug": "talento", "series": "Talento" },
    { "id": "fiat-tipo", "brandId": "fiat", "name": "Tipo (356)", "slug": "tipo", "series": "Tipo" },
    { "id": "fiat-ulysse", "brandId": "fiat", "name": "Ulysse", "slug": "ulysse", "series": "Ulysse" },
    { "id": "fiat-124-spider", "brandId": "fiat", "name": "124 Spider", "slug": "124-spider", "series": "124" },
    { "id": "fiat-barchetta", "brandId": "fiat", "name": "Barchetta", "slug": "barchetta", "series": "Barchetta" },
    { "id": "fiat-cinquecento", "brandId": "fiat", "name": "Cinquecento", "slug": "cinquecento", "series": "Cinquecento" },
    { "id": "fiat-seicento", "brandId": "fiat", "name": "Seicento", "slug": "seicento", "series": "Seicento" },
    { "id": "fiat-croma", "brandId": "fiat", "name": "Croma", "slug": "croma", "series": "Croma" },
    { "id": "fiat-fullback", "brandId": "fiat", "name": "Fullback", "slug": "fullback", "series": "Fullback" },
    { "id": "fiat-linea", "brandId": "fiat", "name": "Linea", "slug": "linea", "series": "Linea" },
    { "id": "fiat-marea", "brandId": "fiat", "name": "Marea", "slug": "marea", "series": "Marea" },
    { "id": "fiat-sedici", "brandId": "fiat", "name": "Sedici", "slug": "sedici", "series": "Sedici" },
    { "id": "fiat-uno", "brandId": "fiat", "name": "Uno", "slug": "uno", "series": "Uno" },
    { "id": "ford-b-max", "brandId": "ford", "name": "B-Max", "slug": "b-max", "series": "B-Max" },
    { "id": "ford-c-max-1", "brandId": "ford", "name": "C-Max / Focus C-Max I", "slug": "c-max-1", "series": "C-Max" },
    { "id": "ford-c-max-2", "brandId": "ford", "name": "C-Max II", "slug": "c-max-2", "series": "C-Max" },
    { "id": "ford-courier", "brandId": "ford", "name": "Tourneo/Transit Courier", "slug": "courier", "series": "Courier" },
    { "id": "ford-ecosport", "brandId": "ford", "name": "EcoSport", "slug": "ecosport", "series": "EcoSport" },
    { "id": "ford-fiesta-4", "brandId": "ford", "name": "Fiesta IV", "slug": "fiesta-4", "series": "Fiesta" },
    { "id": "ford-fiesta-5", "brandId": "ford", "name": "Fiesta V (JH/JD)", "slug": "fiesta-5", "series": "Fiesta", "keywords": ["ST", "1.3", "1.4 TDCI"] },
    { "id": "ford-fiesta-6", "brandId": "ford", "name": "Fiesta VI", "slug": "fiesta-6", "series": "Fiesta", "keywords": ["ST", "1.25", "1.4 TDCI", "1.6 TDCI"] },
    { "id": "ford-fiesta-7", "brandId": "ford", "name": "Fiesta VII", "slug": "fiesta-7", "series": "Fiesta", "keywords": ["ST", "EcoBoost"] },
    { "id": "ford-focus-1", "brandId": "ford", "name": "Focus I", "slug": "focus-1", "series": "Focus", "keywords": ["ST170", "RS", "1.6 16V", "1.8 TDDI", "1.8 TDCI"] },
    { "id": "ford-focus-2", "brandId": "ford", "name": "Focus II", "slug": "focus-2", "series": "Focus", "keywords": ["ST", "RS", "1.6 TDCI", "1.6 16V"] },
    { "id": "ford-focus-3", "brandId": "ford", "name": "Focus III", "slug": "focus-3", "series": "Focus", "keywords": ["ST", "RS", "EcoBoost", "1.6 TDCI"] },
    { "id": "ford-focus-4", "brandId": "ford", "name": "Focus IV", "slug": "focus-4", "series": "Focus", "keywords": ["ST", "EcoBoost", "Mild Hybrid"] },
    { "id": "ford-fusion", "brandId": "ford", "name": "Fusion", "slug": "fusion", "series": "Fusion" },
    { "id": "ford-galaxy-1", "brandId": "ford", "name": "Galaxy I", "slug": "galaxy-1", "series": "Galaxy" },
    { "id": "ford-galaxy-2", "brandId": "ford", "name": "Galaxy II", "slug": "galaxy-2", "series": "Galaxy" },
    { "id": "ford-galaxy-3", "brandId": "ford", "name": "Galaxy III", "slug": "galaxy-3", "series": "Galaxy" },
    { "id": "ford-ka-1", "brandId": "ford", "name": "Ka I", "slug": "ka-1", "series": "Ka" },
    { "id": "ford-ka-2", "brandId": "ford", "name": "Ka II / Ka+", "slug": "ka-2", "series": "Ka" },
    { "id": "ford-kuga-1", "brandId": "ford", "name": "Kuga I", "slug": "kuga-1", "series": "Kuga" },
    { "id": "ford-kuga-2", "brandId": "ford", "name": "Kuga II", "slug": "kuga-2", "series": "Kuga" },
    { "id": "ford-kuga-3", "brandId": "ford", "name": "Kuga III", "slug": "kuga-3", "series": "Kuga" },
    { "id": "ford-mondeo-mk2", "brandId": "ford", "name": "Mondeo II (Mk2)", "slug": "mondeo-mk2", "series": "Mondeo" },
    { "id": "ford-mondeo-mk3", "brandId": "ford", "name": "Mondeo III (Mk3)", "slug": "mondeo-mk3", "series": "Mondeo" },
    { "id": "ford-mondeo-mk4", "brandId": "ford", "name": "Mondeo IV (Mk4)", "slug": "mondeo-mk4", "series": "Mondeo" },
    { "id": "ford-mondeo-mk5", "brandId": "ford", "name": "Mondeo V (Mk5)", "slug": "mondeo-mk5", "series": "Mondeo" },
    { "id": "ford-mustang", "brandId": "ford", "name": "Mustang", "slug": "mustang", "series": "Mustang" },
    { "id": "ford-mustang-mache", "brandId": "ford", "name": "Mustang Mach-E", "slug": "mustang-mache", "series": "Mustang" },
    { "id": "ford-puma", "brandId": "ford", "name": "Puma", "slug": "puma", "series": "Puma" },
    { "id": "ford-ranger", "brandId": "ford", "name": "Ranger", "slug": "ranger", "series": "Ranger" },
    { "id": "ford-s-max-1", "brandId": "ford", "name": "S-Max I", "slug": "s-max-1", "series": "S-Max" },
    { "id": "ford-s-max-2", "brandId": "ford", "name": "S-Max II", "slug": "s-max-2", "series": "S-Max" },
    { "id": "ford-tourneo-connect", "brandId": "ford", "name": "Tourneo / Transit Connect", "slug": "tourneo-connect", "series": "Tourneo" },
    { "id": "ford-tourneo-custom", "brandId": "ford", "name": "Tourneo / Transit Custom", "slug": "tourneo-custom", "series": "Tourneo" },
    { "id": "ford-transit-mk6", "brandId": "ford", "name": "Transit V184/V347", "slug": "transit-mk6", "series": "Transit" },
    { "id": "ford-transit-mk8", "brandId": "ford", "name": "Transit", "slug": "transit-mk8", "series": "Transit" },
    { "id": "ford-capri", "brandId": "ford", "name": "Capri", "slug": "capri", "series": "Sport" },
    { "id": "ford-explorer", "brandId": "ford", "name": "Explorer", "slug": "explorer", "series": "SUV" },
    { "id": "ford-orion", "brandId": "ford", "name": "Orion", "slug": "orion", "series": "Orion" },
    { "id": "ford-probe", "brandId": "ford", "name": "Probe", "slug": "probe", "series": "Sport" },
    { "id": "ford-scorpio", "brandId": "ford", "name": "Scorpio", "slug": "scorpio", "series": "Scorpio" },
    { "id": "ford-sierra", "brandId": "ford", "name": "Sierra", "slug": "sierra", "series": "Sierra" },
    { "id": "ford-windstar", "brandId": "ford", "name": "Windstar", "slug": "windstar", "series": "Van" },
    { "id": "ford-bronco", "brandId": "ford", "name": "Bronco", "slug": "bronco", "series": "SUV" },
    { "id": "mb-a-w168", "brandId": "mercedes", "name": "(W168)", "slug": "a-w168", "series": "A-Class", "keywords": ["W168", "A140", "A160", "A170 CDI", "A190"] },
    { "id": "mb-a-w169", "brandId": "mercedes", "name": "(W169)", "slug": "a-w169", "series": "A-Class", "keywords": ["W169", "A150", "A170", "A180 CDI", "A200 CDI"] },
    { "id": "mb-a-w176", "brandId": "mercedes", "name": "(W176)", "slug": "a-w176", "series": "A-Class", "keywords": ["W176", "A180", "A200", "A220 CDI", "A250", "A45 AMG"] },
    { "id": "mb-a-w177", "brandId": "mercedes", "name": "(W177)", "slug": "a-w177", "series": "A-Class", "keywords": ["W177", "A180", "A200", "A250e", "A35 AMG"] },
    { "id": "mb-b-w245", "brandId": "mercedes", "name": "(W245)", "slug": "b-w245", "series": "B-Class", "keywords": ["W245", "B180 CDI", "B200 CDI", "B200 Turbo"] },
    { "id": "mb-b-w246", "brandId": "mercedes", "name": "(W246)", "slug": "b-w246", "series": "B-Class", "keywords": ["W246", "B180", "B200", "B220 CDI"] },
    { "id": "mb-b-w247", "brandId": "mercedes", "name": "(W247)", "slug": "b-w247", "series": "B-Class", "keywords": ["W247", "B180", "B200", "B250e"] },
    { "id": "mb-c-w202", "brandId": "mercedes", "name": "(W202)", "slug": "c-w202", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C230", "C240", "C250", "C280"] },
    { "id": "mb-c-w203", "brandId": "mercedes", "name": "(W203)", "slug": "c-w203", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C230", "C240", "C270", "C280", "C320", "C350", "OM611", "OM646", "OM612", "M111", "M271", "M272"] },
    { "id": "mb-c-w204", "brandId": "mercedes", "name": "(W204)", "slug": "c-w204", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C250", "C300", "C320", "C350", "C63"] },
    { "id": "mb-c-w205", "brandId": "mercedes", "name": "(W205)", "slug": "c-w205", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C250", "C300", "C350", "C400", "C43", "C63"] },
    { "id": "mb-c-w206", "brandId": "mercedes", "name": "(W206)", "slug": "c-w206", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C300", "C400", "C43", "C63"] },
    { "id": "mb-cla-c117", "brandId": "mercedes", "name": "(C117/X117)", "slug": "cla-c117", "series": "CLA" },
    { "id": "mb-cla-c118", "brandId": "mercedes", "name": "(C118/X118)", "slug": "cla-c118", "series": "CLA" },
    { "id": "mb-clk-w208", "brandId": "mercedes", "name": "(W208)", "slug": "clk-w208", "series": "CLK" },
    { "id": "mb-clk-w209", "brandId": "mercedes", "name": "(W209)", "slug": "clk-w209", "series": "CLK" },
    { "id": "mb-cls-w219", "brandId": "mercedes", "name": "(W219)", "slug": "cls-w219", "series": "CLS" },
    { "id": "mb-cls-w218", "brandId": "mercedes", "name": "(W218)", "slug": "cls-w218", "series": "CLS" },
    { "id": "mb-e-w210", "brandId": "mercedes", "name": "(W210)", "slug": "e-w210", "series": "E-Class", "keywords": ["W210", "Pápaszemes", "Béka lámpás", "E200", "E220", "E230", "E240", "E250", "E270", "E280", "E290", "E300", "E320", "E420", "E430", "E50", "E55"] },
    { "id": "mb-e-w211", "brandId": "mercedes", "name": "(W211)", "slug": "e-w211", "series": "E-Class", "keywords": ["E200", "E220", "E240", "E270", "E280", "E300", "E320", "E350", "E400", "E420", "E500", "E55", "E63", "OM646", "OM647", "OM648", "OM642", "M271", "M272"] },
    { "id": "mb-e-w212", "brandId": "mercedes", "name": "(W212)", "slug": "e-w212", "series": "E-Class", "keywords": ["E200", "E220", "E250", "E300", "E350", "E400", "E500", "E63"] },
    { "id": "mb-e-w213", "brandId": "mercedes", "name": "(W213)", "slug": "e-w213", "series": "E-Class", "keywords": ["E200", "E220", "E300", "E350", "E400", "E450", "E53", "E63"] },
    { "id": "mb-cl-c215", "brandId": "mercedes", "name": "(C215)", "slug": "cl-c215", "series": "CL" },
    { "id": "mb-cl-c216", "brandId": "mercedes", "name": "(C216)", "slug": "cl-c216", "series": "CL" },
    { "id": "mb-clc-cl203", "brandId": "mercedes", "name": "(CL203)", "slug": "clc", "series": "CLC" },
    { "id": "mb-r-w251", "brandId": "mercedes", "name": "(W251)", "slug": "r-w251", "series": "R-Class" },
    { "id": "mb-sl-r230", "brandId": "mercedes", "name": "(R230)", "slug": "sl-r230", "series": "SL" },
    { "id": "mb-sl-r231", "brandId": "mercedes", "name": "(R231)", "slug": "sl-r231", "series": "SL" },
    { "id": "mb-slc-r172", "brandId": "mercedes", "name": "(R172)", "slug": "slc", "series": "SLC" },
    { "id": "mb-slr", "brandId": "mercedes", "name": "SLR McLaren", "slug": "slr", "series": "SLR" },
    { "id": "mb-sls", "brandId": "mercedes", "name": "SLS AMG", "slug": "sls", "series": "SLS" },
    { "id": "mb-x-w470", "brandId": "mercedes", "name": "(W470)", "slug": "x-w470", "series": "X-Class" },
    { "id": "mb-eqa", "brandId": "mercedes", "name": "EQA", "slug": "eqa", "series": "EQ" },
    { "id": "mb-eqb", "brandId": "mercedes", "name": "EQB", "slug": "eqb", "series": "EQ" },
    { "id": "mb-eqc", "brandId": "mercedes", "name": "EQC", "slug": "eqc", "series": "EQ" },
    { "id": "mb-eqe", "brandId": "mercedes", "name": "EQE", "slug": "eqe", "series": "EQ" },
    { "id": "mb-eqs", "brandId": "mercedes", "name": "EQS", "slug": "eqs", "series": "EQ" },
    { "id": "mb-eqv", "brandId": "mercedes", "name": "EQV", "slug": "eqv", "series": "EQ" },
    { "id": "mb-g-class", "brandId": "mercedes", "name": "(W463)", "slug": "g-class", "series": "G-Class" },
    { "id": "mb-gl-x164", "brandId": "mercedes", "name": "(X164)", "slug": "gl-x164", "series": "GL" },
    { "id": "mb-gla-x156", "brandId": "mercedes", "name": "(X156)", "slug": "gla-x156", "series": "GLA" },
    { "id": "mb-gla-h247", "brandId": "mercedes", "name": "(H247)", "slug": "gla-h247", "series": "GLA" },
    { "id": "mb-glb-x247", "brandId": "mercedes", "name": "(X247)", "slug": "glb-x247", "series": "GLB" },
    { "id": "mb-glc-x253", "brandId": "mercedes", "name": "(X253)", "slug": "glc-x253", "series": "GLC" },
    { "id": "mb-m-w163", "brandId": "mercedes", "name": "(W163)", "slug": "m-w163", "series": "M-Class" },
    { "id": "mb-m-w164", "brandId": "mercedes", "name": "(W164)", "slug": "m-w164", "series": "M-Class" },
    { "id": "mb-m-w166", "brandId": "mercedes", "name": "(W166)", "slug": "m-w166", "series": "M-Class" },
    { "id": "mb-s-w220", "brandId": "mercedes", "name": "(W220)", "slug": "s-w220", "series": "S-Class", "keywords": ["W220", "S320 CDI", "S400 CDI", "S500", "S600"] },
    { "id": "mb-s-w221", "brandId": "mercedes", "name": "(W221)", "slug": "s-w221", "series": "S-Class", "keywords": ["W221", "S320 CDI", "S350", "S500", "S63 AMG"] },
    { "id": "mb-s-w222", "brandId": "mercedes", "name": "(W222)", "slug": "s-w222", "series": "S-Class", "keywords": ["W222", "S350d", "S400d", "S500", "S560", "S63 AMG"] },
    { "id": "mb-sls-slk-r170", "brandId": "mercedes", "name": "(R170)", "slug": "slk-r170", "series": "SLK" },
    { "id": "mb-sls-slk-r171", "brandId": "mercedes", "name": "(R171)", "slug": "slk-r171", "series": "SLK" },
    { "id": "mb-sprinter-w901", "brandId": "mercedes", "name": "Sprinter I (W901-905)", "slug": "sprinter-w901", "series": "Sprinter" },
    { "id": "mb-sprinter-w906", "brandId": "mercedes", "name": "Sprinter II (W906/NCV3)", "slug": "sprinter-w906", "series": "Sprinter" },
    { "id": "mb-sprinter-w907", "brandId": "mercedes", "name": "Sprinter III (W907/W910)", "slug": "sprinter-w907", "series": "Sprinter" },
    { "id": "mb-citan", "brandId": "mercedes", "name": "Citan", "slug": "citan", "series": "Citan" },
    { "id": "mb-vito-w638", "brandId": "mercedes", "name": "Vito / V-Osztály (W638)", "slug": "vito-w638", "series": "Vito" },
    { "id": "mb-vito-w639", "brandId": "mercedes", "name": "Vito / Viano (W639)", "slug": "vito-w639", "series": "Vito" },
    { "id": "mb-vito-w447", "brandId": "mercedes", "name": "Vito / V-Osztály (W447)", "slug": "vito-w447", "series": "Vito" },
    { "id": "opel-adam", "brandId": "opel", "name": "Adam", "slug": "adam", "series": "Adam", "keywords": ["S", "Rocks", "1.2", "1.4"] },
    { "id": "opel-agila-a", "brandId": "opel", "name": "Agila A", "slug": "agila-a", "series": "Agila", "keywords": ["1.0", "1.2 16V"] },
    { "id": "opel-agila-b", "brandId": "opel", "name": "Agila B", "slug": "agila-b", "series": "Agila", "keywords": ["1.0", "1.2", "1.3 CDTI"] },
    { "id": "opel-antara", "brandId": "opel", "name": "Antara", "slug": "antara", "series": "Antara", "keywords": ["2.0 CDTI", "2.2 CDTI"] },
    { "id": "opel-astra-f", "brandId": "opel", "name": "Astra F", "slug": "astra-f", "series": "Astra", "keywords": ["GSI", "1.4", "1.6", "1.7 TD"] },
    { "id": "opel-astra-g", "brandId": "opel", "name": "Astra G", "slug": "astra-g", "series": "Astra", "keywords": ["OPC", "1.4 16V", "1.6 16V", "1.7 DTI", "2.0 DT"] },
    { "id": "opel-astra-h", "brandId": "opel", "name": "Astra H", "slug": "astra-h", "series": "Astra", "keywords": ["OPC", "GTC", "TwinTop", "1.7 CDTI", "1.9 CDTI"] },
    { "id": "opel-astra-j", "brandId": "opel", "name": "Astra J", "slug": "astra-j", "series": "Astra", "keywords": ["OPC", "GTC", "1.7 CDTI", "1.4 Turbo"] },
    { "id": "opel-astra-k", "brandId": "opel", "name": "Astra K", "slug": "astra-k", "series": "Astra", "keywords": ["1.6 CDTI", "1.4 Turbo"] },
    { "id": "opel-astra-l", "brandId": "opel", "name": "Astra L", "slug": "astra-l", "series": "Astra" },
    { "id": "opel-combo-c", "brandId": "opel", "name": "Combo C", "slug": "combo-c", "series": "Combo" },
    { "id": "opel-combo-d", "brandId": "opel", "name": "Combo D", "slug": "combo-d", "series": "Combo" },
    { "id": "opel-combo-e", "brandId": "opel", "name": "Combo E", "slug": "combo-e", "series": "Combo" },
    { "id": "opel-corsa-b", "brandId": "opel", "name": "Corsa B", "slug": "corsa-b", "series": "Corsa" },
    { "id": "opel-corsa-c", "brandId": "opel", "name": "Corsa C", "slug": "corsa-c", "series": "Corsa" },
    { "id": "opel-corsa-d", "brandId": "opel", "name": "Corsa D", "slug": "corsa-d", "series": "Corsa" },
    { "id": "opel-corsa-e", "brandId": "opel", "name": "Corsa E", "slug": "corsa-e", "series": "Corsa" },
    { "id": "opel-corsa-f", "brandId": "opel", "name": "Corsa F", "slug": "corsa-f", "series": "Corsa" },
    { "id": "opel-crossland", "brandId": "opel", "name": "Crossland / Crossland X", "slug": "crossland", "series": "Crossland" },
    { "id": "opel-frontera", "brandId": "opel", "name": "Frontera", "slug": "frontera", "series": "Frontera" },
    { "id": "opel-grandland", "brandId": "opel", "name": "Grandland / Grandland X", "slug": "grandland", "series": "Grandland" },
    { "id": "opel-insignia-a", "brandId": "opel", "name": "Insignia A", "slug": "insignia-a", "series": "Insignia" },
    { "id": "opel-insignia-b", "brandId": "opel", "name": "Insignia B", "slug": "insignia-b", "series": "Insignia" },
    { "id": "opel-meriva-a", "brandId": "opel", "name": "Meriva A", "slug": "meriva-a", "series": "Meriva" },
    { "id": "opel-meriva-b", "brandId": "opel", "name": "Meriva B", "slug": "meriva-b", "series": "Meriva" },
    { "id": "opel-mokka-1", "brandId": "opel", "name": "Mokka I", "slug": "mokka-1", "series": "Mokka" },
    { "id": "opel-mokka-2", "brandId": "opel", "name": "Mokka II", "slug": "mokka-2", "series": "Mokka" },
    { "id": "opel-movano", "brandId": "opel", "name": "Movano", "slug": "movano", "series": "Movano" },
    { "id": "opel-omega-b", "brandId": "opel", "name": "Omega B", "slug": "omega-b", "series": "Omega" },
    { "id": "opel-tigra", "brandId": "opel", "name": "Tigra", "slug": "tigra", "series": "Tigra" },
    { "id": "opel-vectra-b", "brandId": "opel", "name": "Vectra B", "slug": "vectra-b", "series": "Vectra" },
    { "id": "opel-vectra-c", "brandId": "opel", "name": "Vectra C", "slug": "vectra-c", "series": "Vectra" },
    { "id": "opel-vivaro-1", "brandId": "opel", "name": "Vivaro I", "slug": "vivaro-1", "series": "Vivaro" },
    { "id": "opel-vivaro-2", "brandId": "opel", "name": "Vivaro II", "slug": "vivaro-2", "series": "Vivaro" },
    { "id": "opel-vivaro-3", "brandId": "opel", "name": "Vivaro III", "slug": "vivaro-3", "series": "Vivaro" },
    { "id": "opel-zafira-a", "brandId": "opel", "name": "Zafira A", "slug": "zafira-a", "series": "Zafira" },
    { "id": "opel-zafira-b", "brandId": "opel", "name": "Zafira B", "slug": "zafira-b", "series": "Zafira" },
    { "id": "opel-zafira-c", "brandId": "opel", "name": "Zafira C Tourer", "slug": "zafira-c", "series": "Zafira" },
    { "id": "opel-zafira-life", "brandId": "opel", "name": "Zafira Life", "slug": "zafira-life", "series": "Zafira" },
    { "id": "opel-ampera", "brandId": "opel", "name": "Ampera", "slug": "ampera", "series": "Ampera" },
    { "id": "opel-arena", "brandId": "opel", "name": "Arena", "slug": "arena", "series": "Van" },
    { "id": "opel-ascona", "brandId": "opel", "name": "Ascona", "slug": "ascona", "series": "Ascona" },
    { "id": "opel-calibra", "brandId": "opel", "name": "Calibra", "slug": "calibra", "series": "Calibra" },
    { "id": "opel-campo", "brandId": "opel", "name": "Campo", "slug": "campo", "series": "Pickup" },
    { "id": "opel-cascada", "brandId": "opel", "name": "Cascada", "slug": "cascada", "series": "Cascada" },
    { "id": "opel-gt", "brandId": "opel", "name": "GT", "slug": "gt", "series": "GT" },
    { "id": "opel-kadett", "brandId": "opel", "name": "Kadett", "slug": "kadett", "series": "Kadett" },
    { "id": "opel-karl", "brandId": "opel", "name": "Karl", "slug": "karl", "series": "Karl" },
    { "id": "opel-monza", "brandId": "opel", "name": "Monza", "slug": "monza", "series": "Monza" },
    { "id": "opel-signum", "brandId": "opel", "name": "Signum", "slug": "signum", "series": "Signum" },
    { "id": "opel-sintra", "brandId": "opel", "name": "Sintra", "slug": "sintra", "series": "Sintra" },
    { "id": "opel-speedster", "brandId": "opel", "name": "Speedster", "slug": "speedster", "series": "Speedster" },
    { "id": "volvo-c30", "brandId": "volvo", "name": "C30", "slug": "c30", "series": "C30" },
    { "id": "volvo-c70", "brandId": "volvo", "name": "C70", "slug": "c70", "series": "C70" },
    { "id": "volvo-s40-1", "brandId": "volvo", "name": "S40 / V40 I", "slug": "s40-1", "series": "S40" },
    { "id": "volvo-s40-2", "brandId": "volvo", "name": "S40 / V50 II", "slug": "s40-2", "series": "S40" },
    { "id": "volvo-s60-1", "brandId": "volvo", "name": "S60 I", "slug": "s60-1", "series": "S60", "keywords": ["D5", "2.4D", "T5", "R"] },
    { "id": "volvo-s60-2", "brandId": "volvo", "name": "S60 II", "slug": "s60-2", "series": "S60", "keywords": ["D2", "D3", "D4", "D5", "T4", "T5", "T6"] },
    { "id": "volvo-s60-3", "brandId": "volvo", "name": "S60 / V60 III", "slug": "s60-3", "series": "S60" },
    { "id": "volvo-s80-1", "brandId": "volvo", "name": "S80 I", "slug": "s80-1", "series": "S80" },
    { "id": "volvo-s80-2", "brandId": "volvo", "name": "S80 II", "slug": "s80-2", "series": "S80" },
    { "id": "volvo-s90", "brandId": "volvo", "name": "S90 / V90", "slug": "s90", "series": "S90" },
    { "id": "volvo-v40-1", "brandId": "volvo", "name": "V40 I", "slug": "v40-1", "series": "V40", "keywords": ["1.9 TD", "1.9 D", "T4"] },
    { "id": "volvo-v40-2", "brandId": "volvo", "name": "V40 II", "slug": "v40-2", "series": "V40", "keywords": ["D2", "D3", "D4", "Cross Country"] },
    { "id": "volvo-v70-2", "brandId": "volvo", "name": "V70 II", "slug": "v70-2", "series": "V70" },
    { "id": "volvo-v70-3", "brandId": "volvo", "name": "V70 III", "slug": "v70-3", "series": "V70" },
    { "id": "volvo-xc40", "brandId": "volvo", "name": "XC40", "slug": "xc40", "series": "XC40" },
    { "id": "volvo-xc60-1", "brandId": "volvo", "name": "XC60 I", "slug": "xc60-1", "series": "XC60", "keywords": ["D3", "D4", "D5"] },
    { "id": "volvo-xc60-2", "brandId": "volvo", "name": "XC60 II", "slug": "xc60-2", "series": "XC60" },
    { "id": "volvo-xc70-2", "brandId": "volvo", "name": "XC70 II", "slug": "xc70-2", "series": "XC70" },
    { "id": "volvo-xc70-3", "brandId": "volvo", "name": "XC70 III", "slug": "xc70-3", "series": "XC70" },
    { "id": "volvo-xc90-1", "brandId": "volvo", "name": "XC90 I", "slug": "xc90-1", "series": "XC90", "keywords": ["D5", "2.4 D5", "T6", "V8"] },
    { "id": "volvo-xc90-2", "brandId": "volvo", "name": "XC90 II", "slug": "xc90-2", "series": "XC90" },
    { "id": "volvo-s70", "brandId": "volvo", "name": "S70", "slug": "s70", "series": "S70" },
    { "id": "volvo-v50", "brandId": "volvo", "name": "V50", "slug": "v50", "series": "V50" },
    { "id": "volvo-v60", "brandId": "volvo", "name": "V60", "slug": "v60", "series": "V60" },
    { "id": "volvo-v70-1", "brandId": "volvo", "name": "V70 I", "slug": "v70-1", "series": "V70" },
    { "id": "volvo-xc70-1", "brandId": "volvo", "name": "XC70 I", "slug": "xc70-1", "series": "XC70" },
    { "id": "volvo-240", "brandId": "volvo", "name": "240 / 244 / 245", "slug": "240", "series": "200-as széria" },
    { "id": "volvo-340", "brandId": "volvo", "name": "340 / 343 / 345 / 360", "slug": "340", "series": "300-as széria" },
    { "id": "volvo-440", "brandId": "volvo", "name": "440 / 460 / 480", "slug": "440", "series": "400-as széria" },
    { "id": "volvo-740", "brandId": "volvo", "name": "740 / 760 / 780", "slug": "740", "series": "700-as széria" },
    { "id": "volvo-850", "brandId": "volvo", "name": "850", "slug": "850", "series": "800-as széria" },
    { "id": "volvo-940", "brandId": "volvo", "name": "940 / 960", "slug": "940", "series": "900-as széria" },
    { "id": "volvo-c40", "brandId": "volvo", "name": "C40", "slug": "c40", "series": "C40" },
    { "id": "volvo-ex30", "brandId": "volvo", "name": "EX30", "slug": "ex30", "series": "EX30" },
    { "id": "volvo-ex90", "brandId": "volvo", "name": "EX90", "slug": "ex90", "series": "EX90" },
    { "id": "iveco-daily-3", "brandId": "iveco", "name": "Daily III", "slug": "daily-3", "series": "Daily" },
    { "id": "iveco-daily-4", "brandId": "iveco", "name": "Daily IV/V", "slug": "daily-4", "series": "Daily" },
    { "id": "iveco-daily-6", "brandId": "iveco", "name": "Daily VI", "slug": "daily-6", "series": "Daily" },
    { "id": "iveco-eurocargo", "brandId": "iveco", "name": "Eurocargo", "slug": "eurocargo", "series": "Truck" },
    { "id": "iveco-stralis", "brandId": "iveco", "name": "Stralis", "slug": "stralis", "series": "Truck" },
    { "id": "iveco-sway", "brandId": "iveco", "name": "S-Way", "slug": "sway", "series": "Truck" },
    { "id": "jaguar-xf", "brandId": "jaguar", "name": "XF", "slug": "xf", "series": "XF" },
    { "id": "jaguar-xj", "brandId": "jaguar", "name": "XJ", "slug": "xj", "series": "XJ" },
    { "id": "jaguar-xe", "brandId": "jaguar", "name": "XE", "slug": "xe", "series": "XE" },
    { "id": "jaguar-fpace", "brandId": "jaguar", "name": "F-Pace", "slug": "fpace", "series": "F-Pace" },
    { "id": "jaguar-epace", "brandId": "jaguar", "name": "E-Pace", "slug": "epace", "series": "E-Pace" },
    { "id": "jaguar-ftype", "brandId": "jaguar", "name": "F-Type", "slug": "ftype", "series": "F-Type" },
    { "id": "jaguar-ipace", "brandId": "jaguar", "name": "I-Pace", "slug": "ipace", "series": "I-Pace" },
    { "id": "jaguar-stype", "brandId": "jaguar", "name": "S-Type", "slug": "stype", "series": "S-Type" },
    { "id": "jaguar-xk", "brandId": "jaguar", "name": "XK", "slug": "xk", "series": "XK" },
    { "id": "jaguar-xtype", "brandId": "jaguar", "name": "X-Type", "slug": "xtype", "series": "X-Type" },
    { "id": "jeep-cherokee", "brandId": "jeep", "name": "Cherokee", "slug": "cherokee", "series": "Cherokee" },
    { "id": "jeep-compass", "brandId": "jeep", "name": "Compass", "slug": "compass", "series": "Compass" },
    { "id": "jeep-grand-cherokee", "brandId": "jeep", "name": "Grand Cherokee", "slug": "grand-cherokee", "series": "Grand Cherokee" },
    { "id": "jeep-renegade", "brandId": "jeep", "name": "Renegade", "slug": "renegade", "series": "Renegade" },
    { "id": "jeep-wrangler", "brandId": "jeep", "name": "Wrangler", "slug": "wrangler", "series": "Wrangler" },
    { "id": "jeep-commander", "brandId": "jeep", "name": "Commander", "slug": "commander", "series": "Commander" },
    { "id": "jeep-gladiator", "brandId": "jeep", "name": "Gladiator", "slug": "gladiator", "series": "Gladiator" },
    { "id": "jeep-patriot", "brandId": "jeep", "name": "Patriot", "slug": "patriot", "series": "Patriot" },
    { "id": "jeep-avenger", "brandId": "jeep", "name": "Avenger", "slug": "avenger", "series": "Avenger" },
    { "id": "jeep-wagoneer", "brandId": "jeep", "name": "Wagoneer", "slug": "wagoneer", "series": "Wagoneer" },
    { "id": "lada-niva", "brandId": "lada", "name": "Niva / 4x4", "slug": "niva", "series": "Niva" },
    { "id": "lada-2101", "brandId": "lada", "name": "1200 / 2101", "slug": "2101", "series": "Zsiguli" },
    { "id": "lada-2105", "brandId": "lada", "name": "2105 / 2107", "slug": "2105", "series": "Zsiguli" },
    { "id": "lada-granta", "brandId": "lada", "name": "Granta", "slug": "granta", "series": "Granta" },
    { "id": "lada-kalina", "brandId": "lada", "name": "Kalina", "slug": "kalina", "series": "Kalina" },
    { "id": "lada-priora", "brandId": "lada", "name": "Priora", "slug": "priora", "series": "Priora" },
    { "id": "lada-samara", "brandId": "lada", "name": "Samara", "slug": "samara", "series": "Samara" },
    { "id": "lada-vesta", "brandId": "lada", "name": "Vesta", "slug": "vesta", "series": "Vesta" },
    { "id": "lancia-ypsilon", "brandId": "lancia", "name": "Ypsilon", "slug": "ypsilon", "series": "Ypsilon" },
    { "id": "lancia-delta", "brandId": "lancia", "name": "Delta", "slug": "delta", "series": "Delta" },
    { "id": "lancia-kappa", "brandId": "lancia", "name": "Kappa", "slug": "kappa", "series": "Kappa" },
    { "id": "lancia-lybra", "brandId": "lancia", "name": "Lybra", "slug": "lybra", "series": "Lybra" },
    { "id": "lancia-musa", "brandId": "lancia", "name": "Musa", "slug": "musa", "series": "Musa" },
    { "id": "lancia-phedra", "brandId": "lancia", "name": "Phedra", "slug": "phedra", "series": "Phedra" },
    { "id": "lancia-thema", "brandId": "lancia", "name": "Thema", "slug": "thema", "series": "Thema" },
    { "id": "lancia-thesis", "brandId": "lancia", "name": "Thesis", "slug": "thesis", "series": "Thesis" },
    { "id": "lancia-voyager", "brandId": "lancia", "name": "Voyager", "slug": "voyager", "series": "Voyager" },
    { "id": "lancia-zeta", "brandId": "lancia", "name": "Zeta", "slug": "zeta", "series": "Zeta" },
    { "id": "land-rover-discovery", "brandId": "land-rover", "name": "Discovery", "slug": "discovery", "series": "Discovery" },
    { "id": "land-rover-freelander", "brandId": "land-rover", "name": "Freelander", "slug": "freelander", "series": "Freelander" },
    { "id": "land-rover-range-rover", "brandId": "land-rover", "name": "Range Rover / Sport", "slug": "range-rover", "series": "Range Rover" },
    { "id": "land-rover-evoque", "brandId": "land-rover", "name": "Range Rover Evoque", "slug": "evoque", "series": "Range Rover" },
    { "id": "land-rover-defender", "brandId": "land-rover", "name": "Defender", "slug": "defender", "series": "Defender" },
    { "id": "land-rover-discovery-sport", "brandId": "land-rover", "name": "Discovery Sport", "slug": "discovery-sport", "series": "Discovery" },
    { "id": "land-rover-range-rover-sport", "brandId": "land-rover", "name": "Range Rover Sport", "slug": "range-rover-sport", "series": "Range Rover" },
    { "id": "land-rover-range-rover-velar", "brandId": "land-rover", "name": "Range Rover Velar", "slug": "range-rover-velar", "series": "Range Rover" },
    { "id": "mini-cooper-r50", "brandId": "mini", "name": "Cooper / One (R50/R53)", "slug": "cooper-r50", "series": "Cooper" },
    { "id": "mini-cooper-r56", "brandId": "mini", "name": "Cooper / One (R56)", "slug": "cooper-r56", "series": "Cooper" },
    { "id": "mini-cooper-f56", "brandId": "mini", "name": "Cooper / One (F56)", "slug": "cooper-f56", "series": "Cooper" },
    { "id": "mini-countryman", "brandId": "mini", "name": "Countryman", "slug": "countryman", "series": "Countryman" },
    { "id": "mini-clubman", "brandId": "mini", "name": "Clubman", "slug": "clubman", "series": "Clubman" },
    { "id": "mini-convertible", "brandId": "mini", "name": "Convertible", "slug": "convertible", "series": "Convertible" },
    { "id": "mini-coupe", "brandId": "mini", "name": "Coupe", "slug": "coupe", "series": "Coupe" },
    { "id": "mini-paceman", "brandId": "mini", "name": "Paceman", "slug": "paceman", "series": "Paceman" },
    { "id": "mini-roadster", "brandId": "mini", "name": "Roadster", "slug": "roadster", "series": "Roadster" },
    { "id": "saab-93", "brandId": "saab", "name": "9-3", "slug": "9-3", "series": "9-3" },
    { "id": "saab-95", "brandId": "saab", "name": "9-5", "slug": "9-5", "series": "9-5" },
    { "id": "saab-900", "brandId": "saab", "name": "900", "slug": "900", "series": "900" },
    { "id": "saab-9000", "brandId": "saab", "name": "9000", "slug": "9000", "series": "9000" },
    { "id": "saab-97x", "brandId": "saab", "name": "9-7X", "slug": "9-7x", "series": "9-7X" },
    { "id": "scania-r-series", "brandId": "scania", "name": "R / PRT-Series", "slug": "r-series", "series": "R-Series" },
    { "id": "scania-l-series", "brandId": "scania", "name": "L-Series", "slug": "l-series", "series": "L-Series" },
    { "id": "scania-s-series", "brandId": "scania", "name": "S-Series", "slug": "s-series", "series": "S-Series" },
    { "id": "scania-p-series", "brandId": "scania", "name": "P-Series", "slug": "p-series", "series": "P-Series" },
    { "id": "scania-g-series", "brandId": "scania", "name": "G-Series", "slug": "g-series", "series": "G-Series" },
    { "id": "smart-fortwo-450", "brandId": "smart", "name": "Fortwo (450)", "slug": "fortwo-450", "series": "Fortwo" },
    { "id": "smart-fortwo-451", "brandId": "smart", "name": "Fortwo (451)", "slug": "fortwo-451", "series": "Fortwo" },
    { "id": "smart-fortwo-453", "brandId": "smart", "name": "Fortwo (453)", "slug": "fortwo-453", "series": "Fortwo" },
    { "id": "smart-forfour", "brandId": "smart", "name": "Forfour", "slug": "forfour", "series": "Forfour" },
    { "id": "smart-roadster", "brandId": "smart", "name": "Roadster", "slug": "roadster", "series": "Roadster" },
    { "id": "smart-1", "brandId": "smart", "name": "#1", "slug": "smart-1", "series": "#1" },
    { "id": "smart-3", "brandId": "smart", "name": "#3", "slug": "smart-3", "series": "#3" },
];
