import { Model } from './types';

export const otherBrandsModels: Model[] = [
    { "id": "alfa-romeo-145", "brandId": "alfa-romeo", "name": "145", "slug": "145", "series": "145" },
    { "id": "alfa-romeo-146", "brandId": "alfa-romeo", "name": "146", "slug": "146", "series": "146" },
    { "id": "alfa-romeo-147", "brandId": "alfa-romeo", "name": "147", "slug": "147", "series": "147", "keywords": ["1.6 TS", "1.9 JTD", "GTA"] },
    { "id": "alfa-romeo-156", "brandId": "alfa-romeo", "name": "156", "slug": "156", "series": "156", "keywords": ["1.9 JTD", "2.4 JTD", "TS", "GTA"] },
    { "id": "alfa-romeo-159", "brandId": "alfa-romeo", "name": "159", "slug": "159", "series": "159", "keywords": ["1.9 JTDm", "2.4 JTDm", "TBi"] },
    { "id": "alfa-romeo-166", "brandId": "alfa-romeo", "name": "166", "slug": "166", "series": "166" },
    { "id": "alfa-romeo-brera", "brandId": "alfa-romeo", "name": "Brera", "slug": "brera", "series": "Brera" },
    { "id": "alfa-romeo-giulia", "brandId": "alfa-romeo", "name": "Giulia", "slug": "giulia", "series": "Giulia" },
    { "id": "alfa-romeo-giulietta", "brandId": "alfa-romeo", "name": "Giulietta", "slug": "giulietta", "series": "Giulietta", "keywords": ["Quadrifoglio", "1.4 TB", "1.6 JTDm", "2.0 JTDm"] },
    { "id": "alfa-romeo-mito", "brandId": "alfa-romeo", "name": "MiTo", "slug": "mito", "series": "MiTo", "keywords": ["Quadrifoglio", "1.3 JTDm"] },
    { "id": "alfa-romeo-stelvio", "brandId": "alfa-romeo", "name": "Stelvio", "slug": "stelvio", "series": "Stelvio" },
    { "id": "alfa-romeo-tonale", "brandId": "alfa-romeo", "name": "Tonale", "slug": "tonale", "series": "Tonale" },
    { "id": "alfa-romeo-33", "brandId": "alfa-romeo", "name": "33", "slug": "33", "series": "33" },
    { "id": "alfa-romeo-4c", "brandId": "alfa-romeo", "name": "4C", "slug": "4c", "series": "4C" },
    { "id": "alfa-romeo-75", "brandId": "alfa-romeo", "name": "75", "slug": "75", "series": "75" },
    { "id": "alfa-romeo-8c", "brandId": "alfa-romeo", "name": "8C", "slug": "8c", "series": "8C" },
    { "id": "alfa-romeo-gt", "brandId": "alfa-romeo", "name": "GT", "slug": "gt", "series": "GT" },
    { "id": "alfa-romeo-gtv", "brandId": "alfa-romeo", "name": "GTV / Spider", "slug": "gtv", "series": "GTV" },
    { "id": "alfa-romeo-junior", "brandId": "alfa-romeo", "name": "Junior", "slug": "junior", "series": "Junior" },
    { "id": "alfa-romeo-spider", "brandId": "alfa-romeo", "name": "Spider", "slug": "spider", "series": "Spider" },
    { "id": "bmw-1-e81", "brandId": "bmw", "name": "1 (E81)", "slug": "1-e81", "series": "1-es sorozat" },
    { "id": "bmw-1-e82", "brandId": "bmw", "name": "1 (E82)", "slug": "1-e82", "series": "1-es sorozat" },
    { "id": "bmw-1-e87", "brandId": "bmw", "name": "1 (E87)", "slug": "1-e87", "series": "1-es sorozat" },
    { "id": "bmw-1-e88", "brandId": "bmw", "name": "1 (E88)", "slug": "1-e88", "series": "1-es sorozat" },
    { "id": "bmw-1-f20", "brandId": "bmw", "name": "1 (F20)", "slug": "1-f20", "series": "1-es sorozat" },
    { "id": "bmw-1-f21", "brandId": "bmw", "name": "1 (F21)", "slug": "1-f21", "series": "1-es sorozat" },
    { "id": "bmw-1-f40", "brandId": "bmw", "name": "1 (F40)", "slug": "1-f40", "series": "1-es sorozat" },
    { "id": "bmw-2-f22", "brandId": "bmw", "name": "2 (F22)", "slug": "2-f22", "series": "2-es sorozat" },
    { "id": "bmw-2-f23", "brandId": "bmw", "name": "2 (F23)", "slug": "2-f23", "series": "2-es sorozat" },
    { "id": "bmw-2-f44", "brandId": "bmw", "name": "2 Gran Coupé (F44)", "slug": "2-f44", "series": "2-es sorozat" },
    { "id": "bmw-2-f45", "brandId": "bmw", "name": "2 Active Tourer (F45)", "slug": "2-f45", "series": "2-es sorozat", "keywords": ["Active Tourer", "F45", "BMW 2", "218d", "216d"] },
    { "id": "bmw-2-f46", "brandId": "bmw", "name": "2 Gran Tourer (F46)", "slug": "2-f46", "series": "2-es sorozat", "keywords": ["Gran Tourer", "F46", "BMW 2", "218d", "220d"] },
    { "id": "bmw-3-e30", "brandId": "bmw", "name": "3 (E30)", "slug": "3-e30", "series": "3-as sorozat", "keywords": ["E30", "316i", "318i", "320i", "325i", "M3"] },
    { "id": "bmw-3-e36", "brandId": "bmw", "name": "3 (E36)", "slug": "3-e36", "series": "3-as sorozat", "keywords": ["E36", "316i", "318is", "320i", "325tds", "M3", "M43", "M44", "M50", "M52", "M41", "M51"] },
    { "id": "bmw-3-e46", "brandId": "bmw", "name": "3 (E46)", "slug": "3-e46", "series": "3-as sorozat", "keywords": ["E46", "316i", "318d", "320d", "330d", "330i", "M3", "M43", "N42", "N46", "M47", "M54", "M57", "M57N"] },
    { "id": "bmw-3-e90", "brandId": "bmw", "name": "3 (E90)", "slug": "3-e90", "series": "3-as sorozat", "keywords": ["E90", "318d", "320d", "M3"] },
    { "id": "bmw-3-e91", "brandId": "bmw", "name": "3 (E91)", "slug": "3-e91", "series": "3-as sorozat", "keywords": ["E91", "Touring", "320d"] },
    { "id": "bmw-3-e92", "brandId": "bmw", "name": "3 (E92)", "slug": "3-e92", "series": "3-as sorozat", "keywords": ["E92", "Coupe", "335i"] },
    { "id": "bmw-3-e93", "brandId": "bmw", "name": "3 (E93)", "slug": "3-e93", "series": "3-as sorozat", "keywords": ["E93", "Cabrio"] },
    { "id": "bmw-3-f30", "brandId": "bmw", "name": "3 (F30)", "slug": "3-f30", "series": "3-as sorozat", "keywords": ["F30", "318d", "320d"] },
    { "id": "bmw-3-f31", "brandId": "bmw", "name": "3 (F31)", "slug": "3-f31", "series": "3-as sorozat", "keywords": ["F31", "Touring"] },
    { "id": "bmw-3-f34", "brandId": "bmw", "name": "3 GT (F34)", "slug": "3-f34", "series": "3-as sorozat", "keywords": ["F34", "Gran Turismo"] },
    { "id": "bmw-3-g20", "brandId": "bmw", "name": "3 (G20)", "slug": "3-g20", "series": "3-as sorozat", "keywords": ["G20"] },
    { "id": "bmw-3-g21", "brandId": "bmw", "name": "3 (G21)", "slug": "3-g21", "series": "3-as sorozat", "keywords": ["G21"] },
    { "id": "bmw-4-f32", "brandId": "bmw", "name": "4 (F32)", "slug": "4-f32", "series": "4-es sorozat" },
    { "id": "bmw-4-f33", "brandId": "bmw", "name": "4 (F33)", "slug": "4-f33", "series": "4-es sorozat" },
    { "id": "bmw-4-f36", "brandId": "bmw", "name": "4 Gran Coupe (F36)", "slug": "4-f36", "series": "4-es sorozat" },
    { "id": "bmw-4-g22", "brandId": "bmw", "name": "4 (G22)", "slug": "4-g22", "series": "4-es sorozat" },
    { "id": "bmw-4-g23", "brandId": "bmw", "name": "4 (G23)", "slug": "4-g23", "series": "4-es sorozat" },
    { "id": "bmw-4-g26", "brandId": "bmw", "name": "4 (G26)", "slug": "4-g26", "series": "4-es sorozat" },
    { "id": "bmw-5-e34", "brandId": "bmw", "name": "5 (E34)", "slug": "5-e34", "series": "5-ös sorozat", "keywords": ["E34", "520i", "525tds"] },
    { "id": "bmw-5-e39", "brandId": "bmw", "name": "5 (E39)", "slug": "5-e39", "series": "5-ös sorozat", "keywords": ["E39", "520d", "525d", "530d", "M5"] },
    { "id": "bmw-5-e60", "brandId": "bmw", "name": "5 (E60)", "slug": "5-e60", "series": "5-ös sorozat", "keywords": ["E60", "520d", "525d", "530d", "535d", "M5"] },
    { "id": "bmw-5-e61", "brandId": "bmw", "name": "5 Touring (E61)", "slug": "5-e61", "series": "5-ös sorozat", "keywords": ["E61", "Touring", "525d", "530d"] },
    { "id": "bmw-5-f10", "brandId": "bmw", "name": "5 (F10)", "slug": "5-f10", "series": "5-ös sorozat", "keywords": ["F10", "520d", "525d", "530d", "535d", "M5"] },
    { "id": "bmw-5-f11", "brandId": "bmw", "name": "5 Touring (F11)", "slug": "5-f11", "series": "5-ös sorozat", "keywords": ["F11", "Touring", "520d", "530d"] },
    { "id": "bmw-5-f07", "brandId": "bmw", "name": "5 GT (F07)", "slug": "5-f07", "series": "5-ös sorozat", "keywords": ["F07", "Gran Turismo", "530d", "535d"] },
    { "id": "bmw-5-g30", "brandId": "bmw", "name": "5 (G30)", "slug": "5-g30", "series": "5-ös sorozat" },
    { "id": "bmw-5-g31", "brandId": "bmw", "name": "5 (G31)", "slug": "5-g31", "series": "5-ös sorozat" },
    { "id": "bmw-5-g60", "brandId": "bmw", "name": "5 (G60)", "slug": "5-g60", "series": "5-ös sorozat" },
    { "id": "bmw-5-g61", "brandId": "bmw", "name": "5 (G61)", "slug": "5-g61", "series": "5-ös sorozat" },
    { "id": "bmw-6-e63", "brandId": "bmw", "name": "6 (E63)", "slug": "6-e63", "series": "6-os sorozat", "keywords": ["E63", "630i", "645i"] },
    { "id": "bmw-6-e64", "brandId": "bmw", "name": "6 (E64)", "slug": "6-e64", "series": "6-os sorozat", "keywords": ["E64", "Cabrio"] },
    { "id": "bmw-6-f12", "brandId": "bmw", "name": "6 (F12)", "slug": "6-f12", "series": "6-os sorozat", "keywords": ["F12", "Cabrio"] },
    { "id": "bmw-6-f13", "brandId": "bmw", "name": "6 (F13)", "slug": "6-f13", "series": "6-os sorozat", "keywords": ["F13", "Coupe"] },
    { "id": "bmw-6-f06", "brandId": "bmw", "name": "6 Gran Coupe (F06)", "slug": "6-f06", "series": "6-os sorozat", "keywords": ["F06", "Gran Coupe"] },
    { "id": "bmw-6-g32", "brandId": "bmw", "name": "6 GT (G32)", "slug": "6-g32", "series": "6-os sorozat" },
    { "id": "bmw-7-e38", "brandId": "bmw", "name": "7 (E38)", "slug": "7-e38", "series": "7-es sorozat", "keywords": ["E38", "725tds", "730d", "740d", "740i", "750i"] },
    { "id": "bmw-7-e65", "brandId": "bmw", "name": "7 (E65)", "slug": "7-e65", "series": "7-es sorozat", "keywords": ["E65", "730d", "740d"] },
    { "id": "bmw-7-e66", "brandId": "bmw", "name": "7 (E66)", "slug": "7-e66", "series": "7-es sorozat", "keywords": ["E66", "Long"] },
    { "id": "bmw-7-f01", "brandId": "bmw", "name": "7 (F01)", "slug": "7-f01", "series": "7-es sorozat", "keywords": ["F01", "730d", "740d"] },
    { "id": "bmw-7-f02", "brandId": "bmw", "name": "7 (F02)", "slug": "7-f02", "series": "7-es sorozat", "keywords": ["F02", "Long"] },
    { "id": "bmw-7-g11", "brandId": "bmw", "name": "7 (G11)", "slug": "7-g11", "series": "7-es sorozat", "keywords": ["G11", "730d", "740d"] },
    { "id": "bmw-7-g12", "brandId": "bmw", "name": "7 (G12)", "slug": "7-g12", "series": "7-es sorozat", "keywords": ["G12", "Long"] },
    { "id": "bmw-7-g70", "brandId": "bmw", "name": "7 (G70)", "slug": "7-g70", "series": "7-es sorozat" },
    { "id": "bmw-8-e31", "brandId": "bmw", "name": "8 (E31)", "slug": "8-e31", "series": "8-as sorozat" },
    { "id": "bmw-8-g14", "brandId": "bmw", "name": "8 (G14)", "slug": "8-g14", "series": "8-as sorozat" },
    { "id": "bmw-8-g15", "brandId": "bmw", "name": "8 (G15)", "slug": "8-g15", "series": "8-as sorozat" },
    { "id": "bmw-8-g16", "brandId": "bmw", "name": "8 (G16)", "slug": "8-g16", "series": "8-as sorozat" },
    { "id": "bmw-x1-e84", "brandId": "bmw", "name": "X1 (E84)", "slug": "x1-e84", "series": "X széria", "keywords": ["E84", "18d", "20d"] },
    { "id": "bmw-x1-f48", "brandId": "bmw", "name": "X1 (F48)", "slug": "x1-f48", "series": "X széria", "keywords": ["F48", "18d", "20d"] },
    { "id": "bmw-x1-u11", "brandId": "bmw", "name": "X1 (U11)", "slug": "x1-u11", "series": "X széria" },
    { "id": "bmw-x5-e53", "brandId": "bmw", "name": "X5 (E53)", "slug": "x5-e53", "series": "X széria", "keywords": ["E53", "3.0d", "4.4i", "4.6is"] },
    { "id": "bmw-x5-e70", "brandId": "bmw", "name": "X5 (E70)", "slug": "x5-e70", "series": "X széria", "keywords": ["E70", "3.0d", "35d", "40d", "M50d"] },
    { "id": "bmw-x5-f15", "brandId": "bmw", "name": "X5 (F15)", "slug": "x5-f15", "series": "X széria", "keywords": ["F15", "25d", "30d", "40d", "M50d"] },
    { "id": "bmw-x5-g05", "brandId": "bmw", "name": "X5 (G05)", "slug": "x5-g05", "series": "X széria", "keywords": ["G05", "30d", "40d", "45e"] },
    { "id": "bmw-x6-e71", "brandId": "bmw", "name": "X6 (E71)", "slug": "x6-e71", "series": "X széria", "keywords": ["E71", "30d", "35d", "40d", "M50d"] },
    { "id": "bmw-x2-f39", "brandId": "bmw", "name": "X2 (F39)", "slug": "x2-f39", "series": "X széria" },
    { "id": "bmw-x3-e83", "brandId": "bmw", "name": "X3 (E83)", "slug": "x3-e83", "series": "X széria", "keywords": ["E83", "2.0d", "3.0d"] },
    { "id": "bmw-x3-f25", "brandId": "bmw", "name": "X3 (F25)", "slug": "x3-f25", "series": "X széria", "keywords": ["F25", "20d", "30d"] },
    { "id": "bmw-x3-g01", "brandId": "bmw", "name": "X3 (G01)", "slug": "x3-g01", "series": "X széria", "keywords": ["G01", "20d", "30d"] },
    { "id": "bmw-x4-f26", "brandId": "bmw", "name": "X4 (F26)", "slug": "x4-f26", "series": "X széria" },
    { "id": "bmw-x4-g02", "brandId": "bmw", "name": "X4 (G02)", "slug": "x4-g02", "series": "X széria" },
    { "id": "bmw-x6-f16", "brandId": "bmw", "name": "X6 (F16)", "slug": "x6-f16", "series": "X széria" },
    { "id": "bmw-x6-g06", "brandId": "bmw", "name": "X6 (G06)", "slug": "x6-g06", "series": "X széria" },
    { "id": "bmw-x7-g07", "brandId": "bmw", "name": "X7 (G07)", "slug": "x7-g07", "series": "X széria" },
    { "id": "bmw-z3-coupe", "brandId": "bmw", "name": "Z3 Coupe (E36/8)", "slug": "z3-coupe", "series": "Z széria" },
    { "id": "bmw-z3-roadster", "brandId": "bmw", "name": "Z3 Roadster (E36/7)", "slug": "z3-roadster", "series": "Z széria" },
    { "id": "bmw-z4-e85", "brandId": "bmw", "name": "Z4 (E85)", "slug": "z4-e85", "series": "Z széria" },
    { "id": "bmw-z4-e86", "brandId": "bmw", "name": "Z4 Coupe (E86)", "slug": "z4-e86", "series": "Z széria" },
    { "id": "bmw-z4-e89", "brandId": "bmw", "name": "Z4 (E89)", "slug": "z4-e89", "series": "Z széria" },
    { "id": "bmw-z4-g29", "brandId": "bmw", "name": "Z4 (G29)", "slug": "z4-g29", "series": "Z széria" },
    { "id": "bmw-z8-e52", "brandId": "bmw", "name": "Z8 (E52)", "slug": "z8-e52", "series": "Z széria" },
    { "id": "bmw-z1", "brandId": "bmw", "name": "Z1", "slug": "z1", "series": "Z széria" },
    { "id": "bmw-i3", "brandId": "bmw", "name": "i3 (I01)", "slug": "i3", "series": "i széria" },
    { "id": "bmw-i4", "brandId": "bmw", "name": "i4 (G26)", "slug": "i4", "series": "i széria" },
    { "id": "bmw-ix", "brandId": "bmw", "name": "iX (I20)", "slug": "ix", "series": "i széria" },
    { "id": "bmw-ix1", "brandId": "bmw", "name": "iX1 (U11)", "slug": "ix1", "series": "i széria" },
    { "id": "bmw-ix2", "brandId": "bmw", "name": "iX2 (U10)", "slug": "ix2", "series": "i széria" },
    { "id": "bmw-ix3", "brandId": "bmw", "name": "iX3 (G08)", "slug": "ix3", "series": "i széria" },
    { "id": "bmw-i8", "brandId": "bmw", "name": "i8 (I12/I15)", "slug": "i8", "series": "i széria" },
    { "id": "bmw-m2", "brandId": "bmw", "name": "M2 (F87/G42)", "slug": "m2", "series": "M széria" },
    { "id": "bmw-m5", "brandId": "bmw", "name": "M5 (E60/F10/F90)", "slug": "m5", "series": "M széria" },
    { "id": "bmw-m6", "brandId": "bmw", "name": "M6 (E63/F13/F06)", "slug": "m6", "series": "M széria" },
    { "id": "bmw-xm", "brandId": "bmw", "name": "XM (G09)", "slug": "xm", "series": "M széria" },

    { "id": "chevrolet-aveo", "brandId": "chevrolet", "name": "Aveo", "slug": "aveo", "series": "Aveo" },
    { "id": "chevrolet-captiva", "brandId": "chevrolet", "name": "Captiva", "slug": "captiva", "series": "Captiva" },
    { "id": "chevrolet-cruze", "brandId": "chevrolet", "name": "Cruze", "slug": "cruze", "series": "Cruze" },
    { "id": "chevrolet-epica", "brandId": "chevrolet", "name": "Epica", "slug": "epica", "series": "Epica" },
    { "id": "chevrolet-kalos", "brandId": "chevrolet", "name": "Kalos", "slug": "kalos", "series": "Kalos" },
    { "id": "chevrolet-lacetti", "brandId": "chevrolet", "name": "Lacetti", "slug": "lacetti", "series": "Lacetti" },
    { "id": "chevrolet-matiz", "brandId": "chevrolet", "name": "Matiz", "slug": "matiz", "series": "Matiz" },
    { "id": "chevrolet-orlando", "brandId": "chevrolet", "name": "Orlando", "slug": "orlando", "series": "Orlando" },
    { "id": "chevrolet-spark", "brandId": "chevrolet", "name": "Spark", "slug": "spark", "series": "Spark" },
    { "id": "chevrolet-trax", "brandId": "chevrolet", "name": "Trax", "slug": "trax", "series": "Trax" },
    { "id": "chevrolet-camaro", "brandId": "chevrolet", "name": "Camaro", "slug": "camaro", "series": "Camaro" },
    { "id": "chevrolet-corvette", "brandId": "chevrolet", "name": "Corvette", "slug": "corvette", "series": "Corvette" },
    { "id": "chevrolet-hhr", "brandId": "chevrolet", "name": "HHR", "slug": "hhr", "series": "HHR" },
    { "id": "chevrolet-silverado", "brandId": "chevrolet", "name": "Silverado", "slug": "silverado", "series": "Silverado" },
    { "id": "chevrolet-tahoe", "brandId": "chevrolet", "name": "Tahoe", "slug": "tahoe", "series": "Tahoe" },
    { "id": "chevrolet-suburban", "brandId": "chevrolet", "name": "Suburban", "slug": "suburban", "series": "Suburban" },
    { "id": "dodge-caliber", "brandId": "dodge", "name": "Caliber", "slug": "caliber", "series": "Caliber" },
    { "id": "dodge-journey", "brandId": "dodge", "name": "Journey", "slug": "journey", "series": "Journey" },
    { "id": "dodge-ram", "brandId": "dodge", "name": "RAM", "slug": "ram", "series": "RAM" },
    { "id": "dodge-avenger", "brandId": "dodge", "name": "Avenger", "slug": "avenger", "series": "Avenger" },
    { "id": "dodge-challenger", "brandId": "dodge", "name": "Challenger", "slug": "challenger", "series": "Challenger" },
    { "id": "dodge-charger", "brandId": "dodge", "name": "Charger", "slug": "charger", "series": "Charger" },
    { "id": "dodge-dakota", "brandId": "dodge", "name": "Dakota", "slug": "dakota", "series": "Dakota" },
    { "id": "dodge-durango", "brandId": "dodge", "name": "Durango", "slug": "durango", "series": "Durango" },
    { "id": "dodge-grand-caravan", "brandId": "dodge", "name": "Grand Caravan", "slug": "grand-caravan", "series": "Caravan" },
    { "id": "dodge-magnum", "brandId": "dodge", "name": "Magnum", "slug": "magnum", "series": "Magnum" },
    { "id": "dodge-neon", "brandId": "dodge", "name": "Neon", "slug": "neon", "series": "Neon" },
    { "id": "dodge-nitro", "brandId": "dodge", "name": "Nitro", "slug": "nitro", "series": "Nitro" },
    { "id": "dodge-stealth", "brandId": "dodge", "name": "Stealth", "slug": "stealth", "series": "Stealth" },
    { "id": "dodge-viper", "brandId": "dodge", "name": "Viper", "slug": "viper", "series": "Viper" },
    { "id": "fiat-124", "brandId": "fiat", "name": "124", "slug": "124", "series": "124" },
    { "id": "fiat-125", "brandId": "fiat", "name": "125", "slug": "125", "series": "125" },
    { "id": "fiat-126", "brandId": "fiat", "name": "126", "slug": "126", "series": "126" },
    { "id": "fiat-127", "brandId": "fiat", "name": "127", "slug": "127", "series": "127" },
    { "id": "fiat-128", "brandId": "fiat", "name": "128", "slug": "128", "series": "128" },
    { "id": "fiat-131", "brandId": "fiat", "name": "131", "slug": "131", "series": "131" },
    { "id": "fiat-132", "brandId": "fiat", "name": "132", "slug": "132", "series": "132" },
    { "id": "fiat-242-serie", "brandId": "fiat", "name": "242-Serie", "slug": "242-serie", "series": "Haszonjármű" },
    { "id": "fiat-500", "brandId": "fiat", "name": "500", "slug": "500", "series": "500", "keywords": ["C", "L", "X", "Abarth", "Multijet", "1.2", "0.9 TwinAir"] },
    { "id": "fiat-500e", "brandId": "fiat", "name": "500e", "slug": "500e", "series": "500" },
    { "id": "fiat-500x", "brandId": "fiat", "name": "500X", "slug": "500x", "series": "500" },
    { "id": "fiat-500l", "brandId": "fiat", "name": "500L", "slug": "500l", "series": "500" },
    { "id": "fiat-600", "brandId": "fiat", "name": "600", "slug": "600", "series": "600" },
    { "id": "fiat-600e", "brandId": "fiat", "name": "600e", "slug": "600e", "series": "600" },
    { "id": "fiat-850", "brandId": "fiat", "name": "850", "slug": "850", "series": "850" },
    { "id": "fiat-900", "brandId": "fiat", "name": "900", "slug": "900", "series": "900" },
    { "id": "fiat-albea", "brandId": "fiat", "name": "Albea", "slug": "albea", "series": "Albea" },
    { "id": "fiat-argenta", "brandId": "fiat", "name": "Argenta", "slug": "argenta", "series": "Argenta" },
    { "id": "fiat-barchetta", "brandId": "fiat", "name": "Barchetta", "slug": "barchetta", "series": "Barchetta" },
    { "id": "fiat-brava", "brandId": "fiat", "name": "Brava", "slug": "brava", "series": "Brava" },
    { "id": "fiat-bravo-1", "brandId": "fiat", "name": "Bravo (182)", "slug": "bravo-1", "series": "Bravo" },
    { "id": "fiat-bravo-2", "brandId": "fiat", "name": "Bravo (198)", "slug": "bravo-2", "series": "Bravo", "keywords": ["Multijet", "1.4 T-Jet"] },
    { "id": "fiat-cinquecento", "brandId": "fiat", "name": "Cinquecento", "slug": "cinquecento", "series": "Cinquecento" },
    { "id": "fiat-coupe", "brandId": "fiat", "name": "Coupe", "slug": "coupe", "series": "Sport" },
    { "id": "fiat-croma", "brandId": "fiat", "name": "Croma", "slug": "croma", "series": "Croma" },
    { "id": "fiat-doblo-1", "brandId": "fiat", "name": "Doblo (223)", "slug": "doblo-1", "series": "Doblo", "keywords": ["1.3 Multijet", "1.9 JTD"] },
    { "id": "fiat-doblo-2", "brandId": "fiat", "name": "Doblo (263)", "slug": "doblo-2", "series": "Doblo", "keywords": ["Multijet"] },
    { "id": "fiat-doblo-3", "brandId": "fiat", "name": "Doblo (Mk3)", "slug": "doblo-3", "series": "Doblo" },
    { "id": "fiat-ducato-2", "brandId": "fiat", "name": "Ducato (244)", "slug": "ducato-2", "series": "Ducato", "keywords": ["2.3 JTD", "2.8 JTD"] },
    { "id": "fiat-ducato-3", "brandId": "fiat", "name": "Ducato (X250/X290)", "slug": "ducato-3", "series": "Ducato", "keywords": ["Multijet"] },
    { "id": "fiat-duna", "brandId": "fiat", "name": "Duna", "slug": "duna", "series": "Duna" },
    { "id": "fiat-fiorino", "brandId": "fiat", "name": "Fiorino", "slug": "fiorino", "series": "Fiorino" },
    { "id": "fiat-freemont", "brandId": "fiat", "name": "Freemont", "slug": "freemont", "series": "Freemont" },
    { "id": "fiat-fullback", "brandId": "fiat", "name": "Fullback", "slug": "fullback", "series": "Fullback" },
    { "id": "fiat-idea", "brandId": "fiat", "name": "Idea", "slug": "idea", "series": "Idea" },
    { "id": "fiat-linea", "brandId": "fiat", "name": "Linea", "slug": "linea", "series": "Linea" },
    { "id": "fiat-marea", "brandId": "fiat", "name": "Marea", "slug": "marea", "series": "Marea" },
    { "id": "fiat-multipla", "brandId": "fiat", "name": "Multipla", "slug": "multipla", "series": "Multipla" },
    { "id": "fiat-palio", "brandId": "fiat", "name": "Palio", "slug": "palio", "series": "Palio" },
    { "id": "fiat-panda-2", "brandId": "fiat", "name": "Panda (169)", "slug": "panda-2", "series": "Panda" },
    { "id": "fiat-panda-3", "brandId": "fiat", "name": "Panda (319)", "slug": "panda-3", "series": "Panda" },
    { "id": "fiat-punto-1", "brandId": "fiat", "name": "Punto I (176)", "slug": "punto-1", "series": "Punto" },
    { "id": "fiat-punto-1-cabrio", "brandId": "fiat", "name": "Punto I Cabrio", "slug": "punto-1-cabrio", "series": "Punto" },
    { "id": "fiat-punto-1-van", "brandId": "fiat", "name": "Punto I Van", "slug": "punto-1-van", "series": "Punto" },
    { "id": "fiat-punto-2", "brandId": "fiat", "name": "Punto II (188)", "slug": "punto-2", "series": "Punto" },
    { "id": "fiat-punto-2-van", "brandId": "fiat", "name": "Punto II Van", "slug": "punto-2-van", "series": "Punto" },
    { "id": "fiat-grande-punto", "brandId": "fiat", "name": "Grande Punto", "slug": "grande-punto", "series": "Punto" },
    { "id": "fiat-punto-evo", "brandId": "fiat", "name": "Punto Evo", "slug": "punto-evo", "series": "Punto" },
    { "id": "fiat-qubo", "brandId": "fiat", "name": "Qubo", "slug": "qubo", "series": "Qubo" },
    { "id": "fiat-regata", "brandId": "fiat", "name": "Regata", "slug": "regata", "series": "Regata" },
    { "id": "fiat-ritmo", "brandId": "fiat", "name": "Ritmo", "slug": "ritmo", "series": "Ritmo" },
    { "id": "fiat-scudo-1", "brandId": "fiat", "name": "Scudo (Mk1)", "slug": "scudo-1", "series": "Scudo" },
    { "id": "fiat-scudo-2", "brandId": "fiat", "name": "Scudo (Mk2)", "slug": "scudo-2", "series": "Scudo" },
    { "id": "fiat-sedici", "brandId": "fiat", "name": "Sedici", "slug": "sedici", "series": "Sedici" },
    { "id": "fiat-seicento", "brandId": "fiat", "name": "Seicento", "slug": "seicento", "series": "Seicento" },
    { "id": "fiat-siena", "brandId": "fiat", "name": "Siena", "slug": "siena", "series": "Siena" },
    { "id": "fiat-stilo", "brandId": "fiat", "name": "Stilo", "slug": "stilo", "series": "Stilo" },
    { "id": "fiat-strada", "brandId": "fiat", "name": "Strada", "slug": "strada", "series": "Strada" },
    { "id": "fiat-talento", "brandId": "fiat", "name": "Talento", "slug": "talento", "series": "Talento" },
    { "id": "fiat-tempra", "brandId": "fiat", "name": "Tempra", "slug": "tempra", "series": "Tempra" },
    { "id": "fiat-tipo-1", "brandId": "fiat", "name": "Tipo (160)", "slug": "tipo-1", "series": "Tipo" },
    { "id": "fiat-tipo-2", "brandId": "fiat", "name": "Tipo (356)", "slug": "tipo-2", "series": "Tipo" },
    { "id": "fiat-ulysse", "brandId": "fiat", "name": "Ulysse", "slug": "ulysse", "series": "Ulysse" },
    { "id": "fiat-uno", "brandId": "fiat", "name": "Uno", "slug": "uno", "series": "Uno" },
    { "id": "ford-6000-serie", "brandId": "ford", "name": "6000-Serie", "slug": "6000-serie", "series": "Haszonjármű" },
    { "id": "ford-b-max", "brandId": "ford", "name": "B-Max", "slug": "b-max", "series": "B-Max" },
    { "id": "ford-capri", "brandId": "ford", "name": "Capri", "slug": "capri", "series": "Sport" },
    { "id": "ford-capri-suv", "brandId": "ford", "name": "Capri SUV", "slug": "capri-suv", "series": "SUV" },
    { "id": "ford-cargo", "brandId": "ford", "name": "Cargo", "slug": "cargo", "series": "Haszonjármű" },
    { "id": "ford-c-max-2", "brandId": "ford", "name": "C-Max II (Mk2)", "slug": "c-max-2", "series": "C-Max" },
    { "id": "ford-focus-c-max-1", "brandId": "ford", "name": "Focus C-Max I (Mk1)", "slug": "focus-c-max-1", "series": "C-Max" },
    { "id": "ford-grand-c-max", "brandId": "ford", "name": "Grand C-Max", "slug": "grand-c-max", "series": "C-Max" },
    { "id": "ford-cougar", "brandId": "ford", "name": "Cougar", "slug": "cougar", "series": "Sport" },
    { "id": "ford-courier", "brandId": "ford", "name": "Courier", "slug": "courier", "series": "Haszonjármű" },
    { "id": "ford-econovan", "brandId": "ford", "name": "Econovan", "slug": "econovan", "series": "Haszonjármű" },
    { "id": "ford-ecosport", "brandId": "ford", "name": "EcoSport", "slug": "ecosport", "series": "SUV" },
    { "id": "ford-edge", "brandId": "ford", "name": "Edge", "slug": "edge", "series": "SUV" },
    { "id": "ford-escort", "brandId": "ford", "name": "Escort", "slug": "escort", "series": "Escort" },
    { "id": "ford-festiva", "brandId": "ford", "name": "Festiva", "slug": "festiva", "series": "Festiva" },
    { "id": "ford-fiesta-1", "brandId": "ford", "name": "Fiesta I (Mk1)", "slug": "fiesta-1", "series": "Fiesta" },
    { "id": "ford-fiesta-2", "brandId": "ford", "name": "Fiesta II (Mk2)", "slug": "fiesta-2", "series": "Fiesta" },
    { "id": "ford-fiesta-3", "brandId": "ford", "name": "Fiesta III (Mk3)", "slug": "fiesta-3", "series": "Fiesta" },
    { "id": "ford-fiesta-4", "brandId": "ford", "name": "Fiesta IV (Mk4)", "slug": "fiesta-4", "series": "Fiesta" },
    { "id": "ford-fiesta-5", "brandId": "ford", "name": "Fiesta V (Mk5)", "slug": "fiesta-5", "series": "Fiesta" },
    { "id": "ford-fiesta-6", "brandId": "ford", "name": "Fiesta VI (Mk6)", "slug": "fiesta-6", "series": "Fiesta" },
    { "id": "ford-fiesta-7", "brandId": "ford", "name": "Fiesta VII (Mk7)", "slug": "fiesta-7", "series": "Fiesta" },
    { "id": "ford-fiesta-8", "brandId": "ford", "name": "Fiesta VIII (Mk8)", "slug": "fiesta-8", "series": "Fiesta" },
    { "id": "ford-fiesta-van", "brandId": "ford", "name": "Fiesta Van", "slug": "fiesta-van", "series": "Fiesta" },
    { "id": "ford-focus-1", "brandId": "ford", "name": "Focus I (Mk1)", "slug": "focus-1", "series": "Focus" },
    { "id": "ford-focus-2", "brandId": "ford", "name": "Focus II (Mk2)", "slug": "focus-2", "series": "Focus" },
    { "id": "ford-focus-3", "brandId": "ford", "name": "Focus III (Mk3)", "slug": "focus-3", "series": "Focus" },
    { "id": "ford-focus-4", "brandId": "ford", "name": "Focus IV (Mk4)", "slug": "focus-4", "series": "Focus" },
    { "id": "ford-fusion", "brandId": "ford", "name": "Fusion", "slug": "fusion", "series": "Fusion" },
    { "id": "ford-galaxy", "brandId": "ford", "name": "Galaxy", "slug": "galaxy", "series": "Galaxy" },
    { "id": "ford-granada", "brandId": "ford", "name": "Granada", "slug": "granada", "series": "Granada" },
    { "id": "ford-grand", "brandId": "ford", "name": "Grand", "slug": "grand", "series": "Grand" },
    { "id": "ford-ka", "brandId": "ford", "name": "Ka", "slug": "ka", "series": "Ka" },
    { "id": "ford-ka-plus", "brandId": "ford", "name": "Ka Plus", "slug": "ka-plus", "series": "Ka" },
    { "id": "ford-kuga", "brandId": "ford", "name": "Kuga", "slug": "kuga", "series": "Kuga" },
    { "id": "ford-maverick", "brandId": "ford", "name": "Maverick", "slug": "maverick", "series": "SUV" },
    { "id": "ford-mondeo-1", "brandId": "ford", "name": "Mondeo I (Mk1)", "slug": "mondeo-1", "series": "Mondeo" },
    { "id": "ford-mondeo-2", "brandId": "ford", "name": "Mondeo II (Mk2)", "slug": "mondeo-2", "series": "Mondeo" },
    { "id": "ford-mondeo-3", "brandId": "ford", "name": "Mondeo III (Mk3)", "slug": "mondeo-3", "series": "Mondeo" },
    { "id": "ford-mondeo-4", "brandId": "ford", "name": "Mondeo IV (Mk4)", "slug": "mondeo-4", "series": "Mondeo" },
    { "id": "ford-mondeo-5", "brandId": "ford", "name": "Mondeo V (Mk5)", "slug": "mondeo-5", "series": "Mondeo" },
    { "id": "ford-orion", "brandId": "ford", "name": "Orion", "slug": "orion", "series": "Orion" },
    { "id": "ford-p-100", "brandId": "ford", "name": "P 100", "slug": "p-100", "series": "Haszonjármű" },
    { "id": "ford-probe", "brandId": "ford", "name": "Probe", "slug": "probe", "series": "Sport" },
    { "id": "ford-puma", "brandId": "ford", "name": "Puma", "slug": "puma", "series": "Puma" },
    { "id": "ford-ranger", "brandId": "ford", "name": "Ranger", "slug": "ranger", "series": "Ranger" },
    { "id": "ford-scorpio", "brandId": "ford", "name": "Scorpio", "slug": "scorpio", "series": "Scorpio" },
    { "id": "ford-sierra", "brandId": "ford", "name": "Sierra", "slug": "sierra", "series": "Sierra" },
    { "id": "ford-s-max-1", "brandId": "ford", "name": "S-Max I (Mk1)", "slug": "s-max-1", "series": "S-Max" },
    { "id": "ford-s-max-2", "brandId": "ford", "name": "S-Max II (Mk2)", "slug": "s-max-2", "series": "S-Max" },
    { "id": "ford-street", "brandId": "ford", "name": "Street", "slug": "street", "series": "Sport" },
    { "id": "ford-taunus", "brandId": "ford", "name": "Taunus", "slug": "taunus", "series": "Taunus" },
    { "id": "ford-taurus-3", "brandId": "ford", "name": "Taurus III", "slug": "taurus-3", "series": "Taurus" },
    { "id": "ford-transit", "brandId": "ford", "name": "Transit", "slug": "transit", "series": "Transit" },
    { "id": "ford-transit-connect", "brandId": "ford", "name": "Transit Connect", "slug": "transit-connect", "series": "Transit" },
    { "id": "ford-transit-courier", "brandId": "ford", "name": "Transit Courier", "slug": "transit-courier", "series": "Transit" },
    { "id": "mb-a-w168", "brandId": "mercedes", "name": "(W168)", "slug": "a-w168", "series": "A-Class", "keywords": ["W168", "A140", "A160", "A170 CDI", "A190"] },
    { "id": "mb-a-w169", "brandId": "mercedes", "name": "(W169)", "slug": "a-w169", "series": "A-Class", "keywords": ["W169", "A150", "A170", "A180 CDI", "A200 CDI"] },
    { "id": "mb-a-w176", "brandId": "mercedes", "name": "(W176)", "slug": "a-w176", "series": "A-Class", "keywords": ["W176", "A180", "A200", "A220 CDI", "A250", "A45 AMG"] },
    { "id": "mb-a-w177", "brandId": "mercedes", "name": "(W177)", "slug": "a-w177", "series": "A-Class", "keywords": ["W177", "A180", "A200", "A250e", "A35 AMG"] },
    { "id": "mb-b-w245", "brandId": "mercedes", "name": "(W245)", "slug": "b-w245", "series": "B-Class", "keywords": ["W245", "B180 CDI", "B200 CDI", "B200 Turbo"] },
    { "id": "mb-b-w246", "brandId": "mercedes", "name": "(W246)", "slug": "b-w246", "series": "B-Class", "keywords": ["W246", "B180", "B200", "B220 CDI"] },
    { "id": "mb-b-w247", "brandId": "mercedes", "name": "(W247)", "slug": "b-w247", "series": "B-Class", "keywords": ["W247", "B180", "B200", "B250e"] },
    { "id": "mb-c-w202", "brandId": "mercedes", "name": "(W202)", "slug": "c-w202", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C230", "C240", "C250", "C280"] },
    { "id": "mb-c-w203", "brandId": "mercedes", "name": "(W203)", "slug": "c-w203", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C230", "C240", "C270", "C280", "C320", "C350", "OM611", "OM646", "OM612", "M111", "M271", "M272"] },
    { "id": "mb-c-w204", "brandId": "mercedes", "name": "(W204)", "slug": "c-w204", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C250", "C300", "C320", "C350", "C63"] },
    { "id": "mb-c-w205", "brandId": "mercedes", "name": "(W205)", "slug": "c-w205", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C250", "C300", "C350", "C400", "C43", "C63"] },
    { "id": "mb-c-w206", "brandId": "mercedes", "name": "(W206)", "slug": "c-w206", "series": "C-Class", "keywords": ["C180", "C200", "C220", "C300", "C400", "C43", "C63"] },
    { "id": "mb-cla-c117", "brandId": "mercedes", "name": "(C117/X117)", "slug": "cla-c117", "series": "CLA" },
    { "id": "mb-cla-c118", "brandId": "mercedes", "name": "(C118/X118)", "slug": "cla-c118", "series": "CLA" },
    { "id": "mb-clk-w208", "brandId": "mercedes", "name": "(W208)", "slug": "clk-w208", "series": "CLK" },
    { "id": "mb-clk-w209", "brandId": "mercedes", "name": "(W209)", "slug": "clk-w209", "series": "CLK" },
    { "id": "mb-cls-w219", "brandId": "mercedes", "name": "(W219)", "slug": "cls-w219", "series": "CLS" },
    { "id": "mb-cls-w218", "brandId": "mercedes", "name": "(W218)", "slug": "cls-w218", "series": "CLS" },
    { "id": "mb-e-w210", "brandId": "mercedes", "name": "(W210)", "slug": "e-w210", "series": "E-Class", "keywords": ["W210", "Pápaszemes", "Béka lámpás", "E200", "E220", "E230", "E240", "E250", "E270", "E280", "E290", "E300", "E320", "E420", "E430", "E50", "E55"] },
    { "id": "mb-e-w211", "brandId": "mercedes", "name": "(W211)", "slug": "e-w211", "series": "E-Class", "keywords": ["E200", "E220", "E240", "E270", "E280", "E300", "E320", "E350", "E400", "E420", "E500", "E55", "E63", "OM646", "OM647", "OM648", "OM642", "M271", "M272"] },
    { "id": "mb-e-w212", "brandId": "mercedes", "name": "(W212)", "slug": "e-w212", "series": "E-Class", "keywords": ["E200", "E220", "E250", "E300", "E350", "E400", "E500", "E63"] },
    { "id": "mb-e-w213", "brandId": "mercedes", "name": "(W213)", "slug": "e-w213", "series": "E-Class", "keywords": ["E200", "E220", "E300", "E350", "E400", "E450", "E53", "E63"] },
    { "id": "mb-e-w214", "brandId": "mercedes", "name": "(W214)", "slug": "e-w214", "series": "E-Class" },
    { "id": "mb-cl-c215", "brandId": "mercedes", "name": "(C215)", "slug": "cl-c215", "series": "CL" },
    { "id": "mb-cl-c216", "brandId": "mercedes", "name": "(C216)", "slug": "cl-c216", "series": "CL" },
    { "id": "mb-clc-cl203", "brandId": "mercedes", "name": "(CL203)", "slug": "clc", "series": "CLC" },
    { "id": "mb-r-w251", "brandId": "mercedes", "name": "(W251)", "slug": "r-w251", "series": "R-Class" },
    { "id": "mb-sl-r230", "brandId": "mercedes", "name": "(R230)", "slug": "sl-r230", "series": "SL" },
    { "id": "mb-sl-r231", "brandId": "mercedes", "name": "(R231)", "slug": "sl-r231", "series": "SL" },
    { "id": "mb-slc-r172", "brandId": "mercedes", "name": "(R172)", "slug": "slc", "series": "SLC" },
    { "id": "mb-slr", "brandId": "mercedes", "name": "SLR McLaren", "slug": "slr", "series": "SLR" },
    { "id": "mb-sls", "brandId": "mercedes", "name": "SLS AMG", "slug": "sls", "series": "SLS" },
    { "id": "mb-x-w470", "brandId": "mercedes", "name": "(W470)", "slug": "x-w470", "series": "X-Class" },
    { "id": "mb-eqa", "brandId": "mercedes", "name": "EQA", "slug": "eqa", "series": "EQ" },
    { "id": "mb-eqb", "brandId": "mercedes", "name": "EQB", "slug": "eqb", "series": "EQ" },
    { "id": "mb-eqc", "brandId": "mercedes", "name": "EQC", "slug": "eqc", "series": "EQ" },
    { "id": "mb-eqe", "brandId": "mercedes", "name": "EQE", "slug": "eqe", "series": "EQ" },
    { "id": "mb-eqs", "brandId": "mercedes", "name": "EQS", "slug": "eqs", "series": "EQ" },
    { "id": "mb-eqv", "brandId": "mercedes", "name": "EQV", "slug": "eqv", "series": "EQ" },
    { "id": "mb-g-class", "brandId": "mercedes", "name": "(W463)", "slug": "g-class", "series": "G-Class" },
    { "id": "mb-gl-x164", "brandId": "mercedes", "name": "(X164)", "slug": "gl-x164", "series": "GL" },
    { "id": "mb-gla-x156", "brandId": "mercedes", "name": "(X156)", "slug": "gla-x156", "series": "GLA" },
    { "id": "mb-gla-h247", "brandId": "mercedes", "name": "(H247)", "slug": "gla-h247", "series": "GLA" },
    { "id": "mb-glb-x247", "brandId": "mercedes", "name": "(X247)", "slug": "glb-x247", "series": "GLB" },
    { "id": "mb-glc-x253", "brandId": "mercedes", "name": "(X253)", "slug": "glc-x253", "series": "GLC" },
    { "id": "mb-gle-w166", "brandId": "mercedes", "name": "GLE (W166)", "slug": "gle-w166", "series": "GLE" },
    { "id": "mb-gle-w167", "brandId": "mercedes", "name": "GLE (W167)", "slug": "gle-w167", "series": "GLE" },
    { "id": "mb-gls-x166", "brandId": "mercedes", "name": "GLS (X166)", "slug": "gls-x166", "series": "GLS" },
    { "id": "mb-gls-x167", "brandId": "mercedes", "name": "GLS (X167)", "slug": "gls-x167", "series": "GLS" },
    { "id": "mb-m-w163", "brandId": "mercedes", "name": "(W163)", "slug": "m-w163", "series": "M-Class" },
    { "id": "mb-m-w164", "brandId": "mercedes", "name": "(W164)", "slug": "m-w164", "series": "M-Class" },
    { "id": "mb-m-w166", "brandId": "mercedes", "name": "(W166)", "slug": "m-w166", "series": "M-Class" },
    { "id": "mb-s-w220", "brandId": "mercedes", "name": "(W220)", "slug": "s-w220", "series": "S-Class", "keywords": ["W220", "S320 CDI", "S400 CDI", "S500", "S600"] },
    { "id": "mb-s-w221", "brandId": "mercedes", "name": "(W221)", "slug": "s-w221", "series": "S-Class", "keywords": ["W221", "S320 CDI", "S350", "S500", "S63 AMG"] },
    { "id": "mb-s-w222", "brandId": "mercedes", "name": "(W222)", "slug": "s-w222", "series": "S-Class", "keywords": ["W222", "S350d", "S400d", "S500", "S560", "S63 AMG"] },
    { "id": "mb-s-w223", "brandId": "mercedes", "name": "(W223)", "slug": "s-w223", "series": "S-Class" },
    { "id": "mb-sls-slk-r170", "brandId": "mercedes", "name": "(R170)", "slug": "slk-r170", "series": "SLK" },
    { "id": "mb-sls-slk-r171", "brandId": "mercedes", "name": "(R171)", "slug": "slk-r171", "series": "SLK" },
    { "id": "mb-sprinter-w901", "brandId": "mercedes", "name": "(W901-905)", "slug": "sprinter-w901", "series": "Sprinter" },
    { "id": "mb-sprinter-w906", "brandId": "mercedes", "name": "(W906/NCV3)", "slug": "sprinter-w906", "series": "Sprinter" },
    { "id": "mb-sprinter-w907", "brandId": "mercedes", "name": "(W907/W910)", "slug": "sprinter-w907", "series": "Sprinter" },
    { "id": "mb-citan", "brandId": "mercedes", "name": "Citan", "slug": "citan", "series": "Citan" },
    { "id": "mb-vito-w638", "brandId": "mercedes", "name": "(W638)", "slug": "vito-w638", "series": "Vito" },
    { "id": "mb-vito-w639", "brandId": "mercedes", "name": "(W639)", "slug": "vito-w639", "series": "Vito" },
    { "id": "mb-vito-w447", "brandId": "mercedes", "name": "(W447)", "slug": "vito-w447", "series": "Vito" },
    { "id": "opel-adam", "brandId": "opel", "name": "Adam", "slug": "adam", "series": "Adam", "keywords": ["S", "Rocks", "1.2", "1.4"] },
    { "id": "opel-agila-a", "brandId": "opel", "name": "Agila A (Mk1 / H00)", "slug": "agila-a", "series": "Agila", "keywords": ["1.0", "1.2 16V"] },
    { "id": "opel-agila-b", "brandId": "opel", "name": "Agila B (Mk2 / H08)", "slug": "agila-b", "series": "Agila", "keywords": ["1.0", "1.2", "1.3 CDTI"] },
    { "id": "opel-ampera", "brandId": "opel", "name": "Ampera", "slug": "ampera", "series": "Ampera" },
    { "id": "opel-antara", "brandId": "opel", "name": "Antara (L07)", "slug": "antara", "series": "Antara", "keywords": ["2.0 CDTI", "2.2 CDTI"] },
    { "id": "opel-ascona", "brandId": "opel", "name": "Ascona (A / B / C)", "slug": "ascona", "series": "Ascona" },
    { "id": "opel-astra-f", "brandId": "opel", "name": "Astra F (Mk1 / T92)", "slug": "astra-f", "series": "Astra", "keywords": ["GSI", "1.4", "1.6", "1.7 TD"] },
    { "id": "opel-astra-g", "brandId": "opel", "name": "Astra G (Mk2 / T98)", "slug": "astra-g", "series": "Astra", "keywords": ["OPC", "1.4 16V", "1.6 16V", "1.7 DTI", "2.0 DT"] },
    { "id": "opel-astra-h", "brandId": "opel", "name": "Astra H (Mk3 / A04)", "slug": "astra-h", "series": "Astra", "keywords": ["OPC", "GTC", "TwinTop", "1.7 CDTI", "1.9 CDTI"] },
    { "id": "opel-astra-j", "brandId": "opel", "name": "Astra J (Mk4 / P10)", "slug": "astra-j", "series": "Astra", "keywords": ["OPC", "GTC", "1.7 CDTI", "1.4 Turbo"] },
    { "id": "opel-astra-k", "brandId": "opel", "name": "Astra K (Mk5 / B16)", "slug": "astra-k", "series": "Astra", "keywords": ["1.6 CDTI", "1.4 Turbo"] },
    { "id": "opel-astra-l", "brandId": "opel", "name": "Astra L (Mk6 / OV51)", "slug": "astra-l", "series": "Astra" },
    { "id": "opel-calibra", "brandId": "opel", "name": "Calibra (C89)", "slug": "calibra", "series": "Calibra" },
    { "id": "opel-campo", "brandId": "opel", "name": "Campo (TF)", "slug": "campo", "series": "Pickup" },
    { "id": "opel-cascada", "brandId": "opel", "name": "Cascada (W13)", "slug": "cascada", "series": "Cascada" },
    { "id": "opel-combo-a", "brandId": "opel", "name": "Combo A (Mk1 / Kadett E)", "slug": "combo-a", "series": "Combo" },
    { "id": "opel-combo-b", "brandId": "opel", "name": "Combo B (Mk2 / 71)", "slug": "combo-b", "series": "Combo" },
    { "id": "opel-combo-c", "brandId": "opel", "name": "Combo C (Mk3 / XC)", "slug": "combo-c", "series": "Combo" },
    { "id": "opel-combo-d", "brandId": "opel", "name": "Combo D (Mk4 / X12)", "slug": "combo-d", "series": "Combo" },
    { "id": "opel-combo-e", "brandId": "opel", "name": "Combo E (Mk5 / K9)", "slug": "combo-e", "series": "Combo" },
    { "id": "opel-commodore", "brandId": "opel", "name": "Commodore (A / B / C)", "slug": "commodore", "series": "Commodore" },
    { "id": "opel-corsa-a", "brandId": "opel", "name": "Corsa A (Mk1 / S83)", "slug": "corsa-a", "series": "Corsa" },
    { "id": "opel-corsa-b", "brandId": "opel", "name": "Corsa B (Mk2 / S93)", "slug": "corsa-b", "series": "Corsa" },
    { "id": "opel-corsa-c", "brandId": "opel", "name": "Corsa C (Mk3 / X01)", "slug": "corsa-c", "series": "Corsa" },
    { "id": "opel-corsa-d", "brandId": "opel", "name": "Corsa D (Mk4 / S07)", "slug": "corsa-d", "series": "Corsa" },
    { "id": "opel-corsa-e", "brandId": "opel", "name": "Corsa E (Mk5 / X15)", "slug": "corsa-e", "series": "Corsa" },
    { "id": "opel-corsa-f", "brandId": "opel", "name": "Corsa F (Mk6 / P2JO)", "slug": "corsa-f", "series": "Corsa" },
    { "id": "opel-corsa-f-van", "brandId": "opel", "name": "Corsa F dobozos (Van)", "slug": "corsa-f-van", "series": "Corsa" },
    { "id": "opel-crossland", "brandId": "opel", "name": "Crossland / Crossland X (P17)", "slug": "crossland", "series": "Crossland" },
    { "id": "opel-frontera", "brandId": "opel", "name": "Frontera (A / B)", "slug": "frontera", "series": "Frontera" },
    { "id": "opel-grandland", "brandId": "opel", "name": "Grandland / Grandland X (A18)", "slug": "grandland", "series": "Grandland" },
    { "id": "opel-insignia-a", "brandId": "opel", "name": "Insignia A (G09)", "slug": "insignia-a", "series": "Insignia" },
    { "id": "opel-insignia-b", "brandId": "opel", "name": "Insignia B (Z18)", "slug": "insignia-b", "series": "Insignia" },
    { "id": "opel-kadett", "brandId": "opel", "name": "Kadett (C / D / E)", "slug": "kadett", "series": "Kadett" },
    { "id": "opel-karl", "brandId": "opel", "name": "Karl (D10)", "slug": "karl", "series": "Karl" },
    { "id": "opel-manta", "brandId": "opel", "name": "Manta (A / B)", "slug": "manta", "series": "Manta" },
    { "id": "opel-meriva-a", "brandId": "opel", "name": "Meriva A (X03)", "slug": "meriva-a", "series": "Meriva" },
    { "id": "opel-meriva-b", "brandId": "opel", "name": "Meriva B (S10)", "slug": "meriva-b", "series": "Meriva" },
    { "id": "opel-mokka-1", "brandId": "opel", "name": "Mokka I (Mk1 / J13)", "slug": "mokka-1", "series": "Mokka" },
    { "id": "opel-mokka-2", "brandId": "opel", "name": "Mokka II (Mk2 / P2QO)", "slug": "mokka-2", "series": "Mokka" },
    { "id": "opel-monza", "brandId": "opel", "name": "Monza (A1 / A2)", "slug": "monza", "series": "Monza" },
    { "id": "opel-movano", "brandId": "opel", "name": "Movano (A / B / C)", "slug": "movano", "series": "Movano" },
    { "id": "opel-omega-a", "brandId": "opel", "name": "Omega A (Mk1 / V87)", "slug": "omega-a", "series": "Omega" },
    { "id": "opel-omega-b", "brandId": "opel", "name": "Omega B (Mk2 / V94)", "slug": "omega-b", "series": "Omega" },
    { "id": "opel-rekord", "brandId": "opel", "name": "Rekord (A / B / C / D / E)", "slug": "rekord", "series": "Rekord" },
    { "id": "opel-senator", "brandId": "opel", "name": "Senator (A / B)", "slug": "senator", "series": "Senator" },
    { "id": "opel-signum", "brandId": "opel", "name": "Signum (Z03)", "slug": "signum", "series": "Signum" },
    { "id": "opel-sintra", "brandId": "opel", "name": "Sintra (GMX110)", "slug": "sintra", "series": "Sintra" },
    { "id": "opel-speedster", "brandId": "opel", "name": "Speedster (E01)", "slug": "speedster", "series": "Speedster" },
    { "id": "opel-tigra", "brandId": "opel", "name": "Tigra (S93 / X04)", "slug": "tigra", "series": "Tigra" },
    { "id": "opel-vectra-a", "brandId": "opel", "name": "Vectra A (Mk1 / J89)", "slug": "vectra-a", "series": "Vectra" },
    { "id": "opel-vectra-b", "brandId": "opel", "name": "Vectra B (Mk2 / J96)", "slug": "vectra-b", "series": "Vectra" },
    { "id": "opel-vectra-c", "brandId": "opel", "name": "Vectra C (Mk3 / Z02)", "slug": "vectra-c", "series": "Vectra" },
    { "id": "opel-vivaro-1", "brandId": "opel", "name": "Vivaro I (Mk1 / X83)", "slug": "vivaro-1", "series": "Vivaro" },
    { "id": "opel-vivaro-2", "brandId": "opel", "name": "Vivaro II (Mk2 / X82)", "slug": "vivaro-2", "series": "Vivaro" },
    { "id": "opel-vivaro-3", "brandId": "opel", "name": "Vivaro III (Mk3 / V)", "slug": "vivaro-3", "series": "Vivaro" },
    { "id": "opel-zafira-a", "brandId": "opel", "name": "Zafira A (Mk1 / T98)", "slug": "zafira-a", "series": "Zafira" },
    { "id": "opel-zafira-b", "brandId": "opel", "name": "Zafira B (Mk2 / A05)", "slug": "zafira-b", "series": "Zafira" },
    { "id": "opel-zafira-c", "brandId": "opel", "name": "Zafira C (Mk3 / P12)", "slug": "zafira-c", "series": "Zafira" },
    { "id": "opel-zafira-life", "brandId": "opel", "name": "Zafira Life (K0)", "slug": "zafira-life", "series": "Zafira" },
    { "id": "volvo-140", "brandId": "volvo", "name": "140", "slug": "volvo-140", "series": "100-as széria" },
    { "id": "volvo-240", "brandId": "volvo", "name": "240 (Mk1)", "slug": "240", "series": "200-as széria" },
    { "id": "volvo-340", "brandId": "volvo", "name": "340 / 360", "slug": "340", "series": "300-as széria" },
    { "id": "volvo-440", "brandId": "volvo", "name": "440", "slug": "440", "series": "400-as széria" },
    { "id": "volvo-460", "brandId": "volvo", "name": "460", "slug": "volvo-460", "series": "400-as széria" },
    { "id": "volvo-480", "brandId": "volvo", "name": "480", "slug": "volvo-480", "series": "400-as széria" },
    { "id": "volvo-740", "brandId": "volvo", "name": "740", "slug": "740", "series": "700-as széria" },
    { "id": "volvo-760", "brandId": "volvo", "name": "760", "slug": "volvo-760", "series": "700-as széria" },
    { "id": "volvo-850", "brandId": "volvo", "name": "850", "slug": "850", "series": "800-as széria" },
    { "id": "volvo-940", "brandId": "volvo", "name": "940", "slug": "940", "series": "900-as széria" },
    { "id": "volvo-960", "brandId": "volvo", "name": "960", "slug": "volvo-960", "series": "900-as széria" },
    { "id": "volvo-c30", "brandId": "volvo", "name": "C30 (Mk1 / 533)", "slug": "c30", "series": "C30" },
    { "id": "volvo-c70-1", "brandId": "volvo", "name": "C70 I (Mk1 / 872/873)", "slug": "c70-1", "series": "C70" },
    { "id": "volvo-c70-2", "brandId": "volvo", "name": "C70 II (Mk2 / 542)", "slug": "c70", "series": "C70" },
    { "id": "volvo-ex30", "brandId": "volvo", "name": "EX30 (Mk1)", "slug": "ex30", "series": "EX30" },
    { "id": "volvo-f10", "brandId": "volvo", "name": "F 10", "slug": "volvo-f10", "series": "Truck" },
    { "id": "volvo-f12", "brandId": "volvo", "name": "F 12", "slug": "volvo-f12", "series": "Truck" },
    { "id": "volvo-f16", "brandId": "volvo", "name": "F 16", "slug": "volvo-f16", "series": "Truck" },
    { "id": "volvo-fh", "brandId": "volvo", "name": "FH", "slug": "volvo-fh", "series": "Truck" },
    { "id": "volvo-fh12", "brandId": "volvo", "name": "FH 12", "slug": "volvo-fh12", "series": "Truck" },
    { "id": "volvo-fl", "brandId": "volvo", "name": "FL", "slug": "volvo-fl", "series": "Truck" },
    { "id": "volvo-flc", "brandId": "volvo", "name": "FLC", "slug": "volvo-flc", "series": "Truck" },
    { "id": "volvo-s40-1", "brandId": "volvo", "name": "S40 I (Mk1 / VS)", "slug": "s40-1", "series": "S40" },
    { "id": "volvo-s40-2", "brandId": "volvo", "name": "S40 II (Mk2 / MS)", "slug": "s40-2", "series": "S40" },
    { "id": "volvo-s60-1", "brandId": "volvo", "name": "S60 I (Mk1 / RS)", "slug": "s60-1", "series": "S60", "keywords": ["D5", "2.4D", "T5", "R"] },
    { "id": "volvo-s60-2", "brandId": "volvo", "name": "S60 II (Mk2 / Y20)", "slug": "s60-2", "series": "S60", "keywords": ["D2", "D3", "D4", "D5", "T4", "T5", "T6"] },
    { "id": "volvo-s60-3", "brandId": "volvo", "name": "S60 III (Mk3 / Z)", "slug": "s60-3", "series": "S60" },
    { "id": "volvo-s70", "brandId": "volvo", "name": "S70 (Mk1 / LS)", "slug": "s70", "series": "S70" },
    { "id": "volvo-s80-1", "brandId": "volvo", "name": "S80 I (Mk1 / TS)", "slug": "s80-1", "series": "S80" },
    { "id": "volvo-s80-2", "brandId": "volvo", "name": "S80 II (Mk2 / AS)", "slug": "s80-2", "series": "S80" },
    { "id": "volvo-s90", "brandId": "volvo", "name": "S90 / V90", "slug": "s90", "series": "S90" },
    { "id": "volvo-s90-2", "brandId": "volvo", "name": "S90 II (Mk2 / 234)", "slug": "volvo-s90-2", "series": "S90" },
    { "id": "volvo-v40-1", "brandId": "volvo", "name": "V40 I (Mk1 / VW)", "slug": "v40-1", "series": "V40", "keywords": ["1.9 TD", "1.9 D", "T4"] },
    { "id": "volvo-v40-2", "brandId": "volvo", "name": "V40 II (Mk2 / MD)", "slug": "v40-2", "series": "V40", "keywords": ["D2", "D3", "D4", "Cross Country"] },
    { "id": "volvo-v50", "brandId": "volvo", "name": "V50 (Mk1 / MW)", "slug": "v50", "series": "V50" },
    { "id": "volvo-v60-1", "brandId": "volvo", "name": "V60 I (Mk1 / F)", "slug": "v60", "series": "V60" },
    { "id": "volvo-v60-2", "brandId": "volvo", "name": "V60 II (Mk2 / Z)", "slug": "volvo-v60-2", "series": "V60" },
    { "id": "volvo-v70-1", "brandId": "volvo", "name": "V70 I (Mk1 / LV)", "slug": "v70-1", "series": "V70" },
    { "id": "volvo-v70-2", "brandId": "volvo", "name": "V70 II (Mk2 / SW)", "slug": "v70-2", "series": "V70" },
    { "id": "volvo-v70-3", "brandId": "volvo", "name": "V70 III (Mk3 / BW)", "slug": "v70-3", "series": "V70" },
    { "id": "volvo-v90-2", "brandId": "volvo", "name": "V90 II (Mk2 / 235)", "slug": "volvo-v90-2", "series": "V90" },
    { "id": "volvo-xc40", "brandId": "volvo", "name": "XC40 (Mk1 / 536)", "slug": "xc40", "series": "XC40" },
    { "id": "volvo-xc60-1", "brandId": "volvo", "name": "XC60 I (Mk1 / Y20)", "slug": "xc60-1", "series": "XC60", "keywords": ["D3", "D4", "D5"] },
    { "id": "volvo-xc60-2", "brandId": "volvo", "name": "XC60 II (Mk2 / UZN)", "slug": "xc60-2", "series": "XC60" },
    { "id": "volvo-xc70-1", "brandId": "volvo", "name": "XC70 I (Mk1 / LV)", "slug": "xc70-1", "series": "XC70" },
    { "id": "volvo-xc70-2", "brandId": "volvo", "name": "XC70 II (Mk2 / SW)", "slug": "xc70-2", "series": "XC70" },
    { "id": "volvo-xc70-3", "brandId": "volvo", "name": "XC70 III (Mk3 / BW)", "slug": "xc70-3", "series": "XC70" },
    { "id": "volvo-xc90-1", "brandId": "volvo", "name": "XC90 I (Mk1 / C)", "slug": "xc90-1", "series": "XC90", "keywords": ["D5", "2.4 D5", "T6", "V8"] },
    { "id": "volvo-xc90-2", "brandId": "volvo", "name": "XC90 II (Mk2 / V)", "slug": "xc90-2", "series": "XC90" },
    { "id": "iveco-daily-3", "brandId": "iveco", "name": "Daily (Mk3)", "slug": "daily-3", "series": "Daily" },
    { "id": "iveco-daily-4", "brandId": "iveco", "name": "Daily (Mk4/5)", "slug": "daily-4", "series": "Daily" },
    { "id": "iveco-daily-6", "brandId": "iveco", "name": "Daily (Mk6)", "slug": "daily-6", "series": "Daily" },
    { "id": "iveco-eurocargo", "brandId": "iveco", "name": "Eurocargo", "slug": "eurocargo", "series": "Truck" },
    { "id": "iveco-stralis", "brandId": "iveco", "name": "Stralis", "slug": "stralis", "series": "Truck" },
    { "id": "iveco-sway", "brandId": "iveco", "name": "S-Way", "slug": "sway", "series": "Truck" },
    { "id": "jaguar-xf", "brandId": "jaguar", "name": "XF", "slug": "xf", "series": "XF" },
    { "id": "jaguar-xj", "brandId": "jaguar", "name": "XJ", "slug": "xj", "series": "XJ" },
    { "id": "jaguar-xe", "brandId": "jaguar", "name": "XE", "slug": "xe", "series": "XE" },
    { "id": "jaguar-fpace", "brandId": "jaguar", "name": "F-Pace", "slug": "fpace", "series": "F-Pace" },
    { "id": "jaguar-epace", "brandId": "jaguar", "name": "E-Pace", "slug": "epace", "series": "E-Pace" },
    { "id": "jaguar-ftype", "brandId": "jaguar", "name": "F-Type", "slug": "ftype", "series": "F-Type" },
    { "id": "jaguar-ipace", "brandId": "jaguar", "name": "I-Pace", "slug": "ipace", "series": "I-Pace" },
    { "id": "jaguar-stype", "brandId": "jaguar", "name": "S-Type", "slug": "stype", "series": "S-Type" },
    { "id": "jaguar-xk", "brandId": "jaguar", "name": "XK", "slug": "xk", "series": "XK" },
    { "id": "jaguar-xtype", "brandId": "jaguar", "name": "X-Type", "slug": "xtype", "series": "X-Type" },
    { "id": "jeep-cherokee", "brandId": "jeep", "name": "Cherokee", "slug": "cherokee", "series": "Cherokee" },
    { "id": "jeep-compass", "brandId": "jeep", "name": "Compass", "slug": "compass", "series": "Compass" },
    { "id": "jeep-grand-cherokee", "brandId": "jeep", "name": "Grand Cherokee", "slug": "grand-cherokee", "series": "Grand Cherokee" },
    { "id": "jeep-renegade", "brandId": "jeep", "name": "Renegade", "slug": "renegade", "series": "Renegade" },
    { "id": "jeep-wrangler", "brandId": "jeep", "name": "Wrangler", "slug": "wrangler", "series": "Wrangler" },
    { "id": "jeep-commander", "brandId": "jeep", "name": "Commander", "slug": "commander", "series": "Commander" },
    { "id": "jeep-gladiator", "brandId": "jeep", "name": "Gladiator", "slug": "gladiator", "series": "Gladiator" },
    { "id": "jeep-patriot", "brandId": "jeep", "name": "Patriot", "slug": "patriot", "series": "Patriot" },
    { "id": "jeep-avenger", "brandId": "jeep", "name": "Avenger", "slug": "avenger", "series": "Avenger" },
    { "id": "jeep-wagoneer", "brandId": "jeep", "name": "Wagoneer", "slug": "wagoneer", "series": "Wagoneer" },
    { "id": "lada-niva", "brandId": "lada", "name": "Niva / 4x4", "slug": "niva", "series": "Niva" },
    { "id": "lada-2101", "brandId": "lada", "name": "1200 / 2101", "slug": "2101", "series": "Zsiguli" },
    { "id": "lada-2105", "brandId": "lada", "name": "2105 / 2107", "slug": "2105", "series": "Zsiguli" },
    { "id": "lada-granta", "brandId": "lada", "name": "Granta", "slug": "granta", "series": "Granta" },
    { "id": "lada-kalina", "brandId": "lada", "name": "Kalina", "slug": "kalina", "series": "Kalina" },
    { "id": "lada-priora", "brandId": "lada", "name": "Priora", "slug": "priora", "series": "Priora" },
    { "id": "lada-samara", "brandId": "lada", "name": "Samara", "slug": "samara", "series": "Samara" },
    { "id": "lada-vesta", "brandId": "lada", "name": "Vesta", "slug": "vesta", "series": "Vesta" },
    { "id": "lancia-ypsilon", "brandId": "lancia", "name": "Ypsilon", "slug": "ypsilon", "series": "Ypsilon" },
    { "id": "lancia-delta", "brandId": "lancia", "name": "Delta (Mk1/2/3)", "slug": "delta", "series": "Delta" },
    { "id": "lancia-kappa", "brandId": "lancia", "name": "Kappa (Mk1)", "slug": "kappa", "series": "Kappa" },
    { "id": "lancia-lybra", "brandId": "lancia", "name": "Lybra (Mk1)", "slug": "lybra", "series": "Lybra" },
    { "id": "lancia-musa", "brandId": "lancia", "name": "Musa (Mk1)", "slug": "musa", "series": "Musa" },
    { "id": "lancia-phedra", "brandId": "lancia", "name": "Phedra (Mk1)", "slug": "phedra", "series": "Phedra" },
    { "id": "lancia-thema", "brandId": "lancia", "name": "Thema (Mk1/2)", "slug": "thema", "series": "Thema" },
    { "id": "lancia-thesis", "brandId": "lancia", "name": "Thesis (Mk1)", "slug": "thesis", "series": "Thesis" },
    { "id": "lancia-voyager", "brandId": "lancia", "name": "Voyager", "slug": "voyager", "series": "Voyager" },
    { "id": "lancia-zeta", "brandId": "lancia", "name": "Zeta", "slug": "zeta", "series": "Zeta" },
    { "id": "land-rover-discovery", "brandId": "land-rover", "name": "Discovery", "slug": "discovery", "series": "Discovery" },
    { "id": "land-rover-freelander", "brandId": "land-rover", "name": "Freelander", "slug": "freelander", "series": "Freelander" },
    { "id": "land-rover-range-rover", "brandId": "land-rover", "name": "Range Rover / Sport", "slug": "range-rover", "series": "Range Rover" },
    { "id": "land-rover-evoque", "brandId": "land-rover", "name": "Range Rover Evoque", "slug": "evoque", "series": "Range Rover" },
    { "id": "land-rover-defender", "brandId": "land-rover", "name": "Defender", "slug": "defender", "series": "Defender" },
    { "id": "land-rover-discovery-sport", "brandId": "land-rover", "name": "Discovery Sport", "slug": "discovery-sport", "series": "Discovery" },
    { "id": "land-rover-range-rover-sport", "brandId": "land-rover", "name": "Range Rover Sport", "slug": "range-rover-sport", "series": "Range Rover" },
    { "id": "land-rover-range-rover-velar", "brandId": "land-rover", "name": "Range Rover Velar", "slug": "range-rover-velar", "series": "Range Rover" },
    { "id": "mini-cooper-r50", "brandId": "mini", "name": "Cooper / One (R50/R53)", "slug": "cooper-r50", "series": "Cooper" },
    { "id": "mini-cooper-r56", "brandId": "mini", "name": "Cooper / One (R56)", "slug": "cooper-r56", "series": "Cooper" },
    { "id": "mini-cooper-f56", "brandId": "mini", "name": "Cooper / One (F56)", "slug": "cooper-f56", "series": "Cooper" },
    { "id": "mini-countryman", "brandId": "mini", "name": "Countryman", "slug": "countryman", "series": "Countryman" },
    { "id": "mini-clubman", "brandId": "mini", "name": "Clubman", "slug": "clubman", "series": "Clubman" },
    { "id": "mini-convertible", "brandId": "mini", "name": "Convertible", "slug": "convertible", "series": "Convertible" },
    { "id": "mini-coupe", "brandId": "mini", "name": "Coupe", "slug": "coupe", "series": "Coupe" },
    { "id": "mini-paceman", "brandId": "mini", "name": "Paceman", "slug": "paceman", "series": "Paceman" },
    { "id": "mini-roadster", "brandId": "mini", "name": "Roadster", "slug": "roadster", "series": "Roadster" },
    { "id": "saab-93", "brandId": "saab", "name": "9-3", "slug": "9-3", "series": "9-3" },
    { "id": "saab-95", "brandId": "saab", "name": "9-5", "slug": "9-5", "series": "9-5" },
    { "id": "saab-900", "brandId": "saab", "name": "900", "slug": "900", "series": "900" },
    { "id": "saab-9000", "brandId": "saab", "name": "9000", "slug": "9000", "series": "9000" },
    { "id": "saab-97x", "brandId": "saab", "name": "9-7X", "slug": "9-7x", "series": "9-7X" },
    { "id": "scania-r-series", "brandId": "scania", "name": "R / PRT-Series", "slug": "r-series", "series": "R-Series" },
    { "id": "scania-l-series", "brandId": "scania", "name": "L-Series", "slug": "l-series", "series": "L-Series" },
    { "id": "scania-s-series", "brandId": "scania", "name": "S-Series", "slug": "s-series", "series": "S-Series" },
    { "id": "scania-p-series", "brandId": "scania", "name": "P-Series", "slug": "p-series", "series": "P-Series" },
    { "id": "scania-g-series", "brandId": "scania", "name": "G-Series", "slug": "g-series", "series": "G-Series" },
    { "id": "smart-fortwo-450", "brandId": "smart", "name": "Fortwo (450)", "slug": "fortwo-450", "series": "Fortwo" },
    { "id": "smart-fortwo-451", "brandId": "smart", "name": "Fortwo (451)", "slug": "fortwo-451", "series": "Fortwo" },
    { "id": "smart-fortwo-453", "brandId": "smart", "name": "Fortwo (453)", "slug": "fortwo-453", "series": "Fortwo" },
    { "id": "smart-forfour", "brandId": "smart", "name": "Forfour", "slug": "forfour", "series": "Forfour" },
    { "id": "smart-roadster", "brandId": "smart", "name": "Roadster", "slug": "roadster", "series": "Roadster" },
    { "id": "smart-1", "brandId": "smart", "name": "#1", "slug": "smart-1", "series": "#1" },
    { "id": "smart-3", "brandId": "smart", "name": "#3", "slug": "smart-3", "series": "#3" },
];
