import { Model } from './vehicle-data';

export const vwGroupModels: Model[] = [
    // --- AUDI ---
    { id: "audi-80-b1", brandId: "audi", name: "80 (B1) 1972-1978", slug: "80-b1", series: "80" },
    { id: "audi-80-b2", brandId: "audi", name: "80 (B2) 1978-1986", slug: "80-b2", series: "80" },
    { id: "audi-80-b3", brandId: "audi", name: "80 (B3) 1986-1991", slug: "80-b3", series: "80" },
    { id: "audi-80-b4", brandId: "audi", name: "80 (B4) 1991-1996", slug: "80-b4", series: "80" },
    { id: "audi-100-c1", brandId: "audi", name: "100 (C1) 1968-1976", slug: "100-c1", series: "100" },
    { id: "audi-100-c2", brandId: "audi", name: "100 (C2) 1976-1982", slug: "100-c2", series: "100" },
    { id: "audi-100-c3", brandId: "audi", name: "100 (C3) 1982-1991", slug: "100-c3", series: "100" },
    { id: "audi-100-c4", brandId: "audi", name: "100 (C4) 1990-1994", slug: "100-c4", series: "100" },
    { id: "audi-a1-8x", brandId: "audi", name: "A1 (8X) 2010-2018", slug: "a1-8x", series: "A1" },
    { id: "audi-a1-gb", brandId: "audi", name: "A1 (GB) 2018-", slug: "a1-gb", series: "A1" },
    { id: "audi-a2-8z", brandId: "audi", name: "A2 (8Z) 1999-2005", slug: "a2-8z", series: "A2" },
    { id: "audi-a3-8l", brandId: "audi", name: "A3 (8L) 1996-2003", slug: "a3-8l", series: "A3" },
    { id: "audi-a3-8p", brandId: "audi", name: "A3 (8P) 2003-2013", slug: "a3-8p", series: "A3" },
    { id: "audi-a3-8v", brandId: "audi", name: "A3 (8V) 2012-2020", slug: "a3-8v", series: "A3" },
    { id: "audi-a3-8y", brandId: "audi", name: "A3 (8Y) 2020-", slug: "a3-8y", series: "A3" },
    { id: "audi-a4-b5", brandId: "audi", name: "A4 (B5) 1994-2001", slug: "a4-b5", series: "A4" },
    { id: "audi-a4-b6", brandId: "audi", name: "A4 (B6) 2000-2006", slug: "a4-b6", series: "A4" },
    { id: "audi-a4-b7", brandId: "audi", name: "A4 (B7) 2004-2009", slug: "a4-b7", series: "A4" },
    { id: "audi-a4-b8", brandId: "audi", name: "A4 (B8) 2007-2016", slug: "a4-b8", series: "A4" },
    { id: "audi-a4-b9", brandId: "audi", name: "A4 (B9) 2015-", slug: "a4-b9", series: "A4" },
    { id: "audi-a5-8t", brandId: "audi", name: "A5 (8T) 2007-2016", slug: "a5-8t", series: "A5" },
    { id: "audi-a5-f5", brandId: "audi", name: "A5 (F5) 2016-", slug: "a5-f5", series: "A5" },
    { id: "audi-a6-c4", brandId: "audi", name: "A6 (C4) 1994-1997", slug: "a6-c4", series: "A6" },
    { id: "audi-a6-c5", brandId: "audi", name: "A6 (C5) 1997-2005", slug: "a6-c5", series: "A6" },
    { id: "audi-a6-c6", brandId: "audi", name: "A6 (C6) 2004-2011", slug: "a6-c6", series: "A6" },
    { id: "audi-a6-c7", brandId: "audi", name: "A6 (C7) 2011-2018", slug: "a6-c7", series: "A6" },
    { id: "audi-a6-c8", brandId: "audi", name: "A6 (C8) 2018-", slug: "a6-c8", series: "A6" },
    { id: "audi-a7-4g", brandId: "audi", name: "A7 (4G) 2010-2018", slug: "a7-4g", series: "A7" },
    { id: "audi-a7-4k", brandId: "audi", name: "A7 (4K) 2018-", slug: "a7-4k", series: "A7" },
    { id: "audi-a8-d2", brandId: "audi", name: "A8 (D2) 1994-2002", slug: "a8-d2", series: "A8" },
    { id: "audi-a8-d3", brandId: "audi", name: "A8 (D3) 2002-2009", slug: "a8-d3", series: "A8" },
    { id: "audi-a8-d4", brandId: "audi", name: "A8 (D4) 2009-2017", slug: "a8-d4", series: "A8" },
    { id: "audi-a8-d5", brandId: "audi", name: "A8 (D5) 2017-", slug: "a8-d5", series: "A8" },
    { id: "audi-q2-ga", brandId: "audi", name: "Q2 (GA) 2016-", slug: "q2-ga", series: "Q2" },
    { id: "audi-q3-8u", brandId: "audi", name: "Q3 (8U) 2011-2018", slug: "q3-8u", series: "Q3" },
    { id: "audi-q3-f3", brandId: "audi", name: "Q3 (F3) 2018-", slug: "q3-f3", series: "Q3" },
    { id: "audi-q5-8r", brandId: "audi", name: "Q5 (8R) 2008-2017", slug: "q5-8r", series: "Q5" },
    { id: "audi-q5-fy", brandId: "audi", name: "Q5 (FY) 2017-", slug: "q5-fy", series: "Q5" },
    { id: "audi-q7-4l", brandId: "audi", name: "Q7 (4L) 2005-2015", slug: "q7-4l", series: "Q7" },
    { id: "audi-q7-4m", brandId: "audi", name: "Q7 (4M) 2015-", slug: "q7-4m", series: "Q7" },
    { id: "audi-q8-4m", brandId: "audi", name: "Q8 (4M) 2018-", slug: "q8-4m", series: "Q8" },
    { id: "audi-r8-42", brandId: "audi", name: "R8 (Type 42) 2006-2015", slug: "r8-42", series: "R8" },
    { id: "audi-r8-4s", brandId: "audi", name: "R8 (Type 4S) 2015-", slug: "r8-4s", series: "R8" },
    { id: "audi-tt-8n", brandId: "audi", name: "TT (8N) 1998-2006", slug: "tt-8n", series: "TT" },
    { id: "audi-tt-8j", brandId: "audi", name: "TT (8J) 2006-2014", slug: "tt-8j", series: "TT" },
    { id: "audi-tt-8s", brandId: "audi", name: "TT (8S) 2014-2023", slug: "tt-8s", series: "TT" },
    { id: "audi-e-tron-ge", brandId: "audi", name: "e-tron / Q8 e-tron (GE) 2018-", slug: "e-tron-ge", series: "e-tron" },
    { id: "audi-e-tron-gt", brandId: "audi", name: "e-tron GT (FW) 2020-", slug: "e-tron-gt", series: "e-tron GT" },
    { id: "audi-q4-e-tron", brandId: "audi", name: "Q4 e-tron (FZ) 2021-", slug: "q4-e-tron", series: "Q4" },

    // --- SEAT ---
    { id: "seat-alhambra-7v", brandId: "seat", name: "Alhambra I (7V) 1996-2010", slug: "alhambra-7v", series: "Alhambra" },
    { id: "seat-alhambra-7n", brandId: "seat", name: "Alhambra II (7N) 2010-2020", slug: "alhambra-7n", series: "Alhambra" },
    { id: "seat-altea-5p", brandId: "seat", name: "Altea (5P) 2004-2015", slug: "altea-5p", series: "Altea" },
    { id: "seat-arona-kj", brandId: "seat", name: "Arona (KJ) 2017-", slug: "arona-kj", series: "Arona" },
    { id: "seat-ateca-kh", brandId: "seat", name: "Ateca (KH) 2016-", slug: "ateca-kh", series: "Ateca" },
    { id: "seat-cordoba-6k", brandId: "seat", name: "Cordoba I (6K) 1993-2002", slug: "cordoba-6k", series: "Cordoba" },
    { id: "seat-cordoba-6l", brandId: "seat", name: "Cordoba II (6L) 2002-2009", slug: "cordoba-6l", series: "Cordoba" },
    { id: "seat-exeo-3r", brandId: "seat", name: "Exeo (3R) 2008-2013", slug: "exeo-3r", series: "Exeo" },
    { id: "seat-ibiza-021a", brandId: "seat", name: "Ibiza I (021A) 1984-1993", slug: "ibiza-021a", series: "Ibiza" },
    { id: "seat-ibiza-6k", brandId: "seat", name: "Ibiza II (6K) 1993-2002", slug: "ibiza-6k", series: "Ibiza" },
    { id: "seat-ibiza-6l", brandId: "seat", name: "Ibiza III (6L) 2001-2008", slug: "ibiza-6l", series: "Ibiza" },
    { id: "seat-ibiza-6j", brandId: "seat", name: "Ibiza IV (6J) 2008-2017", slug: "ibiza-6j", series: "Ibiza" },
    { id: "seat-ibiza-kj", brandId: "seat", name: "Ibiza V (KJ) 2017-", slug: "ibiza-kj", series: "Ibiza" },
    { id: "seat-leon-1m", brandId: "seat", name: "Leon I (1M) 1999-2005", slug: "leon-1m", series: "Leon" },
    { id: "seat-leon-1p", brandId: "seat", name: "Leon II (1P) 2005-2012", slug: "leon-1p", series: "Leon" },
    { id: "seat-leon-5f", brandId: "seat", name: "Leon III (5F) 2012-2020", slug: "leon-5f", series: "Leon" },
    { id: "seat-leon-kl", brandId: "seat", name: "Leon IV (KL) 2020-", slug: "leon-kl", series: "Leon" },
    { id: "seat-mii-kf", brandId: "seat", name: "Mii (KF) 2011-2021", slug: "mii-kf", series: "Mii" },
    { id: "seat-tarraco-kn", brandId: "seat", name: "Tarraco (KN) 2018-", slug: "tarraco-kn", series: "Tarraco" },
    { id: "seat-toledo-1l", brandId: "seat", name: "Toledo I (1L) 1991-1999", slug: "toledo-1l", series: "Toledo" },
    { id: "seat-toledo-1m", brandId: "seat", name: "Toledo II (1M) 1999-2004", slug: "toledo-1m", series: "Toledo" },
    { id: "seat-toledo-5p", brandId: "seat", name: "Toledo III (5P) 2004-2009", slug: "toledo-5p", series: "Toledo" },
    { id: "seat-toledo-nh", brandId: "seat", name: "Toledo IV (NH) 2012-2019", slug: "toledo-nh", series: "Toledo" },

    // --- SKODA ---
    { id: "skoda-citigo-nf", brandId: "skoda", name: "Citigo (NF) 2011-2020", slug: "citigo-nf", series: "Citigo" },
    { id: "skoda-enyaq-5a", brandId: "skoda", name: "Enyaq iV (5A) 2020-", slug: "enyaq-5a", series: "Enyaq" },
    { id: "skoda-fabia-6y", brandId: "skoda", name: "Fabia I (6Y) 1999-2007", slug: "fabia-6y", series: "Fabia" },
    { id: "skoda-fabia-5j", brandId: "skoda", name: "Fabia II (5J) 2007-2014", slug: "fabia-5j", series: "Fabia" },
    { id: "skoda-fabia-nj", brandId: "skoda", name: "Fabia III (NJ) 2014-2021", slug: "fabia-nj", series: "Fabia" },
    { id: "skoda-fabia-pj", brandId: "skoda", name: "Fabia IV (PJ) 2021-", slug: "fabia-pj", series: "Fabia" },
    { id: "skoda-kamiq-nw", brandId: "skoda", name: "Kamiq (NW) 2019-", slug: "kamiq-nw", series: "Kamiq" },
    { id: "skoda-karoq-nu", brandId: "skoda", name: "Karoq (NU) 2017-", slug: "karoq-nu", series: "Karoq" },
    { id: "skoda-kodiaq-ns", brandId: "skoda", name: "Kodiaq I (NS) 2016-2024", slug: "kodiaq-ns", series: "Kodiaq" },
    { id: "skoda-kodiaq-pz", brandId: "skoda", name: "Kodiaq II (PZ) 2024-", slug: "kodiaq-pz", series: "Kodiaq" },
    { id: "skoda-octavia-1u", brandId: "skoda", name: "Octavia I (1U) 1996-2010", slug: "octavia-1u", series: "Octavia" },
    { id: "skoda-octavia-1z", brandId: "skoda", name: "Octavia II (1Z) 2004-2013", slug: "octavia-1z", series: "Octavia" },
    { id: "skoda-octavia-5e", brandId: "skoda", name: "Octavia III (5E) 2012-2020", slug: "octavia-5e", series: "Octavia" },
    { id: "skoda-octavia-nx", brandId: "skoda", name: "Octavia IV (NX) 2020-", slug: "octavia-nx", series: "Octavia" },
    { id: "skoda-rapid-nh", brandId: "skoda", name: "Rapid (NH) 2012-2019", slug: "rapid-nh", series: "Rapid" },
    { id: "skoda-roomster-5j", brandId: "skoda", name: "Roomster (5J) 2006-2015", slug: "roomster-5j", series: "Roomster" },
    { id: "skoda-scala-nw", brandId: "skoda", name: "Scala (NW) 2019-", slug: "scala-nw", series: "Scala" },
    { id: "skoda-superb-3u", brandId: "skoda", name: "Superb I (3U) 2001-2008", slug: "superb-3u", series: "Superb" },
    { id: "skoda-superb-3t", brandId: "skoda", name: "Superb II (3T) 2008-2015", slug: "superb-3t", series: "Superb" },
    { id: "skoda-superb-3v", brandId: "skoda", name: "Superb III (3V) 2015-2023", slug: "superb-3v", series: "Superb" },
    { id: "skoda-superb-nz", brandId: "skoda", name: "Superb IV (NZ) 2023-", slug: "superb-nz", series: "Superb" },
    { id: "skoda-yeti-5l", brandId: "skoda", name: "Yeti (5L) 2009-2017", slug: "yeti-5l", series: "Yeti" },

    // --- VOLKSWAGEN ---
    { id: "vw-amarok-2h", brandId: "volkswagen", name: "Amarok I (2H) 2010-2022", slug: "amarok-2h", series: "Amarok" },
    { id: "vw-amarok-t1", brandId: "volkswagen", name: "Amarok II (T1) 2022-", slug: "amarok-t1", series: "Amarok" },
    { id: "vw-arteon-3h", brandId: "volkswagen", name: "Arteon (3H) 2017-", slug: "arteon-3h", series: "Arteon" },
    { id: "vw-bora-1j", brandId: "volkswagen", name: "Bora (1J) 1998-2005", slug: "bora-1j", series: "Bora" },
    { id: "vw-caddy-9kv", brandId: "volkswagen", name: "Caddy II (9KV) 1995-2004", slug: "caddy-9kv", series: "Caddy" },
    { id: "vw-caddy-2k", brandId: "volkswagen", name: "Caddy III (2K) 2004-2015", slug: "caddy-2k", series: "Caddy" },
    { id: "vw-caddy-sa", brandId: "volkswagen", name: "Caddy IV (SA) 2015-2020", slug: "caddy-sa", series: "Caddy" },
    { id: "vw-caddy-sb", brandId: "volkswagen", name: "Caddy V (SB) 2020-", slug: "caddy-sb", series: "Caddy" },
    { id: "vw-corrado-53i", brandId: "volkswagen", name: "Corrado (53I) 1988-1995", slug: "corrado-53i", series: "Corrado" },
    { id: "vw-crafter-2e", brandId: "volkswagen", name: "Crafter I (2E) 2006-2016", slug: "crafter-2e", series: "Crafter" },
    { id: "vw-crafter-sy", brandId: "volkswagen", name: "Crafter II (SY) 2016-", slug: "crafter-sy", series: "Crafter" },
    { id: "vw-eos-1f", brandId: "volkswagen", name: "Eos (1F) 2006-2015", slug: "eos-1f", series: "Eos" },
    { id: "vw-fox-5z", brandId: "volkswagen", name: "Fox (5Z) 2003-2011", slug: "fox-5z", series: "Fox" },
    { id: "vw-golf-17", brandId: "volkswagen", name: "Golf I (17) 1974-1983", slug: "golf-1", series: "Golf" },
    { id: "vw-golf-19e", brandId: "volkswagen", name: "Golf II (19E) 1983-1992", slug: "golf-2", series: "Golf" },
    { id: "vw-golf-1h", brandId: "volkswagen", name: "Golf III (1H) 1991-1998", slug: "golf-3", series: "Golf" },
    { id: "vw-golf-1j", brandId: "volkswagen", name: "Golf IV (1J) 1997-2003", slug: "golf-4", series: "Golf" },
    { id: "vw-golf-1k", brandId: "volkswagen", name: "Golf V (1K) 2003-2008", slug: "golf-5", series: "Golf" },
    { id: "vw-golf-5k", brandId: "volkswagen", name: "Golf VI (5K) 2008-2012", slug: "golf-6", series: "Golf" },
    { id: "vw-golf-5g", brandId: "volkswagen", name: "Golf VII (5G) 2012-2020", slug: "golf-7", series: "Golf" },
    { id: "vw-golf-cd", brandId: "volkswagen", name: "Golf VIII (CD) 2019-", slug: "golf-8", series: "Golf" },
    { id: "vw-id3-e1", brandId: "volkswagen", name: "ID.3 (E1) 2019-", slug: "id3-e1", series: "ID.3" },
    { id: "vw-id4-e2", brandId: "volkswagen", name: "ID.4 (E2) 2020-", slug: "id4-e2", series: "ID.4" },
    { id: "vw-id5-e3", brandId: "volkswagen", name: "ID.5 (E3) 2021-", slug: "id5-e3", series: "ID.5" },
    { id: "vw-id-buzz-eb", brandId: "volkswagen", name: "ID. Buzz (EB) 2022-", slug: "id-buzz-eb", series: "ID. Buzz" },
    { id: "vw-jetta-16", brandId: "volkswagen", name: "Jetta I (16) 1979-1984", slug: "jetta-1", series: "Jetta" },
    { id: "vw-jetta-16e", brandId: "volkswagen", name: "Jetta II (16E) 1983-1992", slug: "jetta-2", series: "Jetta" },
    { id: "vw-vento-1h", brandId: "volkswagen", name: "Jetta III / Vento (1H) 1992-1998", slug: "vento-1h", series: "Jetta" },
    { id: "vw-bora-1j2", brandId: "volkswagen", name: "Jetta IV / Bora (1J) 1998-2005", slug: "bora-1j2", series: "Jetta" },
    { id: "vw-jetta-1k", brandId: "volkswagen", name: "Jetta V (1K) 2005-2010", slug: "jetta-5", series: "Jetta" },
    { id: "vw-jetta-162", brandId: "volkswagen", name: "Jetta VI (162) 2010-2018", slug: "jetta-6", series: "Jetta" },
    { id: "vw-lt-21", brandId: "volkswagen", name: "LT Mk1 1975-1995", slug: "lt-1", series: "LT" },
    { id: "vw-lt-2d", brandId: "volkswagen", name: "LT Mk2 (2D) 1996-2006", slug: "lt-2", series: "LT" },
    { id: "vw-lupo-6x", brandId: "volkswagen", name: "Lupo (6X) 1998-2005", slug: "lupo-6x", series: "Lupo" },
    { id: "vw-new-beetle-9c", brandId: "volkswagen", name: "New Beetle (9C) 1997-2011", slug: "new-beetle-9c", series: "Beetle" },
    { id: "vw-beetle-5c", brandId: "volkswagen", name: "Beetle (5C) 2011-2019", slug: "beetle-5c", series: "Beetle" },
    { id: "vw-passat-b1", brandId: "volkswagen", name: "Passat (B1) 1973-1980", slug: "passat-b1", series: "Passat" },
    { id: "vw-passat-b2", brandId: "volkswagen", name: "Passat (B2) 1980-1988", slug: "passat-b2", series: "Passat" },
    { id: "vw-passat-b3", brandId: "volkswagen", name: "Passat (B3) 1988-1993", slug: "passat-b3", series: "Passat" },
    { id: "vw-passat-b4", brandId: "volkswagen", name: "Passat (B4) 1993-1996", slug: "passat-b4", series: "Passat" },
    { id: "vw-passat-b5", brandId: "volkswagen", name: "Passat (B5) 1996-2005", slug: "passat-b5", series: "Passat" },
    { id: "vw-passat-b6", brandId: "volkswagen", name: "Passat (B6) 2005-2010", slug: "passat-b6", series: "Passat" },
    { id: "vw-passat-b7", brandId: "volkswagen", name: "Passat (B7) 2010-2014", slug: "passat-b7", series: "Passat" },
    { id: "vw-passat-b8", brandId: "volkswagen", name: "Passat (B8) 2014-2023", slug: "passat-b8", series: "Passat" },
    { id: "vw-passat-b9", brandId: "volkswagen", name: "Passat (B9) 2023-", slug: "passat-b9", series: "Passat" },
    { id: "vw-passat-cc", brandId: "volkswagen", name: "Passat CC (35) 2008-2016", slug: "passat-cc", series: "Passat CC" },
    { id: "vw-phaeton-3d", brandId: "volkswagen", name: "Phaeton (3D) 2002-2016", slug: "phaeton-3d", series: "Phaeton" },
    { id: "vw-polo-86", brandId: "volkswagen", name: "Polo I (86) 1975-1981", slug: "polo-1", series: "Polo" },
    { id: "vw-polo-86c", brandId: "volkswagen", name: "Polo II (86C) 1981-1994", slug: "polo-2", series: "Polo" },
    { id: "vw-polo-6n", brandId: "volkswagen", name: "Polo III (6N) 1994-2001", slug: "polo-3", series: "Polo" },
    { id: "vw-polo-9n", brandId: "volkswagen", name: "Polo IV (9N) 2001-2009", slug: "polo-4", series: "Polo" },
    { id: "vw-polo-6r", brandId: "volkswagen", name: "Polo V (6R) 2009-2017", slug: "polo-5", series: "Polo" },
    { id: "vw-polo-aw", brandId: "volkswagen", name: "Polo VI (AW) 2017-", slug: "polo-6", series: "Polo" },
    { id: "vw-scirocco-1", brandId: "volkswagen", name: "Scirocco I (53) 1974-1981", slug: "scirocco-1", series: "Scirocco" },
    { id: "vw-scirocco-2", brandId: "volkswagen", name: "Scirocco II (53B) 1981-1992", slug: "scirocco-2", series: "Scirocco" },
    { id: "vw-scirocco-3", brandId: "volkswagen", name: "Scirocco III (13) 2008-2017", slug: "scirocco-3", series: "Scirocco" },
    { id: "vw-sharan-7m", brandId: "volkswagen", name: "Sharan I (7M) 1995-2010", slug: "sharan-7m", series: "Sharan" },
    { id: "vw-sharan-7n", brandId: "volkswagen", name: "Sharan II (7N) 2010-2022", slug: "sharan-7n", series: "Sharan" },
    { id: "vw-t-cross-c1", brandId: "volkswagen", name: "T-Cross (C1) 2018-", slug: "t-cross-c1", series: "T-Cross" },
    { id: "vw-t-roc-a1", brandId: "volkswagen", name: "T-Roc (A1) 2017-", slug: "t-roc-a1", series: "T-Roc" },
    { id: "vw-taigo-cs", brandId: "volkswagen", name: "Taigo (CS) 2021-", slug: "taigo-cs", series: "Taigo" },
    { id: "vw-tiguan-5n", brandId: "volkswagen", name: "Tiguan I (5N) 2007-2016", slug: "tiguan-5n", series: "Tiguan" },
    { id: "vw-tiguan-ad", brandId: "volkswagen", name: "Tiguan II (AD) 2016-2024", slug: "tiguan-ad", series: "Tiguan" },
    { id: "vw-tiguan-ct", brandId: "volkswagen", name: "Tiguan III (CT) 2024-", slug: "tiguan-ct", series: "Tiguan" },
    { id: "vw-touareg-7l", brandId: "volkswagen", name: "Touareg I (7L) 2002-2010", slug: "touareg-7l", series: "Touareg" },
    { id: "vw-touareg-7p", brandId: "volkswagen", name: "Touareg II (7P) 2010-2018", slug: "touareg-7p", series: "Touareg" },
    { id: "vw-touareg-cr", brandId: "volkswagen", name: "Touareg III (CR) 2018-", slug: "touareg-cr", series: "Touareg" },
    { id: "vw-touran-1t", brandId: "volkswagen", name: "Touran I (1T) 2003-2015", slug: "touran-1t", series: "Touran" },
    { id: "vw-touran-5t", brandId: "volkswagen", name: "Touran II (5T) 2015-", slug: "touran-5t", series: "Touran" },
    { id: "vw-transporter-t3", brandId: "volkswagen", name: "Transporter T3 1979-1992", slug: "transporter-t3", series: "Transporter" },
    { id: "vw-transporter-t4", brandId: "volkswagen", name: "Transporter T4 1990-2003", slug: "transporter-t4", series: "Transporter" },
    { id: "vw-transporter-t5", brandId: "volkswagen", name: "Transporter T5 2003-2015", slug: "transporter-t5", series: "Transporter" },
    { id: "vw-transporter-t6", brandId: "volkswagen", name: "Transporter T6 2015-2024", slug: "transporter-t6", series: "Transporter" },
    { id: "vw-transporter-t7", brandId: "volkswagen", name: "Multivan T7 2021-", slug: "transporter-t7", series: "Transporter" },
    { id: "vw-up-aa", brandId: "volkswagen", name: "up! (AA) 2011-2023", slug: "up-aa", series: "up!" }
];
