import { Model } from './types';

export const vwGroupModels: Model[] = [
    { "id": "audi-80", "brandId": "audi", "name": "80", "slug": "80", "series": "80" },
    { "id": "audi-90", "brandId": "audi", "name": "90", "slug": "90", "series": "90" },
    { "id": "audi-100", "brandId": "audi", "name": "100", "slug": "100", "series": "100" },
    { "id": "audi-200", "brandId": "audi", "name": "200", "slug": "200", "series": "200" },
    { "id": "audi-v8", "brandId": "audi", "name": "V8", "slug": "v8", "series": "V8" },
    { "id": "audi-a1-8x", "brandId": "audi", "name": "A1", "slug": "a1-8x", "series": "A1", "keywords": ["1.2 TFSI", "1.4 TFSI", "1.6 TDI", "2.0 TDI", "S1"] },
    { "id": "audi-a1-gb", "brandId": "audi", "name": "A1", "slug": "a1-gb", "series": "A1", "keywords": ["25 TFSI", "30 TFSI", "35 TFSI", "40 TFSI"] },
    { "id": "audi-a2", "brandId": "audi", "name": "A2", "slug": "a2", "series": "A2", "keywords": ["1.4 TDI", "1.2 TDI", "1.6 FSI", "1.4 16V"] },
    { "id": "audi-a3-1", "brandId": "audi", "name": "A3", "slug": "a3-8l", "series": "A3", "keywords": ["S3", "1.6", "1.8", "1.8T", "1.9 TDI", "AGR", "ALH", "ASV", "ASZ"] },
    { "id": "audi-a3-2", "brandId": "audi", "name": "A3", "slug": "a3-8p", "series": "A3", "keywords": ["S3", "Sportback", "1.6", "1.6 FSI", "1.9 TDI", "2.0 TDI", "BKC", "BXE", "BKD", "BMM"] },
    { "id": "audi-a3-3", "brandId": "audi", "name": "A3", "slug": "a3-8v", "series": "A3", "keywords": ["S3", "Sedan", "1.4 TFSI", "1.6 TDI", "2.0 TDI", "CRB", "CUNA"] },
    { "id": "audi-a3-8y", "brandId": "audi", "name": "A3", "slug": "a3-8y", "series": "A3", "keywords": ["S3", "RS3"] },
    { "id": "audi-rs3", "brandId": "audi", "name": "RS3", "slug": "rs3", "series": "A3", "keywords": ["8P", "8V", "8Y", "Sportback"] },
    { "id": "audi-a4-b5", "brandId": "audi", "name": "A4", "slug": "a4-b5", "series": "A4", "keywords": ["Avant", "Quattro", "1.6", "1.8T", "1.9 TDI", "AFN", "AJM", "AVG"] },
    { "id": "audi-a4-b6", "brandId": "audi", "name": "A4", "slug": "a4-b6", "series": "A4", "keywords": ["Avant", "Quattro", "Cabriolet", "1.9 TDI", "2.5 TDI", "AVX", "AVF"] },
    { "id": "audi-a4-b7", "brandId": "audi", "name": "A4", "slug": "a4-b7", "series": "A4", "keywords": ["Avant", "Quattro", "2.0 TDI", "3.0 TDI", "BPW", "BRE", "BKN"] },
    { "id": "audi-a4-b8", "brandId": "audi", "name": "A4", "slug": "a4-b8", "series": "A4", "keywords": ["Avant", "Quattro", "Allroad", "2.0 TDI", "2.7 TDI", "3.0 TDI", "CAGA", "CAGB", "CCWA"] },
    { "id": "audi-a4-b9", "brandId": "audi", "name": "A4", "slug": "a4-b9", "series": "A4", "keywords": ["2.0 TFSI", "S4", "RS4"] },
    { "id": "audi-a4-allroad-b8", "brandId": "audi", "name": "Allroad", "slug": "a4-allroad-b8", "series": "A4", "keywords": ["A4 Allroad", "Quattro"] },
    { "id": "audi-a4-allroad-b9", "brandId": "audi", "name": "Allroad", "slug": "a4-allroad-b9", "series": "A4", "keywords": ["A4 Allroad", "Quattro"] },
    { "id": "audi-rs4", "brandId": "audi", "name": "RS4", "slug": "rs4", "series": "A4", "keywords": ["B5", "B7", "B8", "B9", "Avant"] },
    { "id": "audi-s4", "brandId": "audi", "name": "S4", "slug": "s4", "series": "A4", "keywords": ["B5", "B6", "B7", "B8", "B9"] },
    { "id": "audi-a5-8t", "brandId": "audi", "name": "A5", "slug": "a5-8t", "series": "A5" },
    { "id": "audi-a5-f5", "brandId": "audi", "name": "A5", "slug": "a5-f5", "series": "A5" },
    { "id": "audi-rs5", "brandId": "audi", "name": "RS5", "slug": "rs5", "series": "A5" },
    { "id": "audi-s5", "brandId": "audi", "name": "S5", "slug": "s5", "series": "A5" },
    { "id": "audi-a6-c4", "brandId": "audi", "name": "A6", "slug": "a6-c4", "series": "A6", "keywords": ["1.9 TDI", "2.5 TDI", "S6"] },
    { "id": "audi-a6-c5", "brandId": "audi", "name": "A6", "slug": "a6-c5", "series": "A6", "keywords": ["1.9 TDI", "2.5 TDI", "1.8T", "2.4 V6", "2.7T", "2.8 V6", "S6", "RS6"] },
    { "id": "audi-a6-c6", "brandId": "audi", "name": "A6", "slug": "a6-c6", "series": "A6", "keywords": ["2.0 TDI", "2.7 TDI", "3.0 TDI", "2.4", "3.2 FSI", "S6", "RS6"] },
    { "id": "audi-a6-c7", "brandId": "audi", "name": "A6", "slug": "a6-c7", "series": "A6", "keywords": ["2.0 TDI", "3.0 TDI", "2.0 TFSI", "3.0 TFSI", "S6", "RS6"] },
    { "id": "audi-a6-c8", "brandId": "audi", "name": "A6", "slug": "a6-c8", "series": "A6", "keywords": ["35 TDI", "40 TDI", "45 TDI", "50 TDI", "55 TFSI", "S6", "RS6"] },
    { "id": "audi-a6-allroad-c5", "brandId": "audi", "name": "A6 Allroad", "slug": "a6-allroad-c5", "series": "A6" },
    { "id": "audi-a6-allroad-c6", "brandId": "audi", "name": "A6 Allroad", "slug": "a6-allroad-c6", "series": "A6" },
    { "id": "audi-a6-allroad-c7", "brandId": "audi", "name": "A6 Allroad", "slug": "a6-allroad-c7", "series": "A6" },
    { "id": "audi-a6-allroad-c8", "brandId": "audi", "name": "A6 Allroad", "slug": "a6-allroad-c8", "series": "A6" },
    { "id": "audi-rs6", "brandId": "audi", "name": "RS6", "slug": "rs6", "series": "A6" },
    { "id": "audi-s6", "brandId": "audi", "name": "S6", "slug": "s6", "series": "A6" },
    { "id": "audi-a7-c7", "brandId": "audi", "name": "A7", "slug": "a7-c7", "series": "A7" },
    { "id": "audi-a7-c8", "brandId": "audi", "name": "A7", "slug": "a7-c8", "series": "A7" },
    { "id": "audi-rs7", "brandId": "audi", "name": "RS7", "slug": "rs7", "series": "A7" },
    { "id": "audi-s7", "brandId": "audi", "name": "S7", "slug": "s7", "series": "A7" },
    { "id": "audi-a8-d2", "brandId": "audi", "name": "A8", "slug": "a8-d2", "series": "A8" },
    { "id": "audi-a8-d3", "brandId": "audi", "name": "A8", "slug": "a8-d3", "series": "A8" },
    { "id": "audi-a8-d4", "brandId": "audi", "name": "A8", "slug": "a8-d4", "series": "A8" },
    { "id": "audi-a8-d5", "brandId": "audi", "name": "A8", "slug": "a8-d5", "series": "A8" },
    { "id": "audi-s8", "brandId": "audi", "name": "S8", "slug": "s8", "series": "A8" },
    { "id": "audi-q2", "brandId": "audi", "name": "Q2", "slug": "q2", "series": "Q2" },
    { "id": "audi-q3-8u", "brandId": "audi", "name": "Q3", "slug": "q3-8u", "series": "Q3" },
    { "id": "audi-q3-f3", "brandId": "audi", "name": "Q3", "slug": "q3-f3", "series": "Q3" },
    { "id": "audi-rs-q3", "brandId": "audi", "name": "RS Q3", "slug": "rs-q3", "series": "Q3" },
    { "id": "audi-sq3", "brandId": "audi", "name": "SQ3", "slug": "sq3", "series": "Q3" },
    { "id": "audi-q4-etron", "brandId": "audi", "name": "Q4 e-tron", "slug": "q4-etron", "series": "Q4" },
    { "id": "audi-q5-8r", "brandId": "audi", "name": "Q5", "slug": "q5-8r", "series": "Q5" },
    { "id": "audi-q5-fy", "brandId": "audi", "name": "Q5", "slug": "q5-fy", "series": "Q5" },
    { "id": "audi-q7-4l", "brandId": "audi", "name": "Q7", "slug": "q7-4l", "series": "Q7" },
    { "id": "audi-q7-4m", "brandId": "audi", "name": "Q7", "slug": "q7-4m", "series": "Q7" },
    { "id": "audi-q8", "brandId": "audi", "name": "Q8", "slug": "q8", "series": "Q8" },
    { "id": "audi-rs-q8", "brandId": "audi", "name": "RS Q8", "slug": "rs-q8", "series": "Q8" },
    { "id": "audi-sq8", "brandId": "audi", "name": "SQ8", "slug": "sq8", "series": "Q8" },
    { "id": "audi-r8-1", "brandId": "audi", "name": "R8 I", "slug": "r8-1", "series": "R8" },
    { "id": "audi-r8-2", "brandId": "audi", "name": "R8 II", "slug": "r8-2", "series": "R8" },
    { "id": "audi-tt-8n", "brandId": "audi", "name": "TT", "slug": "tt-8n", "series": "TT" },
    { "id": "audi-tt-8j", "brandId": "audi", "name": "TT", "slug": "tt-8j", "series": "TT" },
    { "id": "audi-tt-fv", "brandId": "audi", "name": "TT", "slug": "tt-fv", "series": "TT" },
    { "id": "audi-etron", "brandId": "audi", "name": "e-tron / Q8 e-tron", "slug": "etron", "series": "e-tron" },
    { "id": "audi-etron-gt", "brandId": "audi", "name": "e-tron GT", "slug": "etron-gt", "series": "e-tron" },
    { "id": "audi-q6-etron", "brandId": "audi", "name": "Q6 e-tron", "slug": "q6-etron", "series": "Q6" },
    { "id": "seat-alhambra-1", "brandId": "seat", "name": "I", "slug": "alhambra-1", "series": "Alhambra" },
    { "id": "seat-alhambra-2", "brandId": "seat", "name": "II", "slug": "alhambra-2", "series": "Alhambra" },
    { "id": "seat-altea", "brandId": "seat", "name": "", "slug": "altea", "series": "Altea" },
    { "id": "seat-arona", "brandId": "seat", "name": "", "slug": "arona", "series": "Arona" },
    { "id": "seat-arosa", "brandId": "seat", "name": "", "slug": "arosa", "series": "Arosa" },
    { "id": "seat-ateca", "brandId": "seat", "name": "", "slug": "ateca", "series": "Ateca" },
    { "id": "seat-cordoba-1", "brandId": "seat", "name": "I", "slug": "cordoba-1", "series": "Cordoba" },
    { "id": "seat-cordoba-2", "brandId": "seat", "name": "II", "slug": "cordoba-2", "series": "Cordoba" },
    { "id": "seat-exeo", "brandId": "seat", "name": "", "slug": "exeo", "series": "Exeo" },
    { "id": "seat-ibiza-1", "brandId": "seat", "name": "I", "slug": "ibiza-1", "series": "Ibiza" },
    { "id": "seat-ibiza-2", "brandId": "seat", "name": "II", "slug": "ibiza-2", "series": "Ibiza", "keywords": ["1.4", "1.9 TDI"] },
    { "id": "seat-ibiza-3", "brandId": "seat", "name": "III", "slug": "ibiza-3", "series": "Ibiza", "keywords": ["1.4", "1.9 TDI", "FR", "Cupra"] },
    { "id": "seat-ibiza-4", "brandId": "seat", "name": "IV", "slug": "ibiza-4", "series": "Ibiza", "keywords": ["1.2 TSI", "1.4 TSI", "FR", "Cupra"] },
    { "id": "seat-ibiza-5", "brandId": "seat", "name": "V", "slug": "ibiza-5", "series": "Ibiza", "keywords": ["FR", "1.0 TSI"] },
    { "id": "seat-inca", "brandId": "seat", "name": "", "slug": "inca", "series": "Inca" },
    { "id": "seat-leon-1", "brandId": "seat", "name": "I", "slug": "leon-1", "series": "Leon", "keywords": ["Cupra", "FR", "1.9 TDI", "1.8T"] },
    { "id": "seat-leon-2", "brandId": "seat", "name": "II", "slug": "leon-2", "series": "Leon", "keywords": ["Cupra", "FR", "1.9 TDI", "2.0 TDI", "1.4 TSI"] },
    { "id": "seat-leon-3", "brandId": "seat", "name": "III", "slug": "leon-3", "series": "Leon", "keywords": ["Cupra", "FR", "1.4 TSI", "1.6 TDI", "2.0 TDI"] },
    { "id": "seat-leon-4", "brandId": "seat", "name": "IV", "slug": "leon-4", "series": "Leon", "keywords": ["e-Hybrid", "FR"] },
    { "id": "seat-mii", "brandId": "seat", "name": "", "slug": "mii", "series": "Mii" },
    { "id": "seat-tarraco", "brandId": "seat", "name": "", "slug": "tarraco", "series": "Tarraco" },
    { "id": "seat-toledo-1", "brandId": "seat", "name": "I", "slug": "toledo-1", "series": "Toledo" },
    { "id": "seat-toledo-2", "brandId": "seat", "name": "II", "slug": "toledo-2", "series": "Toledo" },
    { "id": "seat-toledo-3", "brandId": "seat", "name": "III", "slug": "toledo-3", "series": "Toledo" },
    { "id": "seat-toledo-4", "brandId": "seat", "name": "IV", "slug": "toledo-4", "series": "Toledo" },
    { "id": "skoda-citigo", "brandId": "skoda", "name": "", "slug": "citigo", "series": "Citigo" },
    { "id": "skoda-enyaq", "brandId": "skoda", "name": "", "slug": "enyaq", "series": "Enyaq" },
    { "id": "skoda-fabia-1", "brandId": "skoda", "name": "I", "slug": "fabia-1", "series": "Fabia", "keywords": ["1.2 HTP", "1.4 16V", "1.4 MPI", "1.9 TDI", "1.9 SDI", "RS", "vRS"] },
    { "id": "skoda-fabia-2", "brandId": "skoda", "name": "II", "slug": "fabia-2", "series": "Fabia", "keywords": ["1.2 HTP", "1.2 TSI", "1.4 TSI", "1.6 TDI", "RS", "vRS"] },
    { "id": "skoda-fabia-3", "brandId": "skoda", "name": "III", "slug": "fabia-3", "series": "Fabia", "keywords": ["1.0 TSI", "1.2 TSI", "1.4 TDI"] },
    { "id": "skoda-fabia-4", "brandId": "skoda", "name": "IV", "slug": "fabia-4", "series": "Fabia" },
    { "id": "skoda-felicia", "brandId": "skoda", "name": "", "slug": "felicia", "series": "Felicia" },
    { "id": "skoda-kamiq", "brandId": "skoda", "name": "", "slug": "kamiq", "series": "Kamiq" },
    { "id": "skoda-karoq", "brandId": "skoda", "name": "", "slug": "karoq", "series": "Karoq" },
    { "id": "skoda-kodiaq-1", "brandId": "skoda", "name": "I", "slug": "kodiaq-1", "series": "Kodiaq" },
    { "id": "skoda-kodiaq-2", "brandId": "skoda", "name": "II", "slug": "kodiaq-2", "series": "Kodiaq" },
    { "id": "skoda-octavia-1", "brandId": "skoda", "name": "Octavia I", "slug": "octavia-1", "series": "Octavia", "keywords": ["Tour", "Combi", "RS", "1.6", "1.8T", "1.9 TDI", "AGR", "ALH", "ASV", "ASZ"] },
    { "id": "skoda-octavia-2", "brandId": "skoda", "name": "Octavia II", "slug": "octavia-2", "series": "Octavia", "keywords": ["Combi", "RS", "Scout", "1.4 TSI", "1.6 TDI", "1.9 TDI", "2.0 TDI", "BKC", "BXE", "BKD", "BMM", "CAYC"] },
    { "id": "skoda-octavia-3", "brandId": "skoda", "name": "Octavia III", "slug": "octavia-3", "series": "Octavia", "keywords": ["Combi", "RS", "Scout", "1.4 TSI", "1.6 TDI", "2.0 TDI", "CRB", "CUNA"] },
    { "id": "skoda-octavia-4", "brandId": "skoda", "name": "IV", "slug": "octavia-4", "series": "Octavia", "keywords": ["vRS", "iV", "Mild Hybrid"] },
    { "id": "skoda-praktik", "brandId": "skoda", "name": "", "slug": "praktik", "series": "Praktik" },
    { "id": "skoda-rapid", "brandId": "skoda", "name": "", "slug": "rapid", "series": "Rapid" },
    { "id": "skoda-roomster", "brandId": "skoda", "name": "", "slug": "roomster", "series": "Roomster" },
    { "id": "skoda-scala", "brandId": "skoda", "name": "", "slug": "scala", "series": "Scala" },
    { "id": "skoda-superb-1", "brandId": "skoda", "name": "Superb I", "slug": "superb-1", "series": "Superb" },
    { "id": "skoda-superb-2", "brandId": "skoda", "name": "Superb II", "slug": "superb-2", "series": "Superb" },
    { "id": "skoda-superb-3", "brandId": "skoda", "name": "Superb III", "slug": "superb-3", "series": "Superb" },
    { "id": "skoda-superb-4", "brandId": "skoda", "name": "Superb IV", "slug": "superb-4", "series": "Superb" },
    { "id": "skoda-yeti", "brandId": "skoda", "name": "", "slug": "yeti", "series": "Yeti" },
    { "id": "skoda-105", "brandId": "skoda", "name": "105", "slug": "105", "series": "100-as széria" },
    { "id": "skoda-120", "brandId": "skoda", "name": "120", "slug": "120", "series": "100-as széria" },
    { "id": "skoda-130", "brandId": "skoda", "name": "130", "slug": "130", "series": "100-as széria" },
    { "id": "skoda-favorit", "brandId": "skoda", "name": "Favorit", "slug": "favorit", "series": "Favorit" },
    { "id": "skoda-forman", "brandId": "skoda", "name": "Forman", "slug": "forman", "series": "Forman" },
    { "id": "skoda-elroq", "brandId": "skoda", "name": "Elroq", "slug": "elroq", "series": "Elroq" },
    { "id": "vw-amarok-1", "brandId": "volkswagen", "name": "Amarok I", "slug": "amarok-1", "series": "Amarok" },
    { "id": "vw-amarok-2", "brandId": "volkswagen", "name": "Amarok II", "slug": "amarok-2", "series": "Amarok" },
    { "id": "vw-arteon", "brandId": "volkswagen", "name": "Arteon", "slug": "arteon", "series": "Arteon" },
    { "id": "vw-beetle", "brandId": "volkswagen", "name": "Beetle", "slug": "beetle", "series": "Beetle" },
    { "id": "vw-new-beetle", "brandId": "volkswagen", "name": "New Beetle", "slug": "new-beetle", "series": "Beetle" },
    { "id": "vw-bora", "brandId": "volkswagen", "name": "Bora", "slug": "bora", "series": "Bora" },
    { "id": "vw-caddy-2", "brandId": "volkswagen", "name": "Caddy II", "slug": "caddy-2", "series": "Caddy" },
    { "id": "vw-caddy-3", "brandId": "volkswagen", "name": "Caddy III", "slug": "caddy-3", "series": "Caddy" },
    { "id": "vw-caddy-4", "brandId": "volkswagen", "name": "Caddy IV", "slug": "caddy-4", "series": "Caddy" },
    { "id": "vw-caddy-5", "brandId": "volkswagen", "name": "Caddy V", "slug": "caddy-5", "series": "Caddy" },
    { "id": "vw-cc", "brandId": "volkswagen", "name": "CC / Passat CC", "slug": "cc", "series": "CC" },
    { "id": "vw-corrado", "brandId": "volkswagen", "name": "Corrado", "slug": "corrado", "series": "Corrado" },
    { "id": "vw-crafter-1", "brandId": "volkswagen", "name": "Crafter I", "slug": "crafter-1", "series": "Crafter" },
    { "id": "vw-crafter-2", "brandId": "volkswagen", "name": "Crafter II", "slug": "crafter-2", "series": "Crafter" },
    { "id": "vw-eos", "brandId": "volkswagen", "name": "Eos", "slug": "eos", "series": "Eos" },
    { "id": "vw-fox", "brandId": "volkswagen", "name": "Fox", "slug": "fox", "series": "Fox" },
    { "id": "vw-golf-1", "brandId": "volkswagen", "name": "I", "slug": "golf-1", "series": "Golf" },
    { "id": "vw-golf-2", "brandId": "volkswagen", "name": "II", "slug": "golf-2", "series": "Golf" },
    { "id": "vw-golf-3", "brandId": "volkswagen", "name": "III", "slug": "golf-3", "series": "Golf" },
    { "id": "vw-golf-4", "brandId": "volkswagen", "name": "Golf IV", "slug": "golf-4", "series": "Golf", "keywords": ["GTI", "R32", "1.4 16V", "1.6 16V", "1.9 TDI", "PDTDI", "ASZ", "ARL"] },
    { "id": "vw-golf-5", "brandId": "volkswagen", "name": "Golf V", "slug": "golf-5", "series": "Golf", "keywords": ["GTI", "GTD", "R32", "1.4 TSI", "1.6 SR", "1.9 TDI", "2.0 TDI"] },
    { "id": "vw-golf-6", "brandId": "volkswagen", "name": "Golf VI", "slug": "golf-6", "series": "Golf", "keywords": ["GTI", "GTD", "Golf R", "1.2 TSI", "1.4 TSI", "1.6 TDI", "2.0 TDI"] },
    { "id": "vw-golf-7", "brandId": "volkswagen", "name": "Golf VII", "slug": "golf-7", "series": "Golf", "keywords": ["GTI", "GTD", "GTE", "Golf R", "1.2 TSI", "1.4 TSI", "1.6 TDI", "2.0 TDI"] },
    { "id": "vw-golf-8", "brandId": "volkswagen", "name": "Golf VIII", "slug": "golf-8", "series": "Golf", "keywords": ["GTI", "R", "Clubsport", "GTD", "GTE"] },
    { "id": "vw-golf-plus", "brandId": "volkswagen", "name": "Golf Plus", "slug": "golf-plus", "series": "Golf" },
    { "id": "vw-golf-sportsvan", "brandId": "volkswagen", "name": "Golf Sportsvan", "slug": "golf-sportsvan", "series": "Golf" },
    { "id": "vw-id3", "brandId": "volkswagen", "name": "ID.3", "slug": "id3", "series": "ID" },
    { "id": "vw-id4", "brandId": "volkswagen", "name": "ID.4", "slug": "id4", "series": "ID" },
    { "id": "vw-id5", "brandId": "volkswagen", "name": "ID.5", "slug": "id5", "series": "ID" },
    { "id": "vw-id-buzz", "brandId": "volkswagen", "name": "ID. Buzz", "slug": "id-buzz", "series": "ID" },
    { "id": "vw-id7", "brandId": "volkswagen", "name": "ID.7", "slug": "id7", "series": "ID" },
    { "id": "vw-jetta-1", "brandId": "volkswagen", "name": "Jetta I", "slug": "jetta-1", "series": "Jetta" },
    { "id": "vw-jetta-2", "brandId": "volkswagen", "name": "Jetta II", "slug": "jetta-2", "series": "Jetta" },
    { "id": "vw-jetta-5", "brandId": "volkswagen", "name": "Jetta V", "slug": "jetta-5", "series": "Jetta" },
    { "id": "vw-jetta-6", "brandId": "volkswagen", "name": "Jetta VI", "slug": "jetta-6", "series": "Jetta" },
    { "id": "vw-lt", "brandId": "volkswagen", "name": "LT", "slug": "lt", "series": "LT" },
    { "id": "vw-lupo", "brandId": "volkswagen", "name": "Lupo", "slug": "lupo", "series": "Lupo" },
    { "id": "vw-passat-b3", "brandId": "volkswagen", "name": "Passat", "slug": "passat-b3", "series": "Passat" },
    { "id": "vw-passat-b4", "brandId": "volkswagen", "name": "Passat", "slug": "passat-b4", "series": "Passat" },
    { "id": "vw-passat-b5", "brandId": "vw", "name": "Passat", "slug": "passat-b5", "series": "Passat", "keywords": ["Variant", "4Motion", "1.6", "1.8T", "1.9 TDI", "2.5 TDI", "3B", "3BG", "AFN", "AJM", "AVF", "AWX", "PDTDI"] },
    { "id": "vw-passat-b6", "brandId": "vw", "name": "Passat", "slug": "passat-b6", "series": "Passat", "keywords": ["Variant", "4Motion", "1.9 TDI", "2.0 TDI", "3C", "BKC", "BXE", "BKD", "BKP", "BMR", "BMP"] },
    { "id": "vw-passat-b7", "brandId": "vw", "name": "Passat", "slug": "passat-b7", "series": "Passat", "keywords": ["Variant", "4Motion", "Alltrack", "1.6 TDI", "2.0 TDI", "CFG", "CLLA"] },
    { "id": "vw-passat-b8", "brandId": "volkswagen", "name": "Passat B8", "slug": "passat-b8", "series": "Passat", "keywords": ["3G", "1.4 TSI", "2.0 TDI", "BiTDI", "GTE"] },
    { "id": "vw-passat-b9", "brandId": "volkswagen", "name": "Passat", "slug": "passat-b9", "series": "Passat" },
    { "id": "vw-phaeton", "brandId": "volkswagen", "name": "Phaeton", "slug": "phaeton", "series": "Phaeton" },
    { "id": "vw-polo-3", "brandId": "volkswagen", "name": "III", "slug": "polo-3", "series": "Polo" },
    { "id": "vw-polo-4", "brandId": "volkswagen", "name": "IV", "slug": "polo-4", "series": "Polo" },
    { "id": "vw-polo-5", "brandId": "volkswagen", "name": "V", "slug": "polo-5", "series": "Polo" },
    { "id": "vw-polo-6", "brandId": "volkswagen", "name": "VI", "slug": "polo-6", "series": "Polo" },
    { "id": "vw-scirocco-2", "brandId": "volkswagen", "name": "Scirocco II", "slug": "scirocco-2", "series": "Scirocco" },
    { "id": "vw-scirocco-3", "brandId": "volkswagen", "name": "Scirocco III", "slug": "scirocco-3", "series": "Scirocco" },
    { "id": "vw-sharan-1", "brandId": "volkswagen", "name": "I", "slug": "sharan-1", "series": "Sharan" },
    { "id": "vw-sharan-2", "brandId": "volkswagen", "name": "II", "slug": "sharan-2", "series": "Sharan" },
    { "id": "vw-t-cross", "brandId": "volkswagen", "name": "T-Cross", "slug": "t-cross", "series": "T-Cross" },
    { "id": "vw-t-roc", "brandId": "volkswagen", "name": "T-Roc", "slug": "t-roc", "series": "T-Roc" },
    { "id": "vw-taigo", "brandId": "volkswagen", "name": "Taigo", "slug": "taigo", "series": "Taigo" },
    { "id": "vw-tiguan-1", "brandId": "volkswagen", "name": "I", "slug": "tiguan-1", "series": "Tiguan" },
    { "id": "vw-tiguan-2", "brandId": "volkswagen", "name": "II", "slug": "tiguan-2", "series": "Tiguan" },
    { "id": "vw-tiguan-3", "brandId": "volkswagen", "name": "III", "slug": "tiguan-3", "series": "Tiguan" },
    { "id": "vw-touareg-1", "brandId": "volkswagen", "name": "I", "slug": "touareg-1", "series": "Touareg" },
    { "id": "vw-touareg-2", "brandId": "volkswagen", "name": "II", "slug": "touareg-2", "series": "Touareg" },
    { "id": "vw-touareg-3", "brandId": "volkswagen", "name": "III", "slug": "touareg-3", "series": "Touareg" },
    { "id": "vw-touran-1", "brandId": "volkswagen", "name": "I", "slug": "touran-1", "series": "Touran" },
    { "id": "vw-touran-2", "brandId": "volkswagen", "name": "II", "slug": "touran-2", "series": "Touran" },
    { "id": "vw-transporter-t3", "brandId": "volkswagen", "name": "", "slug": "transporter-t3", "series": "Transporter" },
    { "id": "vw-transporter-t4", "brandId": "volkswagen", "name": "", "slug": "transporter-t4", "series": "Transporter" },
    { "id": "vw-transporter-t5", "brandId": "volkswagen", "name": "", "slug": "transporter-t5", "series": "Transporter" },
    { "id": "vw-transporter-t6", "brandId": "volkswagen", "name": "", "slug": "transporter-t6", "series": "Transporter" },
    { "id": "vw-transporter-t7", "brandId": "volkswagen", "name": "", "slug": "transporter-t7", "series": "Transporter" },
    { "id": "vw-multivan-t4", "brandId": "volkswagen", "name": "Multivan", "slug": "multivan-t4", "series": "Multivan" },
    { "id": "vw-multivan-t5", "brandId": "volkswagen", "name": "Multivan", "slug": "multivan-t5", "series": "Multivan" },
    { "id": "vw-multivan-t6", "brandId": "volkswagen", "name": "Multivan", "slug": "multivan-t6", "series": "Multivan" },
    { "id": "vw-multivan-t7", "brandId": "volkswagen", "name": "Multivan", "slug": "multivan-t7", "series": "Multivan" },
    { "id": "vw-up", "brandId": "volkswagen", "name": "Up!", "slug": "up", "series": "Up" },
    { "id": "vw-vento", "brandId": "volkswagen", "name": "Vento", "slug": "vento", "series": "Vento" },
];
